### ISSUE TITLE
Lomotif Version v1.6.0(1.6.4) latest release installation failed

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#1]
Lomotif latest release v1.6.0(1.6.4) version is not installing when we click on Install button it shows "Unable to Download App" "Lomotif" could not be installed at this time.

It is trying to download the app and able to download but installation has failed. 
Please find below is the screenshot which has been taken on  ipad mini4 UID is: 07301e5763930676711511fd727069ecb09697ed

![img_0036](https://cloud.githubusercontent.com/assets/5388768/12215745/8729a724-b6ef-11e5-862b-454099747d9e.PNG)

and 

iPad air UDID is : e0b97cc667d0607d41508858e0d031e244f66448

![img_0084](https://cloud.githubusercontent.com/assets/5388768/12215759/5a509f40-b6f0-11e5-9645-a9ee3ba4b67b.PNG)

**Comment by tsukisa** [comment]
Turn out to be provisioning profile issue
