### ISSUE TITLE
[1.6.5] Default text for "Share to" is missing a hashtag

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#10]
When sharing to platform like Instagram and Twitter, we're missing a hashtag.

"JustinBieber #lomotif made with @lomotif app" is supposed to be "#JustinBieber #lomotif made with @lomotif app"

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@bef7cf60716bc7dce7f12bf7430649fee9a4b2ec
