### ISSUE TITLE
 [1.7.2] iPhone 6 / 9.2.1- Exporting Saved Projects - App Crashes after Export

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#100]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Load old project (1)
3. Hit export immediately
4. Select “No thanks I’ll share later"
5. Load another old project (2)
6. Hit export immediately
7. Select “No thanks I’ll share later”
8.Repeat 2 to 7
9. App crash

Expected Result: Old projects are exported

Actual Result: Lomotif app crashes

Note: The 4th project loaded and exported should crash the app.

[VIDEO here: https://drive.google.com/a/lomotif.com/file/d/0BwpaGclQTuqqdVUyOFZjMDdKN3c/view]

**Comment by tsukisa** [comment]
@xiuie unable to reproduce
