### ISSUE TITLE
[1.9.45] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - Application is crashing when user exports the Lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1000]
Frequency: Every time.

Precondition: User should be logged in to the application with the account created on iOS previous build. 

Action: 
1: Launch the app.
2: Tap on "Start" button and navigate to "Create" screen with adding motifs and any song.
3: Tap on "Export" option >> "Make Lomotif" button.
4: Export and upload progress will be displayed to the user.
5: Check if the application is crashing when the upload process is completed.

Expected result: Application should not crash when user tries to export the created Lomotif.

Actual result: Application is crashing when user tries to export the created Lomotif. 

Note:
- Please refer the following video link for more details:
https://drive.google.com/file/d/0ByjueaPWc0dwcWd1bHZyQkQycGM/view?usp=sharing

**Comment by hiteshbheda** [comment]
@xiuie Duplicate #957

**Comment by testershub** [comment]
@hiteshbheda the above mentioned issue "#957" is related with cross platform. This issue (#1000) is not related with cross platform. It is reproducible with iOS account only created on the previous build. Please see, it is working as expected with the newly created accounts i.e., on build [1.9.45].

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.46] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1
