### ISSUE TITLE
[1.9.45] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - User is not able to delete a project from "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1003]
Frequency: Every time.

Precondition: User should be logged in to the application.

Action:
1: Launch the app.
2: Swipe up to reveal profile view.
3: Tap on "Lomotifs" tab, list of projects will be displayed.
4: Check if there is delete option available to delete the existing projects.

Expected result: Delete option should be available to delete the existing projects. 

Actual result: Delete option is not displayed.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.45] on iPhone 6 / iOS 10.1.1

In fact, Delete option / functionality is not present.

**Comment by xiuie** [comment]
@testershub Thanks but I will not log this for now as it's not yet build. Please check it for the final regression.
