### ISSUE TITLE
[1.9.45] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - "Camera" option is not displayed to the  user while setting up profile picture. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1004]
Frequency: Every time.

Precondition: User should be logged in to the application.

Action: 
1: Launch the app.
2: Swipe up to reveal profile view.
3: Tap on Profile picture.
4: Check if there is "Camera" option provided to the user.

Expected result: "Camera" option should be provided to the user for clicking and setting a desired Profile picture.

Actual result: "Camera" option is not provided to the user, user will have to scroll through many images to select the desired profile picture. User can not click and update the profile picture.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**But I think it's not a bug**
