### ISSUE TITLE
[1.9.45] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - Posted date is not displayed on the projects at "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1006]
Frequency: Every time.

Precondition:
- User should be logged in to the application.
- There should exists at least one project in "Lomotifs" tab.

Action:
1: Launch the app.
2: Swipe up to reveal profile view.
3: Tap on "Lomotifs" tab.
4: Check if posted date is displayed on the projects. 

Expected result: Posted date should be displayed to the user in "Lomotifs" tab.

Actual result: Posted date should be displayed on the projects in "Lomotifs" tab.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**But I think it's not a bug.**
