### ISSUE TITLE
[1.9.45] iPhone 6 Plus 10.1.1 - Multiple notifications are displayed for same action.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1007]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few motifs.
3: Add / skip the music and proceed to "Create" screen.
4: Lock the device or minimize the app.
5: Check two notifications are displayed for same action.

Expected result: One notification should be displayed for same action.

Actual result: Multiple notifications are displayed for same action.

Refer screenshot for more details:

**Comment by testershub** [comment]
![notifications](https://cloud.githubusercontent.com/assets/18608449/20590960/1b957a66-b24c-11e6-856f-be28c7950e78.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**Comment by xiuie** [comment]
Thanks team, but this is not going to be logged as it's on my end and not the developer's end. Live build experiences will be different.
