### ISSUE TITLE
[1.9.45] iPhone 6S / 10.0.2, iPhone 5S / 9.3.5 - Application is crashing while creating lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1008]
Frequency:Every time

Precondition:
- User should be logged in to the application.
- There should be "Lomotif" under "lomotif" tab.

Action:
1: Launch the app.
2: Swipe up to reveal "profile" view.
3: Tap on "Lomotif" tab and load one "Lomotif".
4: Swipe down to reveal "Home" screen and tap on "START".
5: Select videos/motifs and proceed to "Find music" screen.
6: Add or skip music and tap on "Next" option.
7: Check if application is crashing.

Expected result: Application should not crash and user should be navigate to "Create" screen.

Actual result: Application is crashing while creating lomotif.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iVFdDSGtXQmVxNXM

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.11] on iPhone 7 / 10.2.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.12] on iPhone 7 / 10.2.
