### ISSUE TITLE
 [1.7.2] iPhone 6 / 9.2.1- Editing Saved Projects - Video not exported after changes 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#101]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Load old project 
3. Hit export immediately
4. Hit back
5. Make minor change e.g. turn on filters
Hit export
9. App goes to Share page without exporting

Expected Result: New video is saved to camera roll

Actual Result: Jumps to Share page without exporting

**Comment by tsukisa** [comment]
@xiuie unable to reproduce
