### ISSUE TITLE
[1.9.46] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Lomotif under "Lomotifs" tab is not playing.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1013]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few motifs.
3: Skip the music and proceed to "Create" screen.
4: Tap on "Export" option.
5: Tap on "Make Lomotif" button.
6: Skip the sharing and navigate to "Lomotifs" tab.
7: Load the recently created lomotif project.
8: Check if lomotif project loads and starts playing.

Expected result: 
1: Thumbnail should be displayed for lomotif project under "Lomotifs" tab.
2: Lomotif project should load and starts playing.

Actual result: 
1: Thumbnail of lomotif project is not displayed (Black thumbnail is displayed)
2: Lomotif is not playing when user load the recently created lomotif project.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iTDNielJlY2JaNEE

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**But if we create lomotif with Camera Video then it plays properly while loading from Lomotif tab.**

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2.
