### ISSUE TITLE
[1.9.46] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is crashing after tapping on "Make Lomotif" button.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1015]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select 1 video for "All videos" folder.
3: Skip / add the music and proceed to "Create" screen.
4: Tap on "Export" option.
5: Tap on "Back" option.
6: Tap on "Export" option.
7: Tap on "Make Lomotif" button.
8: Check if application is crashing.

Expected result: Application should not crash after tapping on "Make Lomotif" button.

Actual result: 
1: Application is crashing after tapping on "Make Lomotif" button.
2: Sometimes error message "The operation couldn't completed..." is displayed after tapping on "Make Lomotif" button.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ib1p3X1RqY3lfRkk

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**Instead of Crashing, I get Error "The operation couldn't be completed. (Cocoa error -1)"**

![img_1909](https://cloud.githubusercontent.com/assets/9691390/20627166/58ab50d0-b344-11e6-8823-b160583055b2.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2
As user is not able to navigate back.

**Comment by xiuie** [comment]
@testershub We may introduce back button again, so please check again after.
