### ISSUE TITLE
[1.9.46] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is crashing when user navigate back to "Create" screen from "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1016]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few motifs.
3: Add / skip the music and proceed to "Create" screen.
4: Tap on "Export" option.
5: Tap on "Make Lomotif" button.
6: Immediately tap on back option to navigate back to "Create" screen.
7: Check if application is crashing.

Expected result: Application should not crash when user navigate back to "Create" screen from "Saving your Lomotif" screen.

Actual result: Application is crashing when user navigate back to "Create" screen from "Saving your Lomotif" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3idHhzSWpGOVk0OHM

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**Instead of Crashing, I get Error "The operation couldn't be completed. (Cocoa error -1)"**

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2
As user is not able to navigate back.
