### ISSUE TITLE
[1.9.46] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is crashing while deleting the lomotif project under "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1018]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few motifs.
3: Skip the music and proceed to "Create" screen.
4: Tap on "Export" option.
5: Tap on "Make Lomotif" button.
6: Skip the sharing and navigate to "Lomotifs" tab.
7: Load the recently created lomotif.
8: Observed preview is not playing.
9: Tap on three dots at top right corner.
10: Tap on "Delete" option on pop up.
11: Tap on "YES" option on pop up.
12: Check if application is crashing.

Expected result: Application should not crash when user deletes the lomotif from "lomotifs" tab.

Actual result:
1: Application is crashing while deleting the lomotif project under "Lomotifs" tab.
2: "Removing lomotif" is continuously displayed when user deletes the existing lomotif project.

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwZnktX1kyZ2RwbDA

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.46] on iPhone 6 / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.47] on iPhone 6 / iOS 10.1.1

Instead, "Removing" process starts and never ends

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2
