### ISSUE TITLE
[1.9.47] iPhone 6 / 10.1.1- Upload failed - Export lomotif and after 100% upload it shows "upload failed"

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1022]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Create lomotif with photos / motifs and music
4. Click on Export
5. Exported project will be uploaded 100%
6. Go to "In Progress" tab and check whether project uploaded or not

Expected result: Project should be uploaded successfully

Actual result: Project uploaded 100% but on "In progress" tab it shows "Upload failed"

![1](https://cloud.githubusercontent.com/assets/9691390/20651171/dab44f10-b505-11e6-92fe-802762002ba1.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.47] on iPhone 5S / 9.3.5.

One more observation, "Upload Failed" error message is displayed on thumbnail when user taps on "Make Lomotif" button and navigate back to "Create" screen while uploading.

**Comment by xiuie** [comment]
Odd I can't reproduce it on my iPhone 6s/10.1.1 for build [1.9.47]

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1

You can close this issue for build 1.9.52

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.1] on iPhone 6S / 10.0.2
Upload failed is displayed after lomotif uploaded 100%.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.3] on iPhone 5S / 9.3.5.
"Uploading failed" is displayed for lomotif in "In Progress" tab even when uploading process completed 100%.
