### ISSUE TITLE
[1.9.47] iPhone 6 / 10.1.1- Upload and Save option not available - Click on "Upload failed Retry" option and click on Export option

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1023]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Create lomotif with photos / motifs and music
4. Click on Export
5. Exported project will be uploaded 100%
6. Go to "In Progress" tab and there will be "Upload failed Retry" display on lomotif  thumbnail
7. Click on "Upload failed Retry" from thumbnail icon
8. User will be navigated to create screen
9. Click on Export 
10. Check whether user is asked to upload and save option

Expected result: User should be asked for "Upload" and "Save" option, once he/she clicks on "Upload failed Retry" and follows steps again

Actual result: User is not asked for "Upload" and "Save" options

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.47

**Comment by hiteshbheda** [comment]
@xiuie I think it works as design. 

It takes some time to upload the created lomotif. Now it gives me 2 options "Open project"and "Dismiss". When I click on "Open project" then only it opens the project.
