### ISSUE TITLE
[1.9.47] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is crashing when user uncheck "Save to Gallery" checkbox and taps on back option while exporting.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1025]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs and with/ without music.
3: Tap on "Export" option.
4: Tap on "Make Lomotif" button.
5: Immediately tap on back option "<".
6: Observe error message "The operation couldn't be completed..." is displayed.
7: Tap on "OK" option on error message and again tap on "Export" option.
8: Repeat step-5 to step-7 again.
9: Uncheck "Save to Gallery" checkbox and tap on "Make Lomotif" button.
10: Immediately tap on back option "<".
11: Check if application is crashing.

Expected result: Application should not crash when user uncheck "Save to Gallery" checkbox and taps on back option while exporting.

Actual result:  Application is crashing when user uncheck "Save to Gallery" checkbox and taps on back option while exporting.

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwLVJxRHQyNEZjYms

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.47

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2
As user is not able to navigate back to "Create" screen while "Saving your Lomotif" progress is going on.
