### ISSUE TITLE
[1.7.2] iPad Mini / 9.2.1- Thumbnails are blurry

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#103]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select video
3. Previews are blur on iPad

Expected Result: Ability to see what the clips contain

Actual Result: Very blur previews

![1 7 2 issue alert_ blur previews png](https://cloud.githubusercontent.com/assets/16533289/13025487/874f4d34-d243-11e5-892c-bbda2e1053ef.jpeg)

**Comment by benchang** [comment]
@pmtheint this is a product decision, please take note and then close

**Comment by pmtheint** [comment]
Closed. Move to Asana.
