### ISSUE TITLE
[1.9.47] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - Application is crashing while sharing the lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1031]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few motifs.
3: Skip / add music and proceed to "Create" screen.
4: Tap on "Export" option.
5: Tap on "Make Lomotif" button (User will be navigated to "Share" screen)
6: Tap on "Instagram / Twitter" option. (Share pop-up will be displayed.)
7: Tap on "X" option on sharing screen (Not on "Share pop-up)
8: Warning message "Are you sure you don't want to share..." pop up.
9: Tap on "Cancel" option on warning message.
10: Tap on "Share" option on "Share pop-up".
11: Check if application is crashing.

Expected result: Application should not crash while sharing the lomotif.

Actual result: Application is crashing while sharing the lomotif.

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dweUswOExKcUQwd28

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.47

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 5S / 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2 without login.

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.4] on iPhone 6 Plus / 10.1.1. 
Please see, issue is observed when user is not logged in.
