### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- Error on profile picture change - Try to change profile picture

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1032]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Click on User icon on Home screen
4. Tap on profile picture to change it
5. Select any picture from camera folder
6. Click on Yes for "Do you want to replace your profile picture?' popup message
7. Check whether user can change profile picture or not

Expected result: Profile picture should be changed

Actual result: When user tries to change profile picture, it provides an Error

![img_1937](https://cloud.githubusercontent.com/assets/9691390/20759974/929a088c-b744-11e6-9e2a-150f8b9b4aab.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1 and iPad Mini 3 / 9.3.4.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
