### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- Error on change username - Change username and provide valid username

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1033]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on username field to change username
5. On next screen, enter any valid username
6. Check whether user is able to change username or not

Expected result: User should be able to change username

Actual result: When user change and enter valid username it display error on the screen

![img_1938](https://cloud.githubusercontent.com/assets/9691390/20761634/9be73220-b749-11e6-8042-b232e7b51828.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1 and iPhone 5S / 9.3.5.

Please see, issue is reproducible only when user is logged in on two different devices with same credentials and try to change any profile information.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
