### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- Error on Display name - Change Display name and provide valid username

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1034]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on Display name field to change Display name
5. On next screen, enter valid Display name
6. Check whether user is able to change Display name or not

Expected result: User should be able to change Display name

Actual result: Error message display

![display name](https://cloud.githubusercontent.com/assets/9691390/20762145/7535ac18-b74b-11e6-98f2-b6b4d79774c8.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2, iPhone 5S / 9.3.5 and iPad Mini 3 / 9.3.4.

Please see, issue is reproducible only when user is logged in on two different devices with same credentials and try to change any profile information.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
