### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- "Error-Unknown" Error - Change Caption and provide valid Caption

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1036]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on Caption field to change Caption
5. On next screen, enter valid caption
6. Check whether user is able to change Caption or not

Expected result: User should be able to change Caption

Actual result: Error message "Error-Unknown" display

![caption](https://cloud.githubusercontent.com/assets/9691390/20762915/0cc42e0e-b74e-11e6-8f44-8aeb4561e2f6.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.
User is able to change "Caption" successfully.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
