### ISSUE TITLE
[1.9.48] iPhone 6 / 10.1.1- "Error-Unknown" Error - Change Password and provide valid password

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1037]
Frequency: Every time

Action:
1. Launch the app
2. Login with valid credentials
3. Go to User profile information page
4. Click on Password field to change Password
5. On next screen, enter current password and also enter valid new password and repeat password
6. Check whether user is able to change Password or not

Expected result: User should be able to change Password

Actual result: Error message "Error-Unknown" display

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.48] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
