### ISSUE TITLE
[1.7.2] iPhone 6 & iPad Mini / 9.2.1- "Find Music” pull-to-refresh - Stuck at Loading

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#104]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select video
3. In “Find Music” pull to refresh

Expected Result: Reloads songs

Actual Result: Stuck on “Loading"

Note: Does this only happen for Soundcloud music?

![slack for ios upload](https://cloud.githubusercontent.com/assets/16533289/13026489/f4cc8226-d263-11e5-9649-ab30643f0826.jpg)

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@b955e7aa462d5444e94b788fbc6d1de009b925e9
