### ISSUE TITLE
[1.9.48] iPhone 6 Plus / 10.1.1, iPhone 5S / 9.3.5 - Application is crashing after tapping on "Lomotifs" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1044]
Frequency: Every time

Precondition: User should be logged out.

Action:
1: Launch the app.
2: Tap on "Skip Now" option.
3: Tap on "START" and select 3 videos from "Instagram".
4: Add music from "My Music" tab and proceed to "Create" screen.
5: Processing will be displayed.
6: Save the lomotif when 1 or 2 lomotifs loads (Processed).
7: Tap on user icon to reveal profile view.
8: Tap on "Lomotifs" tab.
9: Check if application is crashing.

Expected result: Application should not crash after tapping on "Lomotifs" tab.

Actual result: Application is crashing after tapping on "Lomotifs" tab.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3ieDY0eWh5aDZUZk0

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.48] on iPhone 6 / iOS 10.1.1

**Application crash after step no. 6**

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Application is crashing after step 6**

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6Plus / 10.1.1
