### ISSUE TITLE
[1.7.2] iPhone 6 & iPad Mini / 9.2.1- Instagram Photo & Videos - App Crash

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#105]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select Instagram videos and photos
3. Select Music
4. On Create screen, tap video thumbnail to change highlight moment etc.
5. App crashes

Expected Result: Editing instagram video/photos

Actual Result: App crashes

**Comment by benchang** [comment]
Feels like the Instagram selected videos are not done downloading (app crashes when you try to select bubble before it's done dl'ing)

**Comment by tsukisa** [comment]
@xiuie @benchang sounds like it's related to #85, please verify

**Comment by benchang** [comment]
#85 is closed so this should be closed too
