### ISSUE TITLE
[1.9.49] iPhone 6 / 10.1.1- Snapchat sharing not working - Create lomotif and share it over snapchat

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1052]
Frequency: Every time

Pre-requisite: 
1. User should be logged out / signed out from Lomotif account
2. User should be logged into Snapchat account

Action:
1. Launch the app
2. Create lomotif with motifs and with / without song
3. Click on Export
4. On "Share your Lomotif" screen, click on Snapchat icon
5. Snapchat app will be open
6. Check whether user is able to share lomotif on Snapchat or not

Expected result: User should be able to share lomotif on snapchat

Actual result: User is not able to share lomotif on snapchat

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.49] on iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by xiuie** [comment]
@hiteshbheda @testershub While in Snapchat, swipe up to access "Memories / Camera Roll". Just tried it and it works. Can I close this?

**Comment by hiteshbheda** [comment]
@xiuie Yes yes, Thanks. 

You can close this issue now.
