### ISSUE TITLE
[1.9.49] iPhone 6 / 10.1.1- "Facebook upload failed" error - Create lomotif and share it over Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1053]
Frequency: Every time

Pre-requisite: User should be logged out / signed out from Lomotif account

Action:
1. Launch the app
2. Create lomotif with motifs and with / without song
3. Click on Export
4. On "Share your Lomotif" screen, click on Facebook icon
5. Check whether user is able to share lomotif on facebook or not

Expected result: User should be able to share lomotif on Facebook

Actual result: "Facebook upload failed" Error message display

![img_1962](https://cloud.githubusercontent.com/assets/9691390/20802239/7446dcac-b811-11e6-9694-fd222dec062e.PNG)

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.49

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1

**Issue has been resolved in iOS build [1.9.52]**

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
