### ISSUE TITLE
[1.9.49] iPhone 6 / 10.1.1- Lomotif does not play under "Lomotifs" tab - Create and export lomotif and play it from "Lomotifs" tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1054]
Frequency: Every time

Precondition: There should not be any lomotif under "Lomotifs" tab.

Action:
1. Launch the app and login with valid credentials
2. Tap on "START" 
3. Create lomotif with few motifs
4. Tap on "Export" 
5. Click on "Make Lomotif" button and skip sharing
6. Go to "Lomotifs" tab, Lomotif uploading progress will be displayed
7. Lomotif is available under "Lomotifs" tab once upload finish
8. Click on lomotif available in "Lomotifs" tab, check whether selected lomotif starts playing or not

Expected result: Selected lomotif should start playing

Actual result: Lomotif is not playing

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.49] on iPhone 6S / 10.0.2.
Uploaded lomotif is not tappable on "lomotifs" tab.
It is working as expected when user kill the app and relaunch it.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**IMPORTANT:** 
**1. When upload process successfully completes then also clicking / tapping on exported lomotif (available under "Lomotif" tab does not work.**

**2. If we close / kill the app and then again restart app and then try to open existing lomotif then it works perfectly.**

**Comment by hiteshbheda** [comment]
@xiuie I can't exactly reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1

**Few very strange points I have observed for this issue:**

**1. Once upload process successfully completes, lomotif will display in "Lomotifs" tab at respective user login. When user clicks on lomotif thumbnail then it does not open / load.** 

**2. But when user clicks at TOP LEFT CORNER or BOTTOM LEFT CORNER of lomotif thumbnail then it will open. (Sometimes works when user clicks on Top Right corner or Bottom Right corner)**

**3. By close / kill the app and then again restart app and then try to open existing lomotif then it works perfectly.**

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
