### ISSUE TITLE
[1.9.49] iPhone 6 / 10.1.1- No message display in Lomotifs tab - Create and export lomotif and delete it from "Lomotifs" tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1055]
Frequency: Every time

Precondition: There should not be any lomotif under "Lomotifs" tab.

Action:
1. Launch the app and login with valid credentials
2. Go to "Lomotifs" tab and check there will be message displayed "Nothing here yet. Start uploading your project..."
3. Tap on "START"
4. Create lomotif with few motifs
5. Tap on "Export"
6. Click on "Make Lomotif" button and skip sharing
7. Go to "Lomotifs" tab, Lomotif uploading progress will be displayed
8. Lomotif is available under "Lomotifs" tab once upload finish
9. Close the app
10. Relaunch the app again
11. Go to "Lomotifs" tab
12. Click on available lomotif 
13. Tap on Menu option and Remove lomotif
14. Now, observe whether "Nothing here yet. Start uploading your project..." message is displayed or not

Expected result: "Nothing here yet. Start uploading your project..." message should be displayed

Actual result: "Nothing here yet. Start uploading your project..." message does not display after removing / deleting lomotif

![1](https://cloud.githubusercontent.com/assets/9691390/20805118/7f7940f6-b81b-11e6-95f0-f4f65d81046b.PNG)

![2](https://cloud.githubusercontent.com/assets/9691390/20805117/7f788c56-b81b-11e6-8009-1f777431764f.PNG)

![3](https://cloud.githubusercontent.com/assets/9691390/20805119/7f7a2b06-b81b-11e6-95d7-a19ec59336ec.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.49] on iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1
