### ISSUE TITLE
[1.7.2] iPhone 6 & iPad Mini / 9.2.1- Tap on video thumbnails multiple times - App crash

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#106]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Select video (around 12 video clips)
3. Select music
4. On create screen, rapidly tap on various thumbnails e.g. with three fingers

Expected Result: the last thumbnail loads

Actual Result: App crash

[VIDEO AVAILABLE]

**Comment by tsukisa** [comment]
Duplicate of #80
