### ISSUE TITLE
[1.9.51] iPhone 6S / 10.0.2 - Eye icon is not displayed on "Lomotif" when user select/ checked "For my eyes only" checkbox on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1062]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs with / without music.
3: Tap on "Export" option.
4: Check "For my eyes only" checkbox and tap on "Make Lomotif" button.
5: Skip sharing and navigate to "lomotifs" tab.
6: Check if lock icon is displayed on "Lomotif" thumbnail.

Expected result: Lock icon should be display on "Lomotif" when user select/ checked "For my eyes only" checkbox on "Saving your Lomotif" screen.

Actual result: Lock icon is not displayed on "Lomotif" when user select/ checked "For my eyes only" checkbox on "Saving your Lomotif" screen.

**Comment by Dipamit** [comment]
@xiuie: On skip sharing, Page navigate to Profile page and "In Progress" tab "Upload failed" displayed for thumbnail.

![img_5296 1](https://cloud.githubusercontent.com/assets/17335200/20882403/cf833cd0-bb06-11e6-951f-a022a1abcc6a.PNG)

**Comment by xiuie** [comment]
I can reproduce this on my iPhone 6s + for build [1.9.51]

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1
