### ISSUE TITLE
[1.9.51] iPhone 6S / 10.0.2 - "Uploading failed" message is displayed on lomotif thumbnail after uploading progress completes (100 %).

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1064]
Frequency: Every time

Action: 
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs.
3: Tap on "Export" option.
4: Tap on "Make Lomotif" button and skip sharing.
5: Observe "Uploading lomotif" progress will be displayed on the lomotif thumbnail.
6: Kill / quite the app and relaunch it.
7: Load the recently exported lomotif.
8: Tap on "Export" option and add caption to the lomotif.
9: Tap on "Make Lomotif" button and skip the sharing.
10: Wait till the uploading process completes.
11: Check if "Uploading failed" message is displayed when uploading completes (100%).

Expected result: Lomotif should be upload successfully without any error and display under "Lomotif" tab.

Actual result: "Uploading failed" message is displayed on lomotif thumbnail after uploading progress completes (100 %).

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSFJwQVV3Qy05UGs

**Comment by Dipamit** [comment]
@xiuie: I am able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.51

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Works perfectly**

**Comment by testershub** [comment]
@xiuie I can't reproduced this issue for build [1.9.52] on iPhone 6S / 10.0.2.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.12] on iPhone 6 Plus / 10.1.1
