### ISSUE TITLE
[1.9.51] iPhone 6S / 10.0.2 - User is not able to enter the caption on "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1069]
Frequency: Every time

Action:
1: Launch the app and log in with valid credential.
2: Tap on "START" and create lomotif with few "Video/motifs".
3: Proceed to create screen with/without music.
4: Tap on export option and tap on text field to add caption(Keypad will be displayed and user able to add caption).
5: Tap on back "<" option and navigate back to "Create" screen.
6: Tap on export option, user will be navigated to "Saving your Lomotif" screen.
7: Tap on text field to add caption.
8: Check if user is able to enter the caption.

Expected result: User should able to enter the caption on "Saving your Lomotif" screen.

Actual result: 
1: User is not able to enter the caption on "Saving your Lomotif" screen.
2: After that user is not able to enter caption for any lomotif till user kill the app and open again.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iYjAtU3pHYU1tUDg

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2 and iPhone 6 Plus / 10.1.1.
