### ISSUE TITLE
[1.9.51] iPhone 6S / 10.0.2 - "Search" field is not functional on "Motifs and find music" tabs.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1070]
Frequency: Every time

Action:
1: Launch the app and log in with valid credential.
2: Tap on "START" and create lomotif with few "Video/motifs".
3: Proceed to create screen with/without music.
4: Tap on export option and tap on text filed to add caption.
5: Tap on back "<" option and navigate back to "Create" screen.
6: Tap on "Home" option and navigate to "Home" screen with/without saving lomotif.
7: Tap on "START" and navigate to "Camera roll" screen.
8: Tap on "Motif" tab and tap on "Search" option.
9: Check if "Search" field is not functional.

Expected result: "Search" field should be functional on "Motifs and find music" tabs.

Actual result: "Search" field is not functional on "Motifs and find music" tabs.

Note:
1: All text fields on user profile are also not functional. 
2: All text fields are functional after kill the app and relaunch.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iaWNfQTN0ZUtqSDg

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 Plus / 10.1.1.

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.51

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.51] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2 and iPhone 6 Plus / 10.1.1.
