### ISSUE TITLE
[1.9.52] iPhone 6 / 10.1.1- Caption (Lomotif Description) displays - Create, Export and Make lomotif and Don't enter any description for lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1072]
Frequency: Every time

Action:
1. Launch the app and login with valid credentials
2. Tap on "START"
3. Create lomotif with few motifs
4. Tap on "Export"
5. On "Saving your Lomotif" screen, don't enter any text value in "Say something about this Lomotif" section
6. Tap on "Make Lomotif" button
7. On "Share your Lomotif" screen, click on "Skip sharing"
8. Go to Lomotifs tab on User profile page
9. Open recently Exported and Uploaded lomotif
10. Check whether "Say something about this Lomotif" message display during lomotif playing or not

Expected result: 
1. "Say something about this Lomotif" message should not display on lomotif during playing
2. If user enter any value for "Say something about this Lomotif"  then only value should be display

Actual result: Even if user has not enter any value in "Say something about this Lomotif"  section, then also message display during lomotif playing

![img_2046](https://cloud.githubusercontent.com/assets/9691390/20912897/443c917e-bb99-11e6-8fad-6a3dc63e7631.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.52] on iPhone 6 Plus / 10.1.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
