### ISSUE TITLE
[1.9.52] iPhone 6S / 10.0.2 - Application is crashing after tapping on "Make Lomotif" button.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1077]
Frequency: 7 / 10

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs.
3: Tap on "Export" option.
4: Tap and hold "Make Lomotif" button for few secs and release.
5: Check if application is crashing.

Expected result: Application should not crash after tapping on "Make Lomotif" button.

Actual result: Application is crashing after tapping on "Make Lomotif" button.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iNzA4Vjl0RVhIY0k

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.52] on iPhone 6 Plus / 10.1.1

**Comment by xiuie** [comment]
I can't reproduce this issue for build [1.9.52] on iPhone 6s / iOS 10.1.1. Tried 5 times.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.53] on iPhone 6 / iOS 10.1.1

I have tried more than 7 times but no crash.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1
