### ISSUE TITLE
[1.9.52] iPhone 6S / 10.0.2 - User is not able to delete selected music from "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1080]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs with music.
3: Navigate to music section on "Create" screen.
4: Check if delete option is displayed on music thumbnail.

Expected result:
1: Delete option should be display on music thumbnail on "Create" screen.
2: User should be able to delete selected music from "Create" screen.

Actual result: "Delete" option is not displayed on music thumbnail on "Create" screen.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.53

**Comment by xiuie** [comment]
This is works as designed for now. have informed developer about difference between android and iOS builds.
