### ISSUE TITLE
[1.9.53] iPhone 6 / 10.1.1- User can log in without Email - Do sign up process and remove Email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1083]
Frequency: Every time

Pre-requisite: Log out from Lomotif account

Action:
1. Launch the app
2. On Sign up page, Enter Email and Password in respective field
3. Click on Sign up button
4. Enter @username in username field
5. Remove Email from Email field
6. Click on Let's go button
7. On popup, click on "Proceed without Email" 
8. Check whether user is able to create account or not

Expected result: User should not be able to create account without Email

Actual result: User is able to create account without Email

**Comment by Dipamit** [comment]
@xiuie: I am able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.53

**Comment by xiuie** [comment]
Yes you can log in without email although you are encourage to add your email to safeguard your account.
