### ISSUE TITLE
[1.9.53] iPhone 6 Plus / 10.1.1 - Section under "Preview" is not scrollable on "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1088]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif with few motifs.
3: Enter title.
4: Check if section is scrollable or not.

Expected result: Section under "Preview" should be scrollable on "Create" screen.

Actual result: Section under "Preview" is not scrollable on "Create" screen after entering the title.

Note: Similar issue is observed when user in not logged in.

Please refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iV3c0OXkyd0Z5VU0

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.53] on iPhone 6S / 10.0.2

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
