### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- My Videos Page - Albums wrongly titled

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#109]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Go to My Videos
3. Notice that 2 albums are labelled "All Photos"

Expected Result: Albums are "All Videos" "All Photos" and "Camera Roll" etc.
Actual Result: Two albums are labelled "All Photos" but have different content

![slack for ios upload-2](https://cloud.githubusercontent.com/assets/16533289/13033554/adc73d74-d355-11e5-892f-5d7cd329fe86.jpg)

**Comment by benchang** [comment]
should be a fast fix

**Comment by tsukisa** [comment]
somehow xiu's Camera Roll is named as All Photos by iOS
