### ISSUE TITLE
[1.9.53] iPhone 6S / 10.0.2 - "Operation stopped" message is displayed when user navigate back to "Create" screen from "Saving your Lomotif" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1091]
Frequency: Every time

Action:
1: Launch the app login with valid credential.
2: Tap on "START" and create lomotif with videos.
3: Proceed to "Create" screen with/without music.
4: Apply filter and tap on export option.
5: Tap on back"<" option and navigate to "Create" screen.
6: Check is "Operation stopped" message is displayed.

Expected result: "Operation stopped" message should not display.

Actual result: "Operation stopped" message is displayed when user navigate back to "Create" screen from "Saving your Lomotif" screen

Refer following video for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iVlhVRjQ5eUFRcUk

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.53] on iPhone 6 Plus / 10.1.1.

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.53

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1.
