### ISSUE TITLE
[1.9.53] iPhone 6 Plus / 10.1.1 - Application is crashing while exporting the lomotif. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1093]
Frequency: Every time

Action:
1: Launch the app.
2: "Song of the day" pop up will appears.
3: Tap on "USE" option on pop up and select 1 music and tap on "Next" option.
4: Select 1 video from "Snapchat" and proceed to "Create" screen.
5: Tap on asset's thumbnail and drag the timeframe to the right till the end.
6: Enable sticker and filter toggle button.
7: Tap on "Export" option ("Too few video clips" pop up will appears)
8: Tap on "Proceed" option on pop up.
9: Tap  multiple times on export option ("Baking in video effects" progress will be displayed)
10: Check if application is crashing or not.

Expected result: Application should not crash while exporting the lomotif.

Actual result: Application is crashing while exporting the lomotif. 

Please refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwUzU1THVXYTBkSGM

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.53

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.53] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
