### ISSUE TITLE
[1.9.53] iPhone 6S / 10.0.2 - "Song of the day" list is getting disappeared when user tap on "Search" option and cancel search.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1099]
Frequency: Every time

Action:
1: Launch the app login with valid credential.
2: Wait for "Song of the day" pop up to display.
3: Tap on "Use" option, user will be navigated to "Find music" screen.
4: "Songs of the day" list will be displayed, tap on one song.
5: Tap on "Search" field and tap on "Cancel" option.
6: Check if "Song of the day" list is getting disappeared.

Expected result: "Song of the day" list should not get disappear.

Actual result:  
1: "Song of the day" list is getting disappeared when user tap on "Search" option and cancel search.
2: Default music list is displayed and previously selected song name is not displayed.

Refer following video for more details:
https://drive.google.com/open?id=0B4_JwxP0qsl1NTZHX2liZEw3Y2s

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.53] on iPhone 6 Plus / 10.1.1.

**Comment by xiuie** [comment]
Don't worry about this for now. I would say it's expected behavior.
