### ISSUE TITLE
[1.6.5] Project saves even if I try NOT to save it 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#11]
How to replicate:
1. Start
2. Select videos
3. Skip song (only because I can't add songs)
4. Export video
5. hit back
6. Hit "Home"
7. Opt NOT to save your project
Expected: The app returns to Home,with no new project thumbnails
Actual: The app returns to Home but you see the thumbnail of a project that you've just created

**Comment by tsukisa** [comment]
Project is now auto saved if the user exported at least once
