### ISSUE TITLE
[1.9.53] iPhone 6S / 10.0.2 - "Upload failed" is displayed when user add max length(100 words) text in "Caption" field.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1100]
Frequency: Every time

Action:
1: Launch the app login with valid credential.
2: Tap on "START" and create lomotif with videos.
3: Proceed to "Create" screen with/without music.
4: Tap on export option and navigate to "Saving your Lomotif" screen.
5: Add max length(100 words) text in "Caption" field and tap on "Make Lomotif" button.
6: Skip sharing and navigate to "Lomotifs" tab.
7: Wait for few secs.
8: Check if "Upload failed" is displayed on "In progress" tab.

Expected result: Uploading process should be successfully complete and lomotif should be display under "Lomotifs" tab.

Actual result:  "Upload failed" is displayed when user add max length(100 words) text in "Caption" field.

Refer following video for more details:
https://drive.google.com/open?id=0B4_JwxP0qsl1QmthX0gzUUlLa2c

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.53] on iPhone 6 Plus / 10.1.1.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.53

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6S / 10.0.2
