### ISSUE TITLE
[2.1.1] iPhone 6S / 10.0.2 - Irrelevant pop up message is displayed on "Featured videos" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1117]
Frequency: Every time

Action:
1: Launch the app.
2: Swipe right to view "Featured videos".
3: Check if irrelevant pop up message is displayed.

Expected result: Irrelevant pop up message should not be display.

Actual result: Irrelevant pop up message is displayed on "Featured videos" screen.

Refer following screenshot for more details:
![dump](https://cloud.githubusercontent.com/assets/24311318/21051061/725dee92-be44-11e6-964b-812c202847d0.jpg)

**Comment by xiuie** [comment]
Thanks! But we're testing something.
