### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- Motifs Page - Every time you close an album, jumps back to #1

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#112]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Hit Start
3. Tap Motifs tab
4. Scrub down all the way to open an album (e.g. #101 album)
5. Close the album
6. We see the top-listed albums 

Expected Result: See albums ranked in the 90s or 100s.
Actual Result: See top albums

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@d1f686397c7612f1fe1de97db4193e434441fd8a
