### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Albums - All photos disappear after pull down to refresh all items

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#113]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select All Photos album
4. Pull down to refresh all items

Expected result: All photos should appear in album

Actual result: Empty screen appears every time
[pull_down_to refresh.zip](https://github.com/Lomotif/lomotif-ios-issues/files/136107/pull_down_to.refresh.zip)

**Comment by xiuie** [comment]
I can replicate this.

**Comment by tsukisa** [comment]
issue has been resolved
