### ISSUE TITLE
[2.1.2] iPhone 6S / 10.1.1 - App user profile picture change automatically - Login to lomotif app and on "Follow User" screen -> change profile pic of other searched user

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1138]
Frequency: Everytime

Pre-requisite: User should be logged IN to lomotif app account

Action:
1. Launch the app
2. Login to Lomotif app with valid credentials
3. Go to user profile information page and observe profile picture of logged in user's account
4. Click on "Follow User" icon on top of the screen
5. Search for any lomotif user
6. Select and follow any user from the list
7. Now, go to followed user information page
8. Click on Profile picture of followed user to change it
9. Select any image from device storage
10. Profile picture of followed user will be changed
11. Now go back at Home screen
12. Search for own username on "Follow User" screen
13. Check whether logged in user / own profile picture is automatically updated or not

Expected result: When lomotif application user change other user's profile picture at "Follow user" screen then lomotif logged in user's profile picture should not be automatically updated

Actual result: When lomotif app user (logged in user) is changing other user's profile picture on  "Follow user" screen then lomotif app user (logged in user) (own) profile picture is automatically updated

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.2] on iPhone 6S / 10.0.2

**Comment by xiuie** [comment]
supposedly fixed
