### ISSUE TITLE
[2.1.2] iPhone 6S / 10.1.1 - Lomotif count is 0 - Login to lomotif app and check the number of lomotifs count display on user profile page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1139]
Frequency: Everytime

Pre-requisite: User should be logged IN to lomotif app account (Few lomotifs should be available to logged in user's account at "Lomotifs" tab)

Action:
1. Launch the app
2. Login to Lomotif app with valid credentials (Few lomotifs should be available to logged in user's account at "Lomotifs" tab)
3. Go to user profile page
4. Tap on "Lomotif" tab
5. Observe and make sure few / many lomotifs already available in "Lomotif" tab
6. Now check whether the Lomotif count displays the same number as available in "Lomotif" tab

Expected result: Exact lomotif count (based on number of available lomotifs exist in "Lomotif" tab) should be displayed on User profile page

Actual result: Lomotif count always display as 0 for all users even though many lomotifs available for that user's account

**Comment by xiuie** [comment]
I can reproduce this for 2.1.2 for my iPhone 6S.

**Comment by Aboli-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.4] on iPhone 6 Plus / 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [2.1.4] on iPhone 6S / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.8] on iPhone 6 / iOS 10.2

**Currently, instead of lomotif count 0, it is non-zero but wrong value displays.**

**Comment by xiuie** [comment]
supposedly fixed
