### ISSUE TITLE
[2.1.2] iPhone 6S / 10.1.1 - Right to Left slide not working for Notification - Slide Home screen from Right to Left side to navigate to Notification area

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1145]
Frequency: Everytime

Action:
1. Launch the app
2. Slide Home screen from Left to Right side, it works and navigates user to  Media screen
3. Now, Slide Home screen from Right to Left side
4. Check whether user navigates to Notification screen / area or not

Expected result: When user Slide Home screen from Right to Left side, he/she should be navigated to Notification screen / area

Actual result: Sliding Home screen from Right to Left slide not working to navigate to Notification screen / area

![img_0994](https://cloud.githubusercontent.com/assets/9691390/21301583/f63015fa-c5d4-11e6-887c-5da0432943f7.PNG)

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this for build [2.1.2] on iPhone 6S / 10.0.2

**Comment by xiuie** [comment]
Thanks but I checked with the designer and she said this is Works as Designed.

**Comment by hiteshbheda** [comment]
@xiu Thanks for update
