### ISSUE TITLE
[2.1.2] iPhone 6S / 10.0.2 - Irrelevant pop up: "Do you want to make your lomotif public" message is displayed when user try to make lomotif as "Private".

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1156]
Frequency: Every time

Precondition:
- There should be some lomotif under "Lomotif" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe up to reveal "Profile" screen.
3: Navigate to "Lomotifs" tab and open one lomotif (Lomotif should be public).
4: Tap on "Menu" option and select "Make lomotif private" option.
5: Check if the irrelevant pop up: "Do you want to make your lomotif public" message is displayed.

Expected result: Irrelevant pop up: "Do you want to make your lomotif private" message should be display.

Actual result: Irrelevant pop up: "Do you want to make your lomotif public" message is displayed when user try to make lomotif as "Private".

Note: Irrelevant pop up: "Do you want to make your lomotif private" message is displayed when try to make lomotif as "Public".

Refer following screenshot for more details:
![private](https://cloud.githubusercontent.com/assets/24311318/21304360/b4c08ee0-c5ea-11e6-9d4f-b51d5baef4b1.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.2] on iPhone 6S / iOS 10.1.1

**Comment by xiuie** [comment]
supposedly fixed
