### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Albums - Application hangs when user plays some videos

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#116]
Frequency: Once

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Select nicki minay album
5. Play some videos

Expected result: Application crashes after playing of seventh video

Actual result: Application should not crash

**Comment by xiuie** [comment]
I couldn't replicate this @benchang Give it a go?

**Comment by benchang** [comment]
Application does hang after playing a few videos in succession, but will begin to work again after a few seconds...

**Comment by benchang** [comment]
This may actually be related to UXCam...

**Comment by benchang** [comment]
This requires some investigation..

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.5 on iPad 2 iOS 9.3.1
