### ISSUE TITLE
[2.1.2] iPhone 6S / 10.0.2 - Lomotif privacy is not changing to private when user try to make lomotif as private.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1162]
Frequency: Every time

Precondition:
- There should be some lomotifs under "Lomotifs" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe up to reveal "Profile" screen.
3: Navigate to "Lomotifs" tab and open one lomotif (Lomotif which is public).
4: Tap on "Menu" option and select "Make Lomotif Private" option.
5: Tap on "Yes" option and navigate to "Lomotifs" tab.
6: Check if the lomotif privacy is changing to "Private".

Expected result: Lomotif privacy should change to private and "Eye" icon should be display on lomotif.

Actual result: Lomotif privacy is not changing to private when user try to make lomotif as private.

Note: Lomotif privacy is not changing to public when user try to make private lomotif as public.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSDZWTmV2ZFRCdkU

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.2] on iPhone 6 Plus / 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.2] on iPhone 6S / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6s / iOS 10.1.1

**Comment by xiuie** [comment]
supposedly fixed
