### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Export - Application crashes if user closes sharing screen when video is compressing

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#117]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open one of exists lomotif
3. Tap export button on lomotif screen
4. Tap email button on sharing screen
5. Tap close button on sharing screen when video compressing 

Expected result: Back button should be disabled when video compressing

Actual result: Application crashes

Note: Reproduced with back button on sharing screen

Video: 
https://drive.google.com/file/d/0BwvEsBEA6ip4VmZZRlhJQk15YWc/view?usp=sharing

**Comment by xiuie** [comment]
Very nice bug @vysohanych 
@tsukisa I can replicate this.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@649f1c3
