### ISSUE TITLE
[2.1.3] iPhone 6S / 10.1.1 - Notifications can not be deleted - Go to notifications screen and try to delete notifications

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1171]
Frequency: Everytime

Action:
1. Launch the app
2. Login with valid credentials to lomotif app
3. Tap on Notification icon available at Right bottom corner of Home screen
4. User will be navigated to Notification screen
5. Try to delete notification from the available list of notifications
6. Check whether user is able to delete notification or not

Expected result: User should be able to delete notification from notification screen

Actual result: User is not able to delete / remove notification from notification screen

**Comment by xiuie** [comment]
@hiteshbheda You can't delete notifications from Instagram app either though.
