### ISSUE TITLE
[2.1.3] iPhone 7 / 10.2 - Irrelevant message: "Nothing here yet. Start uploading..." is displayed when there is no lomotif under "In progress" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1189]
Frequency: Every time

Precondition:
- There should be no lomotif under "In progress" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe up to reveal "Profile" screen.
3: Navigate to "In progress" tab.
4: Check if the irrelevant message: "Nothing here yet. Start uploading..." is displayed.

Expected result: Relevant message: "Nothing here yet..." should be display.

Actual result: Irrelevant message: "Nothing here yet. Start uploading..." is displayed when there is no lomotif under "In progress" tab.

Refer following screenshot for more details:
![nothing hereyet](https://cloud.githubusercontent.com/assets/24311318/21380014/2b68f7ba-c778-11e6-98db-be863ed1a7c3.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.3] on iPhone 6 Plus / 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.4] on iPhone 6s / iOS 10.1.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.4] on iPhone 6S / 10.2

**Comment by xiuie** [comment]
supposedly fixed
