### ISSUE TITLE
[1.7.3] iPhone 5S / 8.4.1 - Albums - Incorrect count of videos on albums

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#119]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Open some albums which include more than 30 videos

Expected result: User should see correct counter for each album

Actual result: User sees 30 counter on each album

![img_0538](https://cloud.githubusercontent.com/assets/3593359/13145254/12a1c412-d658-11e5-9bf7-fa709bc9a555.PNG)

**Comment by xiuie** [comment]
I can replicate. Numbers only appear awhile after you open them.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@5da9630d9b0a6efc3a81d413c3b4b4b79f6605aa
