### ISSUE TITLE
[2.1.4] iPhone 7 / 10.2 - User is able to see lomotifs of other user without login.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1195]
Frequency: Every time

Action:
1: Launch the app and without login.
2: Tap on "Follow User" icon and navigate to "Find User" screen.
3: Search for user(There should be lomotif under "Lomotifs" tab) and navigate to "Profile" screen of searched user.
4: Check if user is able to see lomotifs of searched user.

Expected result: User should not be able to see lomotifs of other user without login.

Actual result:  User is able to see lomotifs of other user without login.

**Comment by xiuie** [comment]
This is expected behavior
