### ISSUE TITLE
[2.1.4] iPhone 5S / 9.3.5 - "Eye" sign is displayed on lomotif thumbnail even when user have changed the lomotif privacy to public.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1197]
Frequency: Every time

Precondition:
- There should be some lomotif(Private) under "Lomotifs" tab.

Action:
1: Launch the app login with valid credential.
2: Swipe up to reveal "Profile" screen.
3: Navigate to "Lomotifs" tab and open one lomotif(Private).
4: Tap on  "Menu" option and select "Make Lomotif Private" option.
5: Confirm by tapping on "Yes" option and navigate to "Lomotifs" tab.
6: Check if "Eye" sign is displayed on lomotif thumbnail.

Expected result:  "Eye" sign should not be display.

Actual result:  "Eye" sign is displayed on lomotif thumbnail even when user have changed the lomotif privacy to public.

Note: 
1: Eye sign is not displayed on lomotif thumbnail even when user have changed the lomotif privacy to private.
2: "Eye" sign getting disappeared after user kill and relaunch the app.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iZmszeEJjOGgwOGs

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] for iPhone 6 Plus / 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / iOS 10.1.1

**Comment by xiuie** [comment]
supposedly fixed
