### ISSUE TITLE
[2.1.4] iPhone 6S / 10.2 - "Likes" count is decreasing when user taps on "Heart" option.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1206]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Navigate to "Lomotifs" tab and load any lomotif.
3: Like own video and navigate back to "Lomotifs" tab.
4: Turn off the internet connection and load the same lomotif.
5: Tap on "Heart" option to unlike the video.
6: Observe count is decreased by one.
7: Tap again on "Heart" icon.
8: Check if likes count is decreasing whenever use taps on "heart" option.

Expected result: "Likes" count should get decreased by one when user unlike the lomotif only if user likes own lomotif.

Actual result: "Likes" count is decreasing whenever user taps on "Heart" option.

Note: It is working as expected when user  haven't liked own lomotif.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / iOS 10.1.1

**Comment by xiuie** [comment]
Like count reverts when feed is refreshed. Bug has been logged.

**Comment by xiuie** [comment]
supposedly fixed
