### ISSUE TITLE
[2.1.4] iPhone 5S / 9.3.5 - Like is not displayed for lomotif under "Lomotifs" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1207]
Frequency: Every time

Precondition:
- There should be lomotifs under "Lomoitfs" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe right to reveal "Featured/Following" screen.
3: Tap on "Heart" sign to like own lomotif.
4: Swipe left to navigate to "Home" screen and swipe up to reveal "Profile"screen.
5: Navigate to "Lomotifs" tab and load recently liked lomotif.
6: Check if the like is displayed.

Expected result: Like should be display..

Actual result: Like is not displayed for lomotif under "Lomotifs" tab.

Note: Like is displayed for lomotif when user kill and relaunch the app.

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / 10.2.

**Comment by xiuie** [comment]
supposedly fixed
