### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Albums/Facebook - Facebook does not support to select photos from Albums

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#121]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll tab on Albums screen
4. Click on Facebook

Expected result: Facebook Photos and Videos should be available from Facebook

Actual result: Facebook not supported by Lomotif app, Displays error

![img_0678](https://cloud.githubusercontent.com/assets/9691390/13148011/72494bf0-d681-11e5-9235-60a1632b1bb0.PNG)

**Comment by xiuie** [comment]
@benchang Is this a bug or I assume it's just because testers don't have access to Facebook? Any way to give them access?

**Comment by benchang** [comment]
testers don't have access to Facebook, we would have to individually add them (a byproduct of pushing the dev build)
