### ISSUE TITLE
[2.1.4] iPhone 6S / 10.1.1 - Wrong Lomotif count - Search for user -> Go to profile -> On Lomotif tab count and exact lomotifs are different

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1213]
Frequency: Everytime

Action:
1. Launch the app
2. Login to Lomotif app with valid credentials 
3. Click on User search icon
4. Search for any user (Searched user should have some lomotifs available in "Lomotifs" tab)
5. Tap on user to go to profile page of searched user
6. Go to "Lomotifs" tab of searched user account
7. Observe and count available number of lomotifs in "Lomotifs" tab
8. Check whether lomotif count is same as available lomotifs

Expected result: Exact lomotif count should be displayed on user profile (count shoud be according to available number of lomotif)

Actual result: Lomotif count and lomotif displayed number are different

![1](https://cloud.githubusercontent.com/assets/9691390/21424761/d8d650b2-c86a-11e6-9fef-52e9e3eea793.PNG)

**Comment by testershub** [comment]
@xiuie Similar to #1139

**Comment by hiteshbheda** [comment]
@testershub It's not similar to #1139,

In #1139, we are checking Lomotif count for logged in user. While in this issue, we are searching for user and also in this issue Lomotif count is wrong, it's not 0. It was always 0 in #1139

**Comment by testershub** [comment]
@xiuie #1213 is similar to #1139 as, Lomotif count of uploaded lomotif is same for both "Searched User (Own profile)" and user's profile screen.

Issue is reproducible for build [2.1.4] by following scenario:

Precondition: User should have logged in with account [Which is created in previous build (Old build)] and there should be at least one uploaded lomotif.

1: Launch the app.
2: Navigate to "Lomotifs" tab and observe the uploaded lomotif and lomotif count (Count will be zero for uploaded lomotif)
3: Now search for same user and check zero lommotif count is displayed. 
4: Now, create a lomotif and upload the same.
5: Check lomotif count and number of uploaded lomotifs under "Lomotifs" tab. (wrong count will be displayed)
6: Now search for the same user again and check the count (Count is displayed same as in step-5)

Issue is specifically observed for account which is created for older version. It is working as expected for account created for latest build.

**Comment by xiuie** [comment]
Resolved on server
