### ISSUE TITLE
[2.1.4] iPhone 6S / 10.1.1 - "Following" count does not update - Click on "Following" and unfollow any user from list

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1216]
Frequency: Everytime

Action:
1. Launch the app
2. Login with valid credentials to lomotif app
3. Click on "Follow User" icon on top of the screen
4. Search for any existing user on Find User screen
5. List of users will be displayed
6. Tap on any user from the list
7. Go to selected user's profile page
8. Observe the available count of "Following" on selected user profile page
9. Click on Following option from profile page
10. From "Following" list, unfollow any user
11. Go back to profile page by clicking on Back button
12. Now, observe whether "Following" list has been updated or not

Expected result: When application logged in user unfollow other user from the search list, then at same time "Following" count should be decreased (updated)

Actual result: Even though user is unfollowing other user, "Following" count does not update / decrease

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / 10.2

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.12] on iPhone 5S / 9.3.5

**Comment by xiuie** [comment]
supposedly fixed
