### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Application crashes - During export created lomotif on Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#122]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll tab on Albums screen
4. Select photos from Camera Roll
5. Select audio from Find Music or My Music
6. Tap on "OK" button to create lomotif
7. Click on Export button
8. Select Facebook to share created lomotif
9. Click on "Okay" button 

Expected result: Created lomotif should be share or should take to home screen

Actual result: Application crashes

**Comment by xiuie** [comment]
Can't replicate. My video is successfully shared. Is this due to permissions @benchang or should I get other testers to see if it happens to them?

**Comment by benchang** [comment]
I can't seem to replicate this either so I'm closing it, @pmtheint if you can try replicating and it crashes please reopen this
