### ISSUE TITLE
[2.1.4] iPhone 6S / 10.1.1 - Login button does not enable - On Login page, first insert password and then username / email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#1229]
Frequency: Every time

Pre-requisite: User should be logged out from lomotif app

Action:
1. Launch the app
2. Swipe Home screen upwards (or click on user icon at centre bottom of the screen)
3. Tap on Sign up / Log in button
4. Click on Sign in option
5. Now, enter password first in password field and then username / Email in username /email field
6. Check whether Log In button is enabled or not

Expected result: Login button should be enabled when user first enter password and then username / email

Actual result: Log in button is disabled

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6 Plus / 10.1.1.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.11] on iPhone 6S / 10.2

**Comment by xiuie** [comment]
supposedly fixed
