### ISSUE TITLE
[2.1.4] iPhone 6 Plus / 10.1.1 - Irrelevant like (Heart) is displayed when user double tap on "Featured" lomotifs.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1243]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Navigate to "Featured" lomotif.
3: Double tap on any lomotif under "Featured" tab.
4: Check if irrelevant  like (heart) is displayed.

Expected result: Irrelevant like (Heart) should not be displayed when user double tap on "Featured" lomotifs as there is no any option to like the "Featured" lomotifs.

Actual result: Irrelevant like (Heart) is displayed when user double tap on "Featured" lomotifs.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / 10.2

**Comment by xiuie** [comment]
@testershub @Pankaj-Testershub This is expected behavior. Similar to Instagram, double tap action "lkes" a post.
