### ISSUE TITLE
[2.1.4] iPad Mini 3 / 9.3.4 - Deleted assets are displayed in the uploaded lomotif preview.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1244]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and select few images from "Camera" folder and few motifs.
3: Add/ skip the music and proceed to "Create" screen.
4: Navigate to device storage and delete all added images from "Camera" folder.
5: Observe deleted assets are displayed on "Create" screen.
6: Tap on "Export >> Make Lomotif" button.
7: Navigate to "Lomotifs" tab and wait till uploading completes.
8: Load the recently uploaded lomotif.
9: Check if deleted assets are displayed in preview.

Expected result: Deleted assets should not be displayed in uploaded lomotif preview because user deletes the assets before exporting the lomotif.

Actual result: 
1: Deleted assets are displayed in the uploaded lomotif preview.
2: Deleted assets are not displayed when user load the same lomotif under "In Progress" tab.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.4] on iPhone 6S / 10.2

**Comment by xiuie** [comment]
@testershub @Pankaj-Testershub This is the ideal behavior. The images are probably stored in the cache.
