### ISSUE TITLE
[1.7.3] iPad mini 2 / 9.2 - Create - New changes are saved when user doesn't confirm their

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#125]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open one of exists lomotif
3. Enable Stickers field
4. Add any sticker
5. Tap home button
6. Tap NO button on 'Would you like to save your changes?' dialog
7. Open the same lomotif

Expected result: User sould see lomotif without stiker

Actual result: User can see lomotif with stiker

**Comment by xiuie** [comment]
I can replicate

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@e56c83cfdc
