### ISSUE TITLE
[1.7.3] iPad mini 2 / 9.2 - Create - Application crashes when user taps home button on Create screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#126]
Frequency: Once

Action:
1. Launch Lomotif
2. Open one of exists lomotif
3. Play the lomotif
4. Tap home button on Create screen

Expected result: User sould see home screen

Actual result: Application crashes

**Comment by xiuie** [comment]
I cannot replicate this.

**Comment by benchang** [comment]
Can't replicate, closing
