### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Application Crash - While creating lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#127]
Frequency: Once

Action:
1. Launch Lomotif
2. Tap on START button
3. Select "Happy Birthday" from Motif
4. Select first 6 videos
5. Click on Camera Roll tab
6. Select any photos from Camera roll
7. Click on OK
8. Tap on My Music
9. Select any audio from My Music
10. Click on Home button
11. Click on "YES" to confirm

Expected result: Lomotif should be saved and redirect to home screen

Actual result: Application crashes

**Comment by xiuie** [comment]
I can replicate! This crash bug happened to me the first time I did it too @benchang . However, can't replicate it after that. How should we handle this?

**Comment by benchang** [comment]
I can't seem to replicate this at all, am inclined to close this issue: @xiuie if you can come up with a set of steps to replicate, please reopen
