### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Without any change, Audio changes - During attempting audio change in created lomotif and not saving lomotif, automatically change audio

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#128]
Frequency: Every time

Action:
1. Launch Lomotif
2. Select and open any created lomotif
3. Click on change audio button
4. Select any song/audio from My Music tab
5. Click on Home button
6. Select NO from "Would you like to save your changes?" window

Expected result: In existing Lomotif, audio should not be changed

Actual result: Audio changed in saved lomotif even if we have not saved opened lomotif

**Comment by xiuie** [comment]
I can replicate.

**Comment by tsukisa** [comment]
duplicate of #125
