### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Import Instagram - Can’t Preview and Crash

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#129]
Frequency: Every time

Action:
1. Launch Lomotif
2. In My Videos, select Instagram folder
3. Select clips (The images will not load even after minutes)
4. Select any song/audio 
5. On the Create screen, tap on thumbnail
6. App crash

Expected result: Instagram clips eventually load

Actual result: App crash

**Comment by hiteshbheda** [comment]
I can replicate this..!

**Comment by xiuie** [comment]
Thanks @hiteshbheda :)

**Comment by tsukisa** [comment]
crash issue has been resolved with commit Lomotif/lomotif-ios@f8cb2b9

**Comment by tsukisa** [comment]
@xiuie preview doesn't play the first time, I will create a separate issue for that.
