### ISSUE TITLE
[1.6.5] Minor UI bug when a clip (one that has been resized) is duplicated. 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#13]
How to replicate:
1. Select video clips
2. Select music
3. Resize video clip
4. Duplicate the resized video clip
5. This preview will be mostly black (clip is inaccurately displayed)

**Comment by tsukisa** [comment]
I need the details of following:
1. Aspect ratio
2. Zoom in / zoom out?

**Comment by tsukisa** [comment]
Probably fixed with commit at Lomotif/lomotif-ios@c25da24e6850ee9babd0f3eeb32d558967962791

**Comment by tsukisa** [comment]
@xiuie Bug will be considered fixed if no confirmation is received.

**Comment by xiuie** [comment]
@tsukisa Looks like this is fixed.
