### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Motifs - All Motifs appear black in Saved Projects after awhile (e.g. 24hours +)

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#131]
Frequency: Every time

Action:
1. Launch Lomotif
2. In My Videos, use Motifs
3. Hit home and save project
4. Launch Lomotif 12-36 hours later
5. All Motifs appear black (camera clips work)
6. Export
7. Error -11841

Expected result: Motifs load in project

Actual result: Error -11841

![slack for ios upload-3](https://cloud.githubusercontent.com/assets/16533289/13166060/9142ae2a-d6fe-11e5-828f-6ed43ca2462f.jpg)

![slack for ios upload png-2](https://cloud.githubusercontent.com/assets/16533289/13166075/ad289492-d6fe-11e5-8340-64fdb5d4215d.jpeg)

**Comment by xiuie** [comment]
@benchang Can help to replicate? Or find someone in the office who have saved Motifs yesterday?

**Comment by benchang** [comment]
I can reproduce, motifs do not load

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@8926c8c
