### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Facebook - Can’t preview videos

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#132]
Frequency: Every time

Action:
1. Launch Lomotif
2. In My Videos, select Facebook folder
3. Tap to preview video
4. Video does not preview

Expected result: See a preview of clip

Actual result: Clip does not play

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@bdc24ba
