### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - App Crash - While changing audio from My Music to Find music and then save lomotif by clicking on Home Button

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#133]
Frequency: Once / Twice

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Select multiple videos from slow mo in motif
5. Go to My Music tab 
6. Select any audio from My Music tab
7. Now, change audio from My Music to selecting any audio from Find Music tab
8. Slightly forward this audio song by dragging audio waves
9. Click on Home Button
10. Select "YES" from "Would you like to save your changes?" tab

Expected result: Created lomotif should be saved to Home screen

Actual result: Error - Application crashes

**Comment by xiuie** [comment]
I can replicate this about 25% of the time. @tsukisa I can try to do so when hooked up to Xcode.

**Comment by hiteshbheda** [comment]
I can also replicate it just now @xiuie

**Comment by tsukisa** [comment]
possible relevant to #227
