### ISSUE TITLE
[1.7.3] iPhone 6 / 9.2.1 - Network Error in Selecting Motifs without Internet - Without Internet, when selecting multiple motifs from Nicki Minaj, gives network error to few videos while doesn't give to remaining

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#134]
Frequency: Every time

Action:
1. Off Internet
2. Launch Lomotif
3. Tap on START button
3. Select Motif tab on Albums screen
4. Select "nicki minaj" tab from motif
5. Select vidoes one by one from "nicki minaj"

Expected result: Either all videos should be selected or no video should be selected from "nicki minaj", If gives error then provide to all videos or if not then do not provide to anyone

Actual result: Gives network error in some videos and some videos are selected without error

![img_0718](https://cloud.githubusercontent.com/assets/9691390/13171635/dd1614f2-d719-11e5-8163-1b3e2d06c981.PNG)

![img_0719](https://cloud.githubusercontent.com/assets/9691390/13171637/dd3a5e8e-d719-11e5-91c2-54e81a1037ca.PNG)

**Comment by tsukisa** [comment]
The error will only show if the clip is not cached on device yet. If the clip is already downloaded you won't see the message.
@xiuie please advice if you need to change the message.
