### ISSUE TITLE
[1.7.4] iPhone 6 / 9.2.1 - Import Instagram - App crash when you tap on thumbnail

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#135]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Instagram folder
4. Select Instagram photos and videos
5. On Create screen, while preview is still loading, tap on thumbnail
6. App crash

Expected result: Thumbnail is selected

Actual result: App crash

**Comment by hiteshbheda** [comment]
I can replicate this @xiuie

**Comment by Dipamit** [comment]
I am not able to replicate this issue with above mentioned steps. Tested with iPhone 6 iOS 9.2

**Comment by tsukisa** [comment]
@xiuie issue has been resolved. If you still having the issue, it's probably the file loaded from cache. Go to settings and tap the version number 10 times to clear the cache then try again.
