### ISSUE TITLE
[1.7.4] iPhone 6 / 9.2.1 - Repeat songs - When scroll down in Find music, repeat songs unlimited times

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#136]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any motifs from Motif tab
4. Tap on Find Music tab
5. Scroll down for more audio songs

Expected result: List of audio songs should be end at last song

Actual result: Unlimited songs display, Repeat songs

**Comment by Dipamit** [comment]
I am able to replicate this issue. Every user expecting that list will end at last but in all pages we are scrolling and when it ends, it starts again from first below it. So it is never ending. This can be working as design.

**Comment by tsukisa** [comment]
@xiuie Issue can't be replicated. I guess the issue has been resolved on server side (each pagination call returns same url)
