### ISSUE TITLE
[2.1.8] iPhone 5S / 9.3.5 - User is not navigated to "Following" tab after tapping on "Show me my Lomotif!" button.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1362]
Frequency: Every time

Action:
1: Launch the app and login with valid credential.
2: Tap on "Follow user" icon and navigate to "Friends on Lomotif" screen.
3: Search for own "Profile" and navigate to "In progress" tab.
4: Load one lomotif and navigate to "Create" screen.
5: Tap on export option and export the lomotif.
6: After exporting completed user will be navigated to "Share your Lomotif" screen.
7: Tap on "Show me my Lomotif!" button.
8: Check if user is navigated to "Following" tab.

Expected result: User should be navigate to "Following" tab.

Actual result: User is not navigated to "Following" tab after tapping on "Show me my Lomotif!" button.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSFpCRExDTVo0eG8

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.8] on iPhone 6 Plus / 10.1.1.
User is navigated to "In Progress" tab instead of "Following" tab.

**Comment by tsukisa** [comment]
fixed
