### ISSUE TITLE
[1.7.4] iPhone 6 / 9.2.1 - Search tab in Find Music not working properly - When searching more than 1 word in search tab in Find Music, it does not work

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#137]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any motifs from Motif tab
4. Tap on Find Music tab
5. Tap on search tab
6. In Search tab, type "Hip", it will show 5 results
7. Now, in search tab, type "Hip Hop", it should display 5 results

Expected result: 5 songs including "Hip Hop" words should be displayed

Actual result: No results display

![img_0722](https://cloud.githubusercontent.com/assets/9691390/13182972/8455c39e-d75a-11e5-9bd5-830e746a0688.PNG)

![img_0723](https://cloud.githubusercontent.com/assets/9691390/13182973/845bc9ba-d75a-11e5-9594-634025702f3e.PNG)

**Comment by xiuie** [comment]
@ruiwen Anything to be concerned about? Suspect this is just a dev build thing. If so, please close.

**Comment by Dipamit** [comment]
I can able to replicate this issue. We can search using single word only. If we try to search using more than 1 word it will not showing result. Another thing I want to add here is, when we remove value it should show default value back.

**Comment by benchang** [comment]
yep this should just be a dev build thing

**Comment by ruiwen** [comment]
Separate technical issue logged ^^

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@8b5cd0c
