### ISSUE TITLE
[2.1.9] iPhone 7 / 10.2 - Irrelevant text "null" is displayed for comment notifications.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1370]
Frequency: Everytime.

Precondition: User must have some received comment notifications 
Action: 
1: Launch the app and login with valid credentials.
2: Tap on "Notification" icon
3: Check if irrelevant text "null" is displayed for comment notifications.

Expected result: 
1: Irrelevant text "null" should not display for comment notifications.
2: "Comment" should displayed instead of "Null" text.

Actual result:  Irrelevant text "null" is displayed for comment notifications.

Please refer screenshot for more details:
![15](https://cloud.githubusercontent.com/assets/24449093/21805778/f7c5c7d2-d75b-11e6-836c-9c128ae5633e.jpg)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.9] on iPhone 6 Plus / 10.1.1.

**Comment by tsukisa** [comment]
fixed
