### ISSUE TITLE
[1.7.4] iPhone 5/8.3- Application Launch- Application is crash while launch

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#138]
Frequency: Every time.

Action:
1. Install the application at very first time.
2. Launch the application.
3. Wait for few mins and check the page. 

Expected Result: Application does not crash.

Actual Result: Application is crash at very first time. I need to launch 3-4 times to get first page. To reproduce it again. I closed the application and again launch application. Then again got crash.

[Crash Video and Logs.zip](https://github.com/Lomotif/lomotif-ios-issues/files/138568/Crash.Video.and.Logs.zip)

**Comment by Dipamit** [comment]
Help wanted from my side?

**Comment by benchang** [comment]
@Dipamit did you install through fabric/crashlytics?

**Comment by Dipamit** [comment]
@benchang I installed it though crashlytics.

**Comment by tsukisa** [comment]
@xiuie unable to replicate
