### ISSUE TITLE
[2.1.9] iPhone 5S / 10.2 - Application is crashing when user taps on "Show me my Lomotif" button.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1383]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Navigate to "Feed >> Following" tab.
3: Tap on "Comment" option.
4: Swipe the screen right to left to reveal home screen.
5: Tap on "START" and create a lomotif with few motifs with / without music.
6: Tap on "Export >> Make Lomotif" button.
7: Tap on "Show me my Lomotif" button.
8: Tap on "YES" option on pop up message.
9: Check if application is crashing.

Expected result: Application should not crash when user taps on "Show me my Lomotif" button.

Actual result: Application is crashing when user taps on "Show me my Lomotif" button.

Note: Similar issue os observed when user navigate to home screen from likes screen and create lomotif.

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwUDhhSmFzdU1tMWs

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.9] on iPhone 7 / 10.2

**Comment by Aboli-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.11] on iPhone 7 / 10.2

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.12] on iPhone 7 / 10.2.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.16] on iPhone 7 / 10.2

**Comment by xiuie** [comment]
Verified fixed
