### ISSUE TITLE
[2.1.9] iPhone 7 / 10.2 - Application is crashing when user try to cancel sharing and navigate to "Following" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1386]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Navigate to "Feed >> Following" tab.
3: Select own lomotif and tap on own "Username".
4: User will be navigated to own "Profile" screen.
5: Loading any existing lomotif project under "In Progress" tab.
6: Tap on "Export >> Make Lomotif" option.
7: Tap on "Show me my Lomotif" option and confirm by tapping on "Yes" option.
8: Check if application is crashing.

Expected result: Application should not crash when user try to cancel sharing.

Actual result: Application is crashing when user try to cancel sharing and navigate to "Following" tab.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3icDBuc1MtdnQtWHM

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.9] on iPhone 5S / 10.2.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [2.1.12] on iPhone 6 Plus / 10.1.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.16] on iPhone 7 / 10.2

**Comment by xiuie** [comment]
Verified fixed
