### ISSUE TITLE
[1.7.4] iPhone 5/8.3- Motif tab- My Camera roll data displayed under Motif tab.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#139]
Frequency: Always

Action:
1. Launch the application. 
2. Tap on "Start" button.
3. Check that you can see two tab, Camera Roll and Motif.
4. Check the content displayed under both tabs.
5. Tap on Motif tab and then choose any video from list.
6. Tap on True sign from top right.
7. Tap on back button displayed on top from Find Music page.
8. Check selected tab and content

Expected Result: It should highlight Camera Roll tab as it showing Camera Roll data.

Actual Result: It showing Motif tab highlighted but data for Camera roll.
[Tab Highlight problem.zip](https://github.com/Lomotif/lomotif-ios-issues/files/138594/Tab.Highlight.problem.zip)

**Comment by xiuie** [comment]
I can replicate @tsukisa on 1.7.5. But selecting "Camera Roll" and "Motifs" again fixes the issue, so for now it's a "Low bug"

**Comment by tsukisa** [comment]
issue has been fixed
