### ISSUE TITLE
[2.1.10] iPhone 7 / 10.2 - User does not navigate to "Profile" screen when tap on "User Profile" icon.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1390]
Frequency: Everytime.

Action: 
1: Launch the app and login with valid credential.
2: Tap on "User Profile" icon.
3: Navigate to "Lomotif" tab and tap on any lomotif.
4: Tap on "Feed" icon and tap on "Home" button on "Featured>Following" screen.
5: Tap on "User Profile" icon.
6: Check if user is not navigating to own profile screen.

Expected result: User should navigate to "Profile" screen when tap on "User Profile" icon.

Actual result: User does not navigate to "Profile" screen when tap on "User Profile" icon.

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build[2.1.10] on iPhone 5S / 10.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.11] on iPhone 6S / 10.2
