### ISSUE TITLE
[1.6.5] Serious UI bug: In Landscape view, preview can shift almost entirely off screen

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#14]
How to replicate:
1. Select vidoe clips
2. Select music
3. Resize image in one clip
3. Hit "Lomotif - 30secs"
4. Swipe up on the screen
5. The preview moves off screen

**Comment by tsukisa** [comment]
unable to replicate

**Comment by tsukisa** [comment]
Probably fixed with commit at Lomotif/lomotif-ios@280fc3d9436ef01909da7a51835a7da00fc37302

**Comment by tsukisa** [comment]
@xiuie Bug will be considered fixed if no confirmation is received.

**Comment by xiuie** [comment]
@tsukisa Looks like this is fixed too.
