### ISSUE TITLE
[1.7.4] iPhone 5/8.3- My Music- Menu is not expanded.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#140]
Frequency: Every Time

Action:
1. Launch the application.
2. Tap on "Start" and choose any video.
3. Tap on True sign from top.
4. From Find Music page tap on "My Music" tab.
5. Tap on Menu 3-4 times.
6. Tap on Menu and choose Songs.
7. Again try to tap on menu.

Expected Result: Menu should be expanded.

Actual Result: Menu is not expanded.
[Menu icon for my music.zip](https://github.com/Lomotif/lomotif-ios-issues/files/139001/Menu.icon.for.my.music.zip)

**Comment by xiuie** [comment]
I can replicate this @tsukisa

**Comment by hiteshbheda** [comment]
I can replicate the same @Dipamit

**Comment by tsukisa** [comment]
issue has been resolved
