### ISSUE TITLE
[2.1.10] iPhone 6 Plus / 10.1.1 - Comment count is not getting updated on "Lomotif preview" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#1400]
Frequency: Every time

Precondition:
- There should be some lomotf under "Lomotifs" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe right to reveal "Featured/Following" screen and navigate to "Following" tab.
3: On own lomotifs, tap on "Comment" option and enter one comment.
4: Navigate back to "Following" tab and swipe left and navigate to "Home" screen.
5: Swipe up to reveal "Profile" screen and navigate to "Lomotifs" tab.
6: Open the same lomotif and navigate to "Comments" screen.
7: Observe recently entered comment is displayed, navigate back to "Lomotif preview" screen.
8: Check if comment count is getting updated or not.

Expected result: Comment count should get update on "Lomotif preview" screen.

Actual result: Comment count is not getting updated on "Lomotif preview" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iUjlDaTRsWE9UcWc

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.10] on iPhone 7 / 10.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.15] on iPhone 6 Plus/ 10.1.1
One more thing we observed, comment count is not getting updated on "Lomotif preview" screen when the user navigates to "Lomotif preview" screen from "Following" tab, But after navigating back to "Lomotif preview" from "Comments" screen count gets updated.

**Comment by xiuie** [comment]
supposedly fixed
