### ISSUE TITLE
[2.1.10] iPhone 6  Plus / 10.1.1 - User is not able to like the lomotif after double tapping on lomotif.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1402]
Frequency: Random

Precondition"
- There should be some lomotifs under "Lomotifs" tab.

Action:
1: Launch the app and login with valid credential.
2: Swipe up to reveal "Profile"  screen and navigate to "Lomotifs" tab.
3: Open one lomotif and navigate to "Lomotif preview" screen.
4: Double tap on lomotif to like the lomotif.
5: Check if user is able to like the lomotif.

Expected result: User should able to like the lomotif after double tapping on lomotif.

Actual result: 
1: User is not able to like the lomotif after double tapping on lomotif.
2: Like effect is displayed after double tapping on lomotif.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iNDYzbEhDd3J5UXM

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build  [ 2.1.10] / iPhone 7 / 10.2

**Comment by xiuie** [comment]
Double tapping = like

This is the behavior of Instagram. Works as designed and please take note for future reference
