### ISSUE TITLE
[ 2.1.11] on iPhone 6 Plus / 10.1.1 - User does not navigating to "Lomotif Preview" screen when tap on "Lomotif" thumbnail on "Notification" screen.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1411]
Frequency: Everytime.

Precondition:- User should have some like/comment notifications under "Notifications" screen.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Notification" bell icon.
3: Tap on "Lomotif" thumbnail on "Notifications" screen.
4: Check if user able to navigate to "Lomotif" preview screen or not.

Expected result:- User should navigate "Lomotif Preview" screen when tap on "Lomotif" thumbnail on "Notification" screen.

Actual result: User does not navigating to "Lomotif Preview" screen when tap on "Lomotif" thumbnail on "Notification" screen.

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.11] on iPhone 7 / 10.2

**Comment by xiuie** [comment]
This feature will be introduced soon
