### ISSUE TITLE
[1.7.4] iPhone 5/8.3- Export- Allows to me to go back when file compressing for export.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#142]
Frequency: Every Time

Action:
1. Launch the application.
2. Choose any video and then go next.
3. Choose any music and go next. 
4. Tap on Export icon from top.
5. Choose FB messenger and then check that it started compressing video.
6. Tap on Back from top.

Expected Result: It should not allows to go back while compression going on.

Actual Result: It allows to me go back while compressing process going on. Same issue also while you download any file from Fine Music.

**Comment by xiuie** [comment]
Not sure if this is ok, or we need a confirmation dialogue box @pmtheint

**Comment by pmtheint** [comment]
The compression duration is very short anyway. Safe to disable any interaction while compressing. Will  log this on Asana as UI amendment.

**Comment by pmtheint** [comment]
Moved to Asana.
