### ISSUE TITLE
[2.1.12] iPhone 5S / 9.3.5 - Black frame is displayed at preview when user create lomotif with few motifs from beach category.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1421]
Frequency: Every time

Action:
1: Launch the app with/without.
2: Tap on "START".
3: Tap on "motif" tab.
4: Select few motifs from beach category (which are highlighted in screenshot).
5: Create lomotif with/without music.
6: Check if black frame is displayed at preview or not.

Excepted Result: Black frame should not be displayed at preview when user create lomotif with few motifs from beach category.

Actual Result: Black frame is displayed at preview when user create lomotif with few motifs from beach category.

Refer following video link for more details:
https://drive.google.com/open?id=0B2TfWRODMVhYX0tPYjN0YWFoMFk

Refer following screenshot for more details:
![1421](https://cloud.githubusercontent.com/assets/25073306/22369854/5f04f49e-e4b4-11e6-9d29-3bffd95309ba.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.12] on iPhone 6 Plus / 10.1.1

**Comment by xiuie** [comment]
This has to do with the clips in question. I will close it for now, but let me know if you can reproduce this for more than 5% from those "searched" motifs.
