### ISSUE TITLE
[2.1.12] iPhone 7 / 10.2 - User is able to like the lomotif other than highlighted on "Following" tab.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1423]
Frequency: Every time

Action:
1: Launch the app and login with valid credential.
2: Swipe right to reveal "Featured/Following" screen and navigate to "Following" tab.
3: Select one lomotif to play(Observe selected lomotif is displayed as highlighted.)
4: Double tap on lomotif above or below the highlighted lomotif.
5: Check if user is able to like the lomotif other than highlighted.

Expected result:  User should not be able to like the lomotif other than highlighted on "Following" tab.

Actual result:  User is able to like the lomotif other than highlighted on "Following" tab.

Note: User is able to navigate to "Likes" and "Comments" screen of lomotif other than highlighted. 

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iUmRXNGpCMV9oVUk

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.12] on iPhone 6 Plus / 10.1.1

**Comment by xiuie** [comment]
Will not fix for now. Designer says we can allow this and also, we will be changing preview experience soon.

**Comment by Pankaj-Testershub** [comment]
@xiuie Ok Noted. Thanks.
