### ISSUE TITLE
[2.1.14] iPhone 7 / 10.2 - User is displayed as logged-in even when user has logout from the app.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1440]
Frequency: Every time

Precondition:
- There should be some own likes/comments notification under "Notification" screen.
- There should be some lomotif under "In progress" tab.

Action:
1: Launch the app and login with a valid credential.
2: Swipe left to reveal "Notification" screen and tap on own "Username"(User will be navigated to own profile screen).
3: Navigate to "In progress" tab and load one lomotif(User will be navigated to create screen).
4: Tap on the export option and export the lomotif, after lomotif exported skip sharing and navigate to "Home" screen.
5: Log out from the app and navigate to "Notification" screen.
6: Check if the user is displayed as logged-in or not.

Expected result: User should not display as logged-in even when the user has logged out from the app.

Actual result: User is displayed as logged-in even when the user has logged out from the app.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSng0X1RNQU5WdW8

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.14] on iPhone 5S / 10.2

**Comment by xiuie** [comment]
supposedly fixed
