### ISSUE TITLE
[2.1.14] iPhone 6S / 10.2 - User is not able to Sign up "Error- Error unknown" is displayed on "Username" screen. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1445]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "User" icon.
3: Tap on "Sign up/Log in" button.
4: Enter all valid details and tap on "Sign up" button.
5: Navigate to "Username" screen and tap on "Let's go" button.
6: Check if "Error - Error unknown" is displayed while user is trying to signup.

Expected result: User should be able to Sign up "Error - Error unknown" should not be displayed on "Username" screen.

Actual result: User is not able to Sign up "Error- Error unknown" is displayed on "Username" screen. 

**Note: This issue is specifically observed for "10.2" OS.**

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudenlUd1R3b1E1N3M

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.14] on iPhone 5 S / 10.2

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.14] on iPhone 7 / 10.2
It is working as expected now.
