### ISSUE TITLE
[2.1.14] iPhone 6 Plus / 10.1.1 -  User is not able to view the profile picture of other users.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1453]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "Follow user" icon and navigate to "Friends on Lomotif" screen.
3: Search for any user and navigate to searched user "Profile" screen.
4: Tap on "Profile picture" icon of searched user.
5: Check if the user is able to view the profile picture of searched user or not.

Expected result: User should be able to view the profile picture of other users.

Actual result: User is not able to view the profile picture of other users.

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.14] on iPhone 6s / 10.2.1.
