### ISSUE TITLE
[1.7.5] iPhone 6/9.2.1 - Change Music - Can’t cancel selection

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#146]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video
4. Select any song
5. In Create screen, tap “Change Music"
6. Select “Use Music"
7. Hit “X” before the song loads
8. Returns to Create screen, the music changes to new song after awhile (e.g. 3-4 secs)

Expected:
Tapping “X” will cancel Song Selection

Actual:
Tapping “X” returns to Create screen, but song continues to load in the background and is added to project upon loading

**Comment by pmtheint** [comment]
Moved to Asana
