### ISSUE TITLE
[2.1.14] iPhone 6 Plus / 10.1.1 - "Lomotif reported as [spam]. we will review it shortly." pop up is not displayed in proper format on "Following" tab.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1465]
Frequency: Every time

Precondition: There should at least one lomotif of the following user under the "Following" tab.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Feed>>Following" tab.
3: Tap on "..." dots on other user's lomotif.
4: Tap "Report" option and select "Spam/Inappropriate/Others" options.
5: Check if "Lomotif reported as [spam]. we will review it shortly." pop up is displayed in proper format or not. 

Expected result: "Lomotif reported as [spam]. we will review it shortly." pop up should displayed in proper format as "Lomotif reported as Spam. we will review it shortly."  on "Following" tab.

Actual result: "Lomotif reported as [spam]. we will review it shortly." pop up is not displayed in proper format on "Following" tab.

Note:
**1: Similar issue is observed for "Live Build - [2.1.6]".**
2: Similar is observed when user search for other user and report lomotif under "Lomotif Preview" screen.

Please refer attached screenshot for more details:
![1](https://cloud.githubusercontent.com/assets/24449093/22916734/40417b54-f2a6-11e6-9153-f46aeecc2961.jpg)

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.14] on iPhone 7 / 10.2

**Comment by xiuie** [comment]
Fixed. Please check that the changes are made in the next build.

**Comment by Aboli-Testershub** [comment]
@xiuie, Ok Noted.
Thanks!
