### ISSUE TITLE
[1.7.5] iPhone 6/9.2.1 - Share to Messenger - Crash bug

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#147]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video
4. Select any song
5. In Create screen, tap export
6. In Share screen, select Messenger
7. Crash when in Messenger

Expected:
Share to Messenger

Actual:
Crash

**Comment by tsukisa** [comment]
@xiuie unable to reproduce

**Comment by tsukisa** [comment]
found the problem exists only in build running in live environment
