### ISSUE TITLE
[2.1.14] iPhone 5S / 9.3.5 - Another app is getting opened when user try to log in with the Facebook app and Facebook app is not installed on the device.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1471]
Frequency: Every time

Precondition:
1: The user should be logged out from Lomotif app and from the facebook account on the browser..
2: Facebook account should be unlink and Facebook app should not be installed.

Action:
1: Launch the app(Without login).
2: Tap on "User" icon.
3: Tap on "Sign up/Log in" button.
4: Navigate to "Sign up" screen.
5: Tap on "Connect with Facebook" button.
6: Observed there will two option login by facebook app and login with browser.
7: Tap on "Log in with the Facebook App" button.
8: Check if is showing another app to be opened.

Expected result: 
1: It should show relevant message as "Please install faceboook app".
2: Another app should not be opened when user try to login with facebook app and Facebook app is not installed.

Actual result: Another app is getting opened when user try to log in with the Facebook app and Facebook app is not installed on the device.

**Note: This issue is specifically observed for "iPhone 5S / 9.3.5".**

Please refer video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudZlB0VXUyTHVHcFk

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.14] on iPhone 7 / 10.2

**Comment by tsukisa** [comment]
It's Facebook SDK issue, we have no control over it.
