### ISSUE TITLE
[1.7.5] iPhone 6/9.2.1 - Title - Alignment

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#149]
Frequency: All the time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any clip
4. Select any song
5. In Create screen, turn on title
6. Fill title with the sentence: The quick brown fox jumped over the lazy dogs x 5-10

Change to Lomotif format
Expected:
You can read the first part of the words, OR there’s an error when you exceed the limit

Actual:
You can read the last part of the words (see screenshot)

![slack for ios upload-2](https://cloud.githubusercontent.com/assets/16533289/13246922/93325662-da51-11e5-8b5c-01048e6098b8.jpg)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.5 on iPad 2 iOS 9.3.1
