### ISSUE TITLE
[Live Build (2.1.6)] iPhone 6 plus / 10.1.1 - "Sticker" is not displayed when user tap on particular sticker on"Create" screen. 

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1498]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and navigate to "Add Photos & Videos" screen.
3: Select any assets.
4: Create lomotif with/without music.
5: Tap on "Sticker" (Highlighted in attached screenshot).
6: Check if sticker is displayed on "Create" screen or not.

Expected result: "Sticker" should be display when user tap on particular sticker on"Create" screen. 

Actual result: "Sticker" is not display when user tap on particular sticker on"Create" screen. 

Refer following screenshot for more details:

![1498](https://cloud.githubusercontent.com/assets/25073306/23114532/86587674-f765-11e6-8a4d-6174c20e18d6.jpg)

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for Live_Build [2.1.6] on iPhone 7 / 10.2

**Comment by xiuie** [comment]
We will remove this sticker. Please check that this sticker has been removed on Android/iOS within 24 hours.. (May be cached for awhile)

**Comment by Aishwarya-Testershub** [comment]
@xiuie OK,Noted.

**Comment by Aishwarya-Testershub** [comment]
@xiuie This sticker has been removed on both Android and iOS.
