### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - App Crash - While exporting created lomotif using Export tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#152]
Frequency: Twice / Thrice

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Select multiple (4 -5) videos from slow mo in motif
5. Go to Find Music tab 
6. Select "Indian Summer" song from Find Music tab
7. Now, click on Stickers tab, make it ON and OFF again
8. Select Filters tab, Make it ON and then OFF again
9. Select Enter a Title, Make it ON and OFF again
10. Now, Click on Export button (top right corner)
11. Select YES on next screen (Are you ready to export your Lomotif?)
12. Click on "No thanks, I'll share later" button
13. Click on YES on next screen (Cancel Sharing)

Expected result: Created lomotif should be saved to Home screen and home screen should be displayed to create new lomotif

Actual result: Application crashes

**Comment by xiuie** [comment]
@tsukisa I can replicate this 80% of the time.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@caa102c6d7b6c3b69ffcba45e6f86cafc9bd1b08
