### ISSUE TITLE
[2.1.17] iPhone 6S / 10.2.1 - User is not receiving push notifications for "Follow/Like/Comment" when user there in a app.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1535]
Frequency: Every time

Action:
1: Launch the app on Device-1 and login with valid credentials User-A.
2: Launch the app on Device-2 and login with valid credentials User-B.
3: User-B search for User-A and Follow.
4: Check if User-A is receiving push notification when User-A there in a app.

Expected result: User should receive all push notifications for "Follow/Like/Comment" when user there in a app.

Actual result:
1: User is not receiving push notifications for "Follow/Like/Comment" when user there in a app.
2: User is receiving push notifications for "Follow/Like/Comment" when user not in a app.

Please refer video following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudVkVkbEFJMndoNjQ

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.17] on iPhone 5 / 10.0.1
