### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - App Crash - By changing song in created lomotif and save it again by Home button

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#154]
Frequency: Once

Action:
1. Launch Lomotif
2. Select and open any created lomotif
3. Go to Audio option
4. Click on Song change icon
5. Select any song from Find Music tab
6. Click on Home button
7. Save the lomotif

Expected result: Changed lomotif should be saved at home screen

Actual result: Application crash

**Comment by xiuie** [comment]
@hiteshbheda Does this one still happen in the latest build?

**Comment by hiteshbheda** [comment]
@xiuie No, I just have checked it. This bug has been resolved in 1.8.2. 

App does not crash now.
