### ISSUE TITLE
[2.1.17] iPhone 6 / 10.2 - "Followers" count is changed and displayed similar to "Following" count when user navigate to "Following" screen and again navigate back to "Profile" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1545]
Frequency: Every time

Precondition:
- There should be some "Followers" and "Following" users.

Action:
1: launch the app and login with a valid credential.
2: Navigate to "Profile" screen and observe the "Following" count.
3: Tap on "Following" option and navigate to "Following" screen.
4: Let the loading process to get complete and then navigate back to "Profile" screen.
5: Check if the "Followers" count is changed and displayed similar to "Following" count or not.

Expected result: "Followers" count should not be changed and displayed similar to "Following" count.

Actual result: 
1: "Followers" count is displayed similar to "Following" count when user navigate to "Following" screen and again navigate back to "Profile" screen.
2: When the user navigates to "Followers" screen and navigate back to "Profile" screen, then the count is displayed correctly.

Note: Similar issue is observed on other users "Profile" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iVEU4LW8wdUtvT2s

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.17] on iPhone 6 Plus / 10.1.1

**Comment by xiuie** [comment]
supposedly fixed
