### ISSUE TITLE
[2.1.17] iPhone 6 Plus / 10.1.1 - Waveform of added song is getting out of bound on "Create" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1552]
Frequency: Every time

Action:
1: Launch the app and login with a valid credential.
2: Tap on "START", create lomotif with motifs and proceed to "Create" screen without music.
3: Navigate to "Music" section and tap on "Add songs" option, user will be navigated to "Find Music" screen.
4: Select one song and tap on "Tick" option, the user will be navigated to "Create" screen with selected song.
5: Navigate to "Music" section and observe added song waveform is not displayed.
6: Scroll up and again scroll down to "Music" section(Observe waveform is displayed).
7: Check if the waveform of added song is getting out of bound or not.

Expected result: Waveform of added song should not get out of bound on "Create" screen.

Actual result: Waveform of added song is getting out of bound on "Create" screen.

Note: User needs to save the lomotif and again load the same lomotif to get waveform displayed correctly.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iR2trcG96RENkdjg

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.17] on iPhone 6  / 10.2

**Comment by xiuie** [comment]
supposedly fixed
