### ISSUE TITLE
[Live Build (2.1.17)] iPhone 5S / 10.2 - The appearance of some stickers is very small on "Create" screen.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1556]
Frequency: Every time

Action:
1: Launch the app with/without login.
2: Tap on "START".
3: Create lomotif with Photos/Videos/Motifs with/without music.
4: Enable sticker and select mentioned(Refer screenshot) stickers.
5: Check if the appearance of mentioned sticker is very small.

Expected result: The appearance of sticker should be normal on "Create" screen.

Actual result: The appearance of some stickers is very small on "Create" screen.

Please refer attached screenshot for more details:
![19](https://cloud.githubusercontent.com/assets/24449093/23391915/444acebe-fd9e-11e6-90ec-a53b8c083c89.jpg)

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for [Live Build (2.1.17)] on iPhone 5 / 10.0.1

**Comment by xiuie** [comment]
Stickers have been removed.

**Comment by Aboli-Testershub** [comment]
@xiuie, Ok Noted.

**Comment by Aboli-Testershub** [comment]
@xiuie, Only one sticker has been removed, another sticker is still displayed with the small appearance.
Please refer attached screenshot for more details:
![20](https://cloud.githubusercontent.com/assets/24449093/23497041/5c0d17be-ff47-11e6-9ad1-8472e89a0955.jpg)
