### ISSUE TITLE
[Live Build (2.1.17)] iPhone 6 Plus / 10.1.1 - Error: "Error - Unknown" message is displayed when user tries to sign up with "Facebook" account on "Username" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1557]
Frequency: Every time

Precondition:
- User should have one new "Facebook" account(Not used before).

Action:
1: Launch the app.
2: Swipe up to reveal "Profile" screen and tap on "Sign up/Login" button, user will be navigated to "Sign up" screen.
3: Tap on "Connect with Facebook" button and the user will navigate to "Facebook" sign up the screen.
4: Enter all valid credential to log in with "Facebook" account, user will be asked to authenticate the account.
5: User will be then navigated to "Username" screen by tapping on "Ok" option of authentication.
6: Enter all valid details and tap on "Let's go" button.
7: Check if Error: "Error - Unknown" message is displayed when user tries to sign up with "Facebook" account on "Username" screen.

Expected result: Error: 
1: "Error - Unknown" message should not be displayed.
2: User should be able to sign up with "Facebook" account.

Actual result: Error: "Error - Unknown" message is displayed when user tries to sign up with "Facebook" account on "Username" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iMldvQXFlNEg3QXM

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [Live Build (2.1.17)] on iPhone 5S / 10.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.18] on iPhone 6 Plus / 10.1.1
