### ISSUE TITLE
[Live_Build (2.1.8)] iPhone 7 / 10.2.1 - "Followers/Following/Lomotifs" count is getting reset to zero when user navigate to "Profile" screen from "Home" screen.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1561]
Frequency: Every time

Precondition:
- There should not be any "Followers/Following" under "Following/Followers" screen.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Profile" screen and observe "Following/Followers" count is zero.
3: Navigate to "Home>>Friends on Lomotif" screen and search for any user.
4: Tap on "Follow" option, user will start following the searched user.
5: Navigate back to "Home>>Profile" screen.
6: Check if the "Following" count is first increasing and then getting reset to zero.

Expected result: "Followers/Following/Lomotifs" counts should not get reset to zero when user navigate to "Profile" screen from "Home" screen.

Actual result: 
1: "Followers/Following/Lomotifs" count is getting reset to zero when user navigate to "Profile" screen from "Home" screen.
2: "Following/Followers" user are displayed under "Following/Followers" screen and uploaded lomotifs are also displayed under "Lomotifs" tab.

Note: 
1: Similar issue is observed for "Like/Comments".
2: Issue is observed when auto refresh is done after the user is navigating to "Profile" screen from "Home" screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iYWUzYnZSek5sRHM

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [Live_Build (2.1.8)] on iPhone 5 / 10.0.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for live build [2.1.8] on iPhone 7 / 10.2.1

**Comment by xiuie** [comment]
supposedly fixed
