### ISSUE TITLE
[2.1.20] iPhone 6S / 10.2.1 - User is unable to Sign Up continuous loading "Registering your account" is displayed after tapping on "Sign up" button on "Sign up" screen. 

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1566]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "User" icon and  tap on "Sign up | Log in" button.
3: Tap on "Sign up" option and navigate to "Sign up" screen.
4: Tap on "Sign up" button.
5: Check if continuous loading is displayed or not.

Expected result: User should be able to sign up continuous loading should not be displayed after tapping on "Sign up" button on "Sign up" screen.

Actual result: User is unable to sign up continuous loading "Registering your account" is displayed after tapping on "Sign up" button on "Sign up" screen. 

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudRU8wdFJNd0JrMzA

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.20] on iPhone 6 Plus / 10.2.1

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.21] on iPhone 7 / 10.2.1
