### ISSUE TITLE
[2.1.20] iPhone 7 / 10.2.1 - "Eye" symbol is not displayed to see the entered password under "Password" field.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1567]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Sign Up/Login" screen and navigate to "Login" screen.
3: Check if the "Eye" symbol is displayed or not.

Expected result: "Eye" symbol should display to see the entered password under "Password" field.

Actual result: "Eye" symbol is not displayed to see the entered password under "Password" field.

Refer the following screenshot for more details:
![eye](https://cloud.githubusercontent.com/assets/24311318/23642847/eb90fe16-0323-11e7-8fe6-02a0ef7114a6.jpg)

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.20] on iPhone 6S / 10.2.1

**Comment by xiuie** [comment]
supposedly fixed
