### ISSUE TITLE
[2.1.20] iPhone 6 Plus / 10.2.1 - Application is crashing when user swipe right to reveal "Sign up/Login" screen while logging in process.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1568]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Profile" screen and tap on "Sign up/Login" button, user will be navigated to "Sign up/Login" screen.
3: Tap on "Log in"option, user will be navigated to "Login" screen and enter all valid credential.
4: Tap on "Log in" button and immediately swipe right or tap on "<"option to navigate "Sign up/Login" screen.
5: Check if the application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user swipe right to reveal "Sign up/Login" screen while logging in process.

Note: Similar issue is observed when user login from "Notification" screen and "Following" tab.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iS0w2UV9OV3VCWjQ

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.20] on iPhone 7 / 10.2.1

**Comment by xiuie** [comment]
supposedly fixed

**Comment by Pankaj-Testershub** [comment]
@xiuie Verified Fixed.
