### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - App Crash Bug - Share on Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#157]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video from Camera Roll
4. Select any song from My Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select Facebook to share created lomotif

Expected: Lomotif should be shared on Facebook

Actual: Application crashes

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1.
