### ISSUE TITLE
[1.8.0] iPhone 5S / 8.4.1 - Find Music - Application crashes when user selects any item from menu on My Music tab

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#158]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Open 'dance' album
5. Select the first video
6. Tap apply button on Albums screen
7. Switch to My Music tab on Find Music screen
8. Open menu on My Music tab
9. Tap on Playlists item

Expected result: User sees all playlist from phone

Actual result: Application crashes

Video:
https://drive.google.com/file/d/0BwvEsBEA6ip4WDJ1NUdGbGVvQkk/view?usp=sharing

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Similar to #206 

I can't replicate this bug for build [1.8.4] on iPhone 6 / 9.3.1

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by vysohanych** [comment]
This bug seems is duplicate of bug #163  . You can close one of them.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this bug for build [1.8.6] on iPhone 6 / 9.3.1

Agree with @vysohanych. You can close this issue as well also close similar issue #163 and #206
