### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Wrong Results in Find Music search - Search song from Find Music with "ping" word displays wrong search items/results

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#159]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Select multiple videos from motif
5. Go to Find Music tab 
6. Click on search tab
7. Search for "ping" word

Expected result: Songs which contains word "ping" should be displayed as result

Actual result: Displays wrong songs list, which do not contain "ping" word

![img_0811](https://cloud.githubusercontent.com/assets/9691390/13342440/7c020e98-dc67-11e5-9e14-0741446bf51b.PNG)

![img_0812](https://cloud.githubusercontent.com/assets/9691390/13342441/7c344642-dc67-11e5-9217-ff92b1b5b19f.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @ruiwen I can still replicate this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

It may be because of the searched keyword contains anywhere with that album. Not sure :)

**Comment by ruiwen** [comment]
@hiteshbheda @vysohanych Probably a backend implementation issue, but this seems to be working as  intended (if not quite as expected) =)

**Comment by hiteshbheda** [comment]
@ruiwen Thanks for update..!!
