### ISSUE TITLE
[2.1.24] iPhone 7 / 10.2.1 - Sound enable and disable option is not available for "Lomotif Preview" on Following tab. 

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1598]
Frequency: Every time

Precondition: There should be at least one lomotif uploaded.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "Feed" icon and navigate to "Following" tab.
3: Tap on "Lomotif Preview".
4: Check if "Sound" option is available for enable and disable the sound.

Excepted Result: Sound enable and disable option should be available for "Lomotif Preview" on Following tab. 

Actual Result: Sound enable and disable option is not available for "Lomotif Preview" on Following tab. 

**Note** **: Similar issue is observed for "Lomotif Preview" in "Lomotif tab".**

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.10 (2.1.24)] on iPhone 6 Plus / 10.2.1

**Comment by xiuie** [comment]
We no longer have such a feature. You now pause to stop or mute from your device.
