### ISSUE TITLE
[1.6.5] Waveform not loaded when music is selected from "My Music"

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#16]
Also there are no album art and title.

Note this issue was also present in 1.6.3, a build which works properly when using 30-sec iTunes preview. This bug only occured when using music from the user's device. In 1.6.5, music previews do not work either.

**Comment by tsukisa** [comment]
Bug resolved with commit at Lomotif/lomotif-ios@73b35be
