### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Search Option/Menu button Bug - Once selected Songs from Option/Menu button list and try to select again from Option/Menu button, its not working / disable

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#160]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll on Albums screen
4. Select few photos from Camera Roll
5. Go to My Music tab
6. Click on Search bar
7. Search for particular word/string/character (I have searched for "Bhi" string)
8. Click on Search Button from Keyboard
9. Click on Option button (Left to search music space)
10. Select Songs from given list
11. Now, again click on Option button (Left to search music space)

Expected result: Option/Menu button (Left to search music space) should be selected to do more search for word/string entered

Actual result: Option/Menu button (Left to search music space) not working / disable

![img_0777](https://cloud.githubusercontent.com/assets/9691390/13343875/f8c7b96e-dc76-11e5-80bc-44b0dd6a170d.PNG)

![img_0778](https://cloud.githubusercontent.com/assets/9691390/13343872/f8b2888c-dc76-11e5-8332-0a1f826d0269.PNG)

![img_0779](https://cloud.githubusercontent.com/assets/9691390/13343873/f8bc628a-dc76-11e5-89cc-3da478281f09.PNG)

![img_0780](https://cloud.githubusercontent.com/assets/9691390/13343871/f8ad6c8a-dc76-11e5-8f04-2dd557dded20.PNG)

![img_0781](https://cloud.githubusercontent.com/assets/9691390/13343874/f8c5c17c-dc76-11e5-928c-b103b33f09b4.PNG)

**Comment by xiuie** [comment]
I can replicate this.

**Comment by tsukisa** [comment]
@xiuie issue has been resolved
