### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Delete button Bug - Unable to delete photo during creation of lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#161]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Camera Roll on Albums screen
4. Select few photos from Camera Roll
5. Go to My Music tab
6. Select any song
7. Click on any photo/picture in created lomotif
8. On next screen, Click on Delete option (-) 

Expected result: Selected Picture/Photo should be deleted

Actual result: Delete option/button not working, Picture/Photo not deleted

![img_0815](https://cloud.githubusercontent.com/assets/9691390/13344896/2f7b49fe-dc80-11e5-8e21-b8951b39b42e.PNG)

**Comment by xiuie** [comment]
@pmtheint Shooting this over to you because almost every tester thinks this is a bug, although it works as designed. Not sure how to improve this.

**Comment by pmtheint** [comment]
@xiuie The + and - buttons should not have shown up unless they are being pressed and held (not tapped). By showing the buttons with a tap, we're implying that these buttons can be pressed. A good issue. Will log this on Asana.

**Comment by pmtheint** [comment]
Logged on Asana. Proposed new UX.
