### ISSUE TITLE
[2.1.26] iPhone 6S / 10.2.1 - Profile picture of Facebook account fails to fetch to Lomotif account.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1621]
Frequency: Every time.

Precondition: Facebook account should have a profile picture.

Action:
1: Launch the app and logged in with facebook credentials.
2: Navigate to "Profile" screen.
3: Check if profile picture fetched.

Expected result: Profile picture of Facebook account should fetch to Lomotif account.

Actual result:  Profile picture of Facebook account fails to fetch to Lomotif account.

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.26] on iPhone 6 / 10.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.28] on iPhone 6 Plus / 10.2.1
