### ISSUE TITLE
[2.1.26] iPhone 7 / 10.2.1 - Music is still remaining audible on "Saving your Lomotif" screen when user opens keypad to enter text and taps on "Export" option.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1624]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START", create lomotif with motifs/videos/pictures and with music.
3: Tap on the text field to enter text, the keypad will appear.
4: Tap on "Export" option and navigate to "Saving your Lomotif" screen.
5: Check if the music is audible on "Saving your Lomotif" screen or not.

Expected result: Music should not be audible on "Saving your Lomotif" screen when user opens keypad to enter text and then taps on "Export" option.

Actual result:  Music is still remaining audible on "Saving your Lomotif" screen when user opens keypad to enter text and taps on "Export" option.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iOEpIazNFR0VZaXc

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.26] on iPhone 6 / 10.2

**Comment by Pankaj-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.28] on iPhone 6 Plus / 10.2.1
