### ISSUE TITLE
[2.1.26] iPhone 6S / 10.2.1 - "Following" tab>Lomotif preview is fails to play after single tapping on it when preview progress gets finished. (Issue is specifically observed when "Following" tab has only one Lomotif or for last Lomotif).

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1625]
Frequency: Every time

Precondition: There should be only one lomotif in "Following" tab.

1: Launch the app and login with valid credentials.
2: Navigate to "Feed>>Following" tab.
3: Let the preview finish.
4: Single tap on the lomotif.
5: Check if lomotif preview is playing.

Expected result:  "Following" tab>Lomotif preview should play after single tapping on it when preview progress gets finished.

Actual result: Lomotif preview in "Following" tab is playing after the second tap.

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudNEVEUk5yRnV3Tnc

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.26] on iPhone 7 / 10.2.1

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.29] on iPhone 6 Plus.
