### ISSUE TITLE
[2.1.27] iPhone 6 Plus / 10.2.1 - Feature fade in and fade out is not working properly for recently uploaded lomotif on "Following" tab.

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1630]
Frequency: Every Time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and Create lomotif with photos/videos/motifs with/without music.
3: Export lomotif and cancel sharing.
4: Navigate to "Following" tab (Let the lomotif upload).
5: Tap on "Lomotif Uploaded" pop up message.
6: Check if feature fade in and fade out is not working on "Following" tab.

Excepted Result: Feature fade in and fade out should be work properly for recently uploaded lomotif on "Following" tab.

Actual Result: 
1: Feature fade in and fade out is not working properly for recently uploaded lomotif on "Following" tab.
2: When user tap on "Lomotif Preview" it is working fine.

Refer following video link for more details:
https://drive.google.com/open?id=0B_UFwGpNtOm2NkdYUU9KU2I1YTg

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.27] on iPhone 5S / 10.2

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.29] on iPhone 6 Plus.
