### ISSUE TITLE
[2.1.27] iPhone 7 / 10.2.1 - User is able to Like lomotif after double tapping on "Like" (Heart) icon on "Following/Lomotif Preview" screens.

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1633]
Frequency: Every time.

Precondition: There should be some lomotifs under "Following/Lomotif" tabs.

Action:
1: Launch the app and login with a valid credential.
2: Navigate to "Following" tab.
3: Double tap on "Like" icon (Observe, Like count will not increase).
4: Check if lomotif is displayed as liked.

Expected result: User should be unable to like lomotif after double tapping( the first tap should be like and the second tap should be unlike and vice versa.) 

Actual result:
- The user is able to like lomotif and like count is not increased. (Like count is set when the user navigates back to "Following/Lomotif Preview" screens from "Like" screen.)
- The user is receiving notifications for like.

Please refer following video link for more details:
https://drive.google.com/open?id=0Bx8fu9rzyCudakZOenpyb3JCSHc

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.27] on iPhone 6 Plus / 10.2.1
