### ISSUE TITLE
[2.1.27] iPhone 6 Plus / 10.2.1 - "Would you like to link your facebook.." message is displayed after tapping on "Facebook" option even when user has already linked with "Facebook" account from "Camera Roll".

### ISSUE THREAD

**Issue by Aishwarya-Testershub** [Lomotif/lomotif-ios-issues#1635]
Frequency - Every time 

Precondition - "Facebook" account should be unlinked.

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START".
3: Tap on "Facebook" option.
4: "Would you like to link your Facebook.." message is displayed, tap on "OK".
5: Linked the Facebook account,Facebook assets is displayed.
6: Close "Facebook" option.
7: Again, Tap on "Facebook" option.
8: Check if "Would you like to link your Facebook.." message is displayed or not.

Excepted Result: "Would you like to link your facebook.." message should not be displayed after tapping on "Facebook" option even when user has already linked with "Facebook" account from "Camera Roll".

Actual Result: "Would you like to link your facebook.." message is displayed after tapping on "Facebook" option even when user has already linked with "Facebook" account from "Camera Roll".

Refer video link for more details:
https://drive.google.com/open?id=0B2TfWRODMVhYOXVhbXJCakFBUnc

**Comment by Aboli-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.27] on iPhone 5S / 10.2

**Comment by Aboli-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.29] on iPhone 6 Plus.
