### ISSUE TITLE
[2.1.28] iPhone 7 / 10.2.1 - Application crashes when user tries to login in the app.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1637]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Profile" screen.
3: Tap on "Sign up/Login" button and navigate to "Login" screen.
4: Enter valid credentials and tap on "Login" button.
5: Check if the application crashes.

Expected result: Application should not crash.

Actual result: Application crashes when user tries to login in the app.

Note: Application crashes every time after user relaunches the app.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iSXZKYnVHek5vYWc

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.29] on iPhone 6 / 10.2
