### ISSUE TITLE
[2.1.28] iPhone 7 / 10.2.1 - Application crashes when user tries to "Sign up" for the new account with Email/Username.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1638]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Profile" and tap on "Sign up/login" button.
3: Navigate to "Sign up" screen and enter all valid details:
4: Tap on "Sign up" button.
5: Check if the application crashes.

Expected result: Application should not crash.

Actual result: Application crashes when user tries to "Sign up" for the new account.

Note: Application crashes every time after user relaunches the app.

**Comment by Pankaj-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.28] on iPhone 6 Plus / 10.2.1

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.29] on iPhone 6 / 10.2
