### ISSUE TITLE
[2.1.28] iPhone 6 Plus / 10.2.1 - "LOMOTIF" text displayed on lomotif preview is truncated from right side when user share 16:9 view lomotif on "Instagram".

### ISSUE THREAD

**Issue by Aboli-Testershub** [Lomotif/lomotif-ios-issues#1640]
Frequency: Every time

Precondition: Instagram app should be installed and logged in with valid credentials.

Action:
1: Launch the app with/without login.
2: Tap on "START" and create 16:9 lomotif with photos/videos/motifs with/without music.
3: Export and share lomotif on "Instagram".
4: Wait till lomotif get upload.
5: Check if "LOMOTIF" text displayed on lomotif preview is truncated

Expected result: "LOMOTIF" text displayed on lomotif preview should not be truncated from left when user share 16:9 view lomotif on "Instagram".

Actual result: "LOMOTIF" text displayed on lomotif preview is truncated from left when user share 16:9 view lomotif on "Instagram".

Please refer attached screenshot for more details:
![39](https://cloud.githubusercontent.com/assets/24449093/24697940/98076500-1a0c-11e7-97de-2f25ed6dd4f6.jpg)

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [2.1.28] iPhone 5S / 9.3.5

**Comment by xiuie** [comment]
Not a bug. Users can share landscape video in its entirety on Instagram

**Comment by Aboli-Testershub** [comment]
@xiuie, OK Noted.
