### ISSUE TITLE
[Live Build_2.1.10] iPhone 7 / 10.3.1 - User is not able to login/Sign up with "Facebook" account, continuous loading is displayed.

### ISSUE THREAD

**Issue by Pankaj-Testershub** [Lomotif/lomotif-ios-issues#1649]
Frequency: Every time

Action:
1: Launch the app.
2: Navigate to "Profile>>Sign up/Login" screen.
3: Tap on "Connect with Facebook" button.
4: Check if continuous loading notification is displayed or not.

Expected result: User should be able to Sign up/Login with facebook account.

Actual result: User is not able to login/Sign up with "Facebook" account, continuous loading is displayed.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iLUlWdmRnQzVBQ1U

**Comment by Aishwarya-Testershub** [comment]
@xiuie I can reproduce this issue for build [Live Build_2.1.10] on iPhone 6 Plus / 10.2.1

**Comment by ruiwen** [comment]
@Aishwarya-Testershub @Pankaj-Testershub Hi guys, could you try again? We've made some changes on our end

**Comment by Pankaj-Testershub** [comment]
@ruiwen, We have checked and it is now working fine on our end.
