### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Audio not added when screenlock - During loading songs from Find Music, screen lock will cause problem with Audio in Lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#165]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video from Motif
4. Select any song from Find Music tab
5. During loading of Audio, Lock the screen/iPhone
6. Unlock iPhone
7. Play created Lomotif

Expected: Either audio should be added and if not added then should show certain message that audio has not uploaded

Actual: Lomotif created without Audio

![img_0817](https://cloud.githubusercontent.com/assets/9691390/13348036/29137746-dc97-11e5-80e3-737d2a2de041.PNG)

**Comment by xiuie** [comment]
Music from Find Music is not adding in general so I can't verify this now.

My music loads too quickly, so no time to lock phone.

**Comment by hiteshbheda** [comment]
@xiuie Yes, It may be happened. But if you try to load some larger song which takes longer time and try to follow the steps mentioned, then it will be reproduced.

**Comment by xiuie** [comment]
@tsukisa This might be causing the no-music bug.

**Comment by tsukisa** [comment]
@xiuie potentially fixed with commit Lomotif/lomotif-ios@5d757e7842, needs verify
