### ISSUE TITLE
[1.8.0] iPhone 5S / 8.4.1 - Albums - Application crashes when user stops song loading and confirms selected motifs

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#166]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Open 'slow mo' album
5. Select some videos
6. Tap apply button on Albums screen
7. Open the Adele's album Hello
8. Tap Use Music button
9. Tab back button on Find Music screen when song loading
10. Tap apply button on Albums screen

Expected result: User sees Find Music screen

Actual result: Application crashes

[crash.zip](https://github.com/Lomotif/lomotif-ios-issues/files/148551/crash.zip)

**Comment by tsukisa** [comment]
@xiuie i can't reproduce this
