### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Search Option/Menu button Bug - Can't search with spaces

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#167]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motifs on Albums screen
4. Select selena gomez from Motifs
5. Now, click on search tab (New! Find motifs easier with search)
6. Enter "selena" in search tab
7. It will display some results
8. Now enter "selena gomez" in search tab

Expected result: Results/Motifs of selena gomez should be displayed

Actual result: 1. No results / Motifs display, 
2. When we enter two words, search tab not working

![img_0792](https://cloud.githubusercontent.com/assets/9691390/13371011/8a6dfc3c-dd41-11e5-9810-6e46b6a3788b.PNG)

![img_0793](https://cloud.githubusercontent.com/assets/9691390/13371012/8aa26030-dd41-11e5-852d-7b98d936359b.PNG)

![img_0794](https://cloud.githubusercontent.com/assets/9691390/13371013/8abddae0-dd41-11e5-91c3-3bb197ecb570.PNG)

![img_0795](https://cloud.githubusercontent.com/assets/9691390/13371014/8ac3745a-dd41-11e5-9684-2f2fe24e3a9a.PNG)

**Comment by xiuie** [comment]
@benchang As I understand it we don't allow searches for more than one word? Are we planning to disable spaces or is there a better way?

i.e. selena gomez and selenag omez returns the selenagomez tag

**Comment by tsukisa** [comment]
@xiuie issue has been resolved
