### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Unable to play shared Lomotif on WhatsApp - Share on WhatsApp

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#168]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video from Camera Roll
4. Select any song from My Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select WhatsApp to share created lomotif
8. Select a contact from WhatsApp to share/send created lomotif
9. Send lomotif
10. After sent, click on play button to play shared lomotif

Expected: Shared Lomotif should be played after sharing

Actual: Error - Unable to play shared lomotif in WhatsApp

![img_0804](https://cloud.githubusercontent.com/assets/9691390/13371472/e10a96ee-dd4c-11e5-8f12-1d644ba96f49.PNG)

![img_0802](https://cloud.githubusercontent.com/assets/9691390/13371473/e135da2a-dd4c-11e5-9f5d-89eee801eebb.PNG)

**Comment by xiuie** [comment]
I currently can't reproduce this..

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce it now. But i have shared a screenshots for earlier problem/bug.
