### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Unable to insert Audio from Find Music - Unable to add audio from Find Music to create Lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#169]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any motifs from Motif
4. Go to Find Music tab
5. Select any audio ()
6. Create Lomotif
7. Play Lomotif

Expected: Audio (from Find Music) should be added in Lomotif 

Actual: Error - Audio (from Find Music) has been loaded 100% but not added in created Lomotif

![img_0819](https://cloud.githubusercontent.com/assets/9691390/13371517/21e9f780-dd4e-11e5-81fd-c3daf7a83dbe.PNG)

![img_0818](https://cloud.githubusercontent.com/assets/9691390/13371518/220b4fde-dd4e-11e5-91d5-1898378ae02c.PNG)

**Comment by ruiwen** [comment]
@tsukisa's found the issue in the code and is implementing a fix =)

**Comment by hiteshbheda** [comment]
@xiuie @ruiwen Thanks..!!

**Comment by tsukisa** [comment]
@xiuie resolved with commit Lomotif/lomotif-ios@dd45a7e0f8492ff2fe444a39bdbfbfe83d610d89
