### ISSUE TITLE
[1.8.0] iPhone 5S / 8.4.1 - Find Music - Song appears twice when user uses search on My Music tab

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#170]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap on START button
3. Switch to Motif tab on Albums screen
4. Open 'dance' album
5. Select the first video
6. Tap apply button on Albums screen
7. Switch to My Music tab on Find Music screen
8. Search any exists song

Expected result: Song appears once on search result screen

Actual result: Song appears twice on search result screen

![img_0573](https://cloud.githubusercontent.com/assets/3593359/13379113/ec655fcc-de25-11e5-8d94-dae3964eed8a.PNG)

**Comment by xiuie** [comment]
I can replicate this double-music bug

**Comment by ruiwen** [comment]
Any possible relation to this?
https://github.com/Lomotif/lomotif-ios-issues/issues/143

Edit: Nope, not a dupe

**Comment by xiuie** [comment]
@ruiwen Honestly don't know. I'll leave you to triage #170 then? :)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@ea7d59e6cc8cb6fd7a805ed4820287f1c9c84acd
