### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1   - Keyboard Dismissal - Keyboard dismissal is laggy

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#172]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Tap on “Search” Motifs
4. Click “X"
5. Notice keyboard takes 2 seconds to dismiss after the Videos page disappears

 Expected: Keyboard to be dismissed together with the page

Actual: Keyboard takes 2 seconds to dismiss, blocking the view of projects

**Comment by tsukisa** [comment]
issue has been resolved Lomotif/lomotif-ios@908ffc3b7e
