### ISSUE TITLE
[1.8.0] iPhone 6 / 9.2.1 - Duration - Maximum length not accurate

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#173]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 1 x video less than 5 secs (e.g. any Motif)
4. Select Music
5. Notice export video indicates that it is 15secs.. 
6. Adjust slider to 30secs

Expected: Feedback given that max duration cannot exceed total length of clips

Actual: Can move the slider anywhere between 3 and 30 secs

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this

**Comment by pmtheint** [comment]
@xiuie noted. Listed on Asana.

**Comment by pmtheint** [comment]
Been fixed.
