### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Menu Button Disable near Search Music - Once select any option from Menu, Menu option is disabled near Search Music in My Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#174]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video from any Motifs
4. Click on Next option (Top Right corner)
5. Select My Music from Find Music screen
6. Click on Menu option near Search Music option
7. Select album category from the list
8. Again try to click on Menu option

Expected: Option Menu should be clicked and work properly

Actual: Option Menu disabled once clicked on any item from available list

![img_0845](https://cloud.githubusercontent.com/assets/9691390/13499675/5da3863e-e185-11e5-9660-90b39ba6cf1c.PNG)

**Comment by tsukisa** [comment]
@xiuie issue fixed with commit Lomotif/lomotif-ios@77e3a95b8d
