### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - App crashes - Switching between Lomotif app and other apps on iPhone

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#175]
Frequency: Once / Twice

Action:
1. Launch Lomotif
2. Tap on START button
3. Select multiple videos from Motifs
4. Tap on Find Music tab
5. Select any song from Find Music
6. 100 % song loading process complete and create lomotif
7. Now, Play and Pause a created lomotif on the screen
8. Then switch to any other app installed on iPhone
9. Again, Switch to lomotif app

Expected: Lomotif app should be running and it should display/play created lomotif

Actual: App crashes

**Comment by xiuie** [comment]
Can't replicate. Closing for now.. Let me know if you can reproduce it in 1.8.2 @hiteshbheda
