### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - App Crashes - During Sharing lomotif on Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#176]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video from Camera Roll
4. Select any song from My Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select Facebook to share created lomotif

Expected: Lomotif should be shared on Facebook

Actual: Application crashes

**Comment by xiuie** [comment]
I can't reproduce this either. @hiteshbheda If it still occurs in 1.8.2 please send a video.
