### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The videos in the folders disappear in the "Motif" section after scrolling the screen down

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#180]
Also the folders flicker after reproducing this bug during the scrolling

Frequency: Every time
1. Launch the app
2. Tap the "Start" button
3. Open the "Motif" section
4. Open any of the 5 last folders
5. Scroll the list down\up (Repeat this step several times if needed)
6. Take a look at videos in the folders

Actual result: The videos in the folders disappear in the "Motif" section after scrolling the screen down
Expected result: The videos in the folders do not disappear in the "Motif" section after scrolling the screen down

Video: https://www.dropbox.com/s/5bz7dylj3xrr480/Video_Bug_563_disappear.mp4?dl=0

**Comment by tsukisa** [comment]
flickering issue is fixed with commit Lomotif/lomotif-ios@7d073d1452
