### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The user cannot scroll the video list to the end in the "Motif" section

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#183]
Frequency: Every time
1. Launch the app
2. Tap the "Start" button
3. Open the "Motif" section
4. Open any folder
5. Scroll down the video list
6. Observe the result

Actual result: The user cannot scroll the video list to the end in the "Motif" section
Expected result: The user can scroll the video list to the end in the "Motif" section

Video: https://www.dropbox.com/s/3lexs6csrlplrpw/Video_Bug_569_scroll.mp4?dl=0

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@b3e8194c9c
