### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The video starts to play on the "Create" screen after hiding and reopening the app if the video was paused

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#184]
Frequency: Every time
1. Launch the app
2. Tap the "Start" button
3. Open the "Motif" section
4. Select several videos
5. Proceed to the "Create" screen
6. Tap the "Play" button and pause the video
7. Hide the app and reopen it 
8. Observe the result

Actual result: The video starts to play on the "Create" screen after hiding and reopening the app if the video was paused
Expected result: The video does not start to play on the "Create" screen after hiding and reopening the app if the video was paused

Video: https://www.dropbox.com/s/b11wl5iz5qpoej8/Video_Bug_571_hide.mp4?dl=0

**Comment by xiuie** [comment]
@pmtheint Either log as asana task, or close.. depending on your assessment. :)

**Comment by pmtheint** [comment]
Works as designed. Proposed new UX on Asana.
