### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The video starts to play on the "Create" screen after tapping the duration line in any point

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#185]
Frequency: Every time
1. Launch the app
2. Tap the "Start" button
3. Open the "Motif" section
4. Select several videos
5. Proceed to the "Create" screen
6. Tap the duration line in any point
7. Observe the result

Actual result: The video starts to play on the "Create" screen after tapping the duration line in any point
Expected result: The video changes its duration and does not start to play on the "Create" screen after tapping the duration line in any point

Video: https://www.dropbox.com/s/4lx04tzpmbstm7x/Video_Bug_570_duration.mp4?dl=0

**Comment by xiuie** [comment]
@pmtheint Fyi. Video included. If not an issue to you, please close.

**Comment by pmtheint** [comment]
Works as designed.
