### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The language does not change on the "FAQ" screen after tapping the "russian" button

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#187]
Frequency: Every time
1. Launch the app
2. Tap the settings button
3. Open the "FAQ" section
4. Tap the "russian"(русский) button
5. Observe the result

Actual result: The language does not change on the "FAQ" screen after tapping the "russian" button
Expected result: The language changes on the "FAQ" screen after tapping the "russian" button

Video: https://www.dropbox.com/s/3h1nrdt45iggv8y/Video_Bug_573_russian.mp4?dl=0

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1
