### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - Some sections are not translated on the settings screen when the device language is russian

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#188]
Frequency: Every time

Preconditions: change the device language to russian
1. Launch the app
2. Tap the settings button
3. Pay attention to the section 

Actual result: Some sections are not translated on the settings screen when the device language is russian
Expected result: All sections are translated on the settings screen when the device language is russian

![bug_539_translate](https://cloud.githubusercontent.com/assets/17638908/13530496/575ed1ca-e22a-11e5-80b0-58dbfc735b81.png)

**Comment by tsukisa** [comment]
Last section of settings view is for testing purpose only, it doesn't exist in live build
