### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The font sizes of some sections differ from the rest font sizes of others sections

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#189]
Frequency: Every time

Preconditions: change the device language to russian
1. Launch the app
2. Tap the settings button
3. Pay attention to the font sizes of some sections

Actual result: The font sizes of some sections differ from the rest font sizes of others sections on the settings screen
Expected result: The font sizes of all section are the same on the settings screen

![bug_540_size](https://cloud.githubusercontent.com/assets/17638908/13530630/04226b7e-e22b-11e5-8c46-d1d25b1b39a5.png)

**Comment by xiuie** [comment]
Just fyi @pmtheint

**Comment by pmtheint** [comment]
Logged and prioritised on Asana
