### ISSUE TITLE
[1.8.1] iPhone 6s (9.2.1) - The "Facebook" icon is not centered on the main screen

### ISSUE THREAD

**Issue by QAmobiletester** [Lomotif/lomotif-ios-issues#190]
Frequency: Every time

Preconditions: change the device language to russian
1. Launch the app
2. Take a look at the "Facebook" icon

Actual result: The "Facebook" icon is not centered on the main screen
Expected result: The "Facebook" icon is centered on the main screen

![bug_538_fb](https://cloud.githubusercontent.com/assets/17638908/13530705/6917c92a-e22b-11e5-87a2-cb50ea04f650.png)

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1
