### ISSUE TITLE
[1.8.1] iPhone 6 (9.2.1) - Motifs search - The app crashes when you search for two words

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#192]
Frequency: Every time

Launch the app
Tap the "Start" button
Open the "Motif" section
Enter search term with space e.g. Nicki Minaj
Press search
Observe the crash

Expected result: The app does not crash (the app ignores the space and searches for nickiminaj)

Actual result: The app crashes

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@7b947be3ec
