### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Two Instagram Folders - At selecting photos from Camera Roll

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#193]
Frequency: Every time

Action:
1. Launch the app
2. Tap the "Start" button
3. Open Albums screen
4. Select Camera Roll
5. Check for Instagram folder

Expected result: One Instagram folder shold be available to store and open created lomotifs

Actual result: Two Instagram folders are available at Camera Roll screen at Albums

![img_0864](https://cloud.githubusercontent.com/assets/9691390/13534616/0307034a-e25c-11e5-98c9-e88cda84ca28.PNG)

**Comment by xiuie** [comment]
I have two "All Photos" albums instead, and have reported this issue before in #109

**Comment by tsukisa** [comment]
@xiuie @hiteshbheda first Instagram folder pulls video from your Instagram account, second Instagram folder is created by Instagram app.
