### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Click on one search motif automatically selects two motifs - At selecting motifs from search option results

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#194]
Frequency: Every time

Action:
1. Launch the app
2. Tap the "Start" button
3. Click on Motifs tab on Albums screen
4. Click on Search motif tab
5. Search for "Slow" word
6. Scroll down screen and load more results
7. Multiple duplicate results may be available
8. Select on any one motifs from loaded results

Expected result: 
1. Only one motif should be selected
2. In case as per your flow both the screen should be selected then also it should be displayed results as 2 selected motifs at top right corner of screen

Actual result: If we load more results by scrolling down the screen and select any specific motif from loaded results, it will automatically select another duplicate motif from upper results and displays selected motif result as only one instead of two.

![img_0867](https://cloud.githubusercontent.com/assets/9691390/13536132/3459bef8-e264-11e5-84aa-8b28d1ddcdad.PNG)

![img_0868](https://cloud.githubusercontent.com/assets/9691390/13536131/3452ee98-e264-11e5-84b8-6b717ee43709.PNG)

**Comment by xiuie** [comment]
I can replicate on iPhone 6/1.9.2

**Comment by tsukisa** [comment]
@xiuie ok i think i know the issue, because the clip selected appears more than once in the result. Will investigate this

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1
