### ISSUE TITLE
[1.8.1] iPhone 5S / 8.4.1 - Sharing screen - Error 'Request failed: server error (0)' appears on Home screen when user tries export via Twitter without wi-fi

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#196]
Frequency: Every Time

Action:
1. Turn off wi-fi on device
2. Launch Lomotif
3. Open any exists lomotif
4. Tap export button on Create screen
5. Tap Twitter button on sharing screen

Expected result: User sees error message on sharing screen

Actual result: Error 'Request failed: server error (0)' appears on Home screen

![img_0595](https://cloud.githubusercontent.com/assets/3593359/13547239/75b14046-e2d3-11e5-8f5c-4f3584d1d883.PNG)

**Comment by xiuie** [comment]
Resolved. Now has been replaced by "Upload Failed. Twitter upload failed."
