### ISSUE TITLE
[1.8.1] iPhone 5S / 8.4.1 - Sharing screen - User can open a few sharing screens

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#197]
Frequency: Sometime

Action:
1. Launch Lomotif
2. Open any exists lomotif
3. Tap a few times export button on Create screen

Expected result: Only one sharing screens was opened

Actual result: A few sharing screens were opened

Video: https://drive.google.com/file/d/0BwvEsBEA6ip4M3N0M0dEVTUyR0E/view?usp=sharing

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@1f2be6b963
