### ISSUE TITLE
[1.8.1] iPhone 5S / 8.4.1 - Albums - Application crashes, when user uses in search not Latin letters

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#198]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Switch to Motif tab on Albums screen
4. Switch keyboard's language to language with not Latin letters (for example to Ukrainian)
5. Enter search text as 'тест'
6. Tap search button on keyboard

Expected result: User doesn't see any search result

Actual result: Application crashes

Video: https://drive.google.com/file/d/0BwvEsBEA6ip4eFotNVlvSk5iRjQ/view?usp=sharing

**Comment by tsukisa** [comment]
@xiuie @vysohanych search terms is encoded now, please try again

**Comment by vysohanych** [comment]
Search works correct. The application doesn't crash
