### ISSUE TITLE
Facebook Login is Not Working 

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#2]
1. Open Lomotif App 
2. Click On Create a Lomotif 
3. Click on Facebook button
4. Login with Valid Details It showing Error Application is still in development Mode 

Here is the screenshot,
![img_0085](https://cloud.githubusercontent.com/assets/5388768/12229955/795ca522-b872-11e5-8e22-3a4c086cf795.PNG)

**Comment by tsukisa** [comment]
Test version of lomotif is using Facebook test environment, that only allows a list of approved users to login.
