### ISSUE TITLE
[1.6.5] Panoramic photos captured on the iPhone appears "black" in the app

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#20]
The same panoramic photo work in the live build

**Comment by tsukisa** [comment]
Probably fixed with commit at Lomotif/lomotif-ios@c25da24

**Comment by tsukisa** [comment]
@xiuie Bug will be considered fixed if no confirmation is received.

**Comment by xiuie** [comment]
@tsukisa Still not fixed in the 1.6.8 build

**Comment by tsukisa** [comment]
Found the issue. The number of pixel in panaramic photo is too large for the rendering engine to handle that's why the image -> video conversion fails. I will try to find the sweet spot for this.

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@09316c931273ca6259f9926301df69f3fc8ceb46
