### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Camera Roll Disabled - When clicked on Search Motif tab, Camera Roll disabled

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#200]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Tap on “Search Motif” in Albums tab
4. Click on Camera Roll

Expected: Camera Roll should be accessible / opened and "Search Motif" option should be disappear.

Actual: Unable to click on Camera roll, Camera Roll disabled

![img_0855](https://cloud.githubusercontent.com/assets/9691390/13549243/9d7467b2-e327-11e5-9486-8cadeac31ac1.PNG)

![img_0856](https://cloud.githubusercontent.com/assets/9691390/13549242/9d7263ea-e327-11e5-8d08-9899011fef4b.PNG)

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@14df77b509
