### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Wrong videos (not as per category) in Motif - Problem with "rain" motifs, it shows different videos on "rain" motif category

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#201]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Tap on  motif tab on Albums screen
4. Select "rain" category

Expected: Selection of "rain" category motif should show relevant videos/motifs.

Actual: It shows different videos (Justin Bieber's videos)

![img_0876](https://cloud.githubusercontent.com/assets/9691390/13549498/450b9618-e32c-11e5-83a3-9b6b544a1aeb.PNG)

**Comment by tsukisa** [comment]
@xiuie @hiteshbheda this was a bug in v1.8.1, please verify if it still persist in v1.8.2

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Problem has been resolved. It works correctly in 1.8.2 now. 
Thank you.
