### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Vidoes disappear after displayed once in some Motif category - Select certain motif category creates this problem

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#202]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Tap on motif tab on Albums screen
4. Select motif categories like beliebers only!, trippy!, dd4l or clouds
5. Observe the effect / result

Expected: Videos / motifs of respective selected category should be displayed

Actual: Videos appears once for a second and immediately disappear and black screen display after it for upper mentioned motif categories.

![img_0873](https://cloud.githubusercontent.com/assets/9691390/13549551/9bf80848-e32d-11e5-830f-18a34cd7edb9.PNG)

![img_0874](https://cloud.githubusercontent.com/assets/9691390/13549552/9bfded4e-e32d-11e5-950d-eb13c504e8a8.PNG)

![img_0875](https://cloud.githubusercontent.com/assets/9691390/13549553/9bff5544-e32d-11e5-9ecb-0bacca712b09.PNG)

![img_0877](https://cloud.githubusercontent.com/assets/9691390/13549554/9c558b62-e32d-11e5-8c4d-d4ef5ef30c2f.PNG)

**Comment by xiuie** [comment]
@paulyangzhiwen I can't replicate this. Can you try?

**Comment by paulyangzhiwen** [comment]
@xiuie cannot replicate (iPhone 6s / 9.2)

**Comment by hiteshbheda** [comment]
@xiuie @paulyangzhiwen  It works correctly now, but when i have tried earlier there was a problem (I have attached screenshots as well).

**Comment by tsukisa** [comment]
@xiuie issue has been resolved
