### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2.1 - Clear value in Search box does not affect to search song results - During search in My Music with a word and cancel/clear word not affecting to search songs result

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#203]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Select multiple videos from motif
5. Go to Find Music tab
6. Select My Music
7. Type any word in the search box (I have typed "Bewajah" word)
8. It will show you list of songs which contain entered word
9. Now, erase the word from search box and click on cancel button (available at right of search box)

Expected result: When erase the value / word from search box and click on cancel button, it should display the list of all songs rather than only previously filtered songs

Actual result: Displays a list of songs which were available during previously searched word

![img_0852](https://cloud.githubusercontent.com/assets/9691390/13549581/c755ff80-e32e-11e5-9d68-1adbde433d2d.PNG)

![img_0853](https://cloud.githubusercontent.com/assets/9691390/13549582/c7576758-e32e-11e5-8fac-e3d87181dbb4.PNG)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@ea7d59e
