### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - Erase value in search box Bug - In Find Music search for a word and then erase/cancel word, not affect to search results

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#205]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Select multiple videos from motif
5. Go to Find Music tab to select audio
6. Type word "there"
7. It will show you one song as a result
8. Now, clear search box value and click on cancel

Expected result: Clear search box and click on cancel should refresh the songs list / results

Actual result: No change in results, shows previously filtered songs

![img_0896](https://cloud.githubusercontent.com/assets/9691390/13577408/5bc1f158-e4b8-11e5-9561-36ee05af4e26.PNG)

![img_0897](https://cloud.githubusercontent.com/assets/9691390/13577409/5bcb2af2-e4b8-11e5-95b1-ea68c18b2c7f.PNG)

![img_0898](https://cloud.githubusercontent.com/assets/9691390/13577410/5bcfd124-e4b8-11e5-92f3-dabea67dac68.PNG)

**Comment by xiuie** [comment]
Similar to #203

**Comment by pmtheint** [comment]
logged and prioritised in asana
