### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App crash - Clicking on Playlist in My Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#206]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any pictures from camera roll
4. Tap on  My Music tab from Find Music screen
5. Click on Menu button (left to search music space)
6. It will display various items
7. Select Playlists

Expected result: Playlists' songs should be displayed

Actual result: Application Crashes

![img_0917](https://cloud.githubusercontent.com/assets/9691390/13594045/1ba62732-e527-11e5-8966-187c16f3c998.PNG)

**Comment by Dipamit** [comment]
Able to replicate this issue in new build(1.7.12) with iPhone 5/8.3

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Similar to #158

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce it for build [1.8.6] on iPhone 6 / iOS 9.3.1
