### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App Crashes - During Search the word "slow mo" and swipe the screen to load more results

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#207]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Tap on Search box.
5. Type word "slow mo"
6. Click on Search button
7. Results will be displayed on the screens
8. Swipe screen to load more results/motifs

Expected result: More Results / motifs should be loaded and display

Actual result: Application Crashes

![img_0885](https://cloud.githubusercontent.com/assets/9691390/13603487/8eeb8ebc-e563-11e5-9c7d-9f71f9e87f8a.PNG)

![img_0886](https://cloud.githubusercontent.com/assets/9691390/13603488/8eed18ae-e563-11e5-87e7-d21dc1e02629.PNG)

**Comment by xiuie** [comment]
@tsukisa I can replicate this. Critical bug!

**Comment by tsukisa** [comment]
@xiuie was looking into this issue yesterday, will fix it asap

**Comment by tsukisa** [comment]
refer to issue #209

**Comment by tsukisa** [comment]
issue has been resolved
