### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - Search Results display Bug - Search the word "slow mo" and Cancel search will disappear "nicki minaj" category

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#208]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Tap on Search box.
5. Type word "slow mo"
6.Click on Search button
7. Results will be displayed on the screens
8. Select few motifs to create lomotif
9. Now, click on camera roll and again click on Motifs tab
10. Click cancel search option

Expected result: It should display selected results/motifs and when also it should again display all motif categories

Actual result: First motif category, i.e. "nicki minaj", does not display, It display "slow mo" word instead of nicki minaj category.

![img_0887](https://cloud.githubusercontent.com/assets/9691390/13606758/44de8b34-e573-11e5-8244-82edc458e40e.PNG)

![img_0888](https://cloud.githubusercontent.com/assets/9691390/13606756/44dc301e-e573-11e5-9833-6fc673de7e40.PNG)

![img_0889](https://cloud.githubusercontent.com/assets/9691390/13606759/44dff3f2-e573-11e5-868f-409ef02c9b3c.PNG)

![img_0890](https://cloud.githubusercontent.com/assets/9691390/13606760/44e28126-e573-11e5-8672-beb2d7ea49f5.PNG)

![img_0891](https://cloud.githubusercontent.com/assets/9691390/13606788/5ecd3874-e573-11e5-86fd-43de94c77319.PNG)

**Comment by xiuie** [comment]
I can replicate this..

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@a80b359887
