### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App Crashes - During two word search in Motif tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#209]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select Motif tab on Albums screen
4. Tap on Search box.
5. Type word "nicki"
6. Click on Search button
7. Results will be displayed on the screens
8. Again type the word "nicki minaj"
9. It will displays results / motifs
10. Click on cancel and again search the same word "nicki minaj"
11. Click on search button

Expected result: Results / motifs related to "nicki minaj" should be displayed

Actual result: Application Crashes

![img_0892](https://cloud.githubusercontent.com/assets/9691390/13609259/2c4086b2-e57e-11e5-8c13-3d156e7d7802.PNG)

![img_0893](https://cloud.githubusercontent.com/assets/9691390/13609261/2c45c640-e57e-11e5-8cca-8aeac92bab1e.PNG)

![img_0894](https://cloud.githubusercontent.com/assets/9691390/13609260/2c43796c-e57e-11e5-90f0-770290bec13c.PNG)

![img_0895](https://cloud.githubusercontent.com/assets/9691390/13609262/2c4794e8-e57e-11e5-92b9-afbd064709fb.PNG)

**Comment by tsukisa** [comment]
@benchang search result returns json with invalid pagination url, search term is not encoded
    next = "http://ditto.lomotif.com/v1/video/motif/search/?q=nicki minaj&page=2&g_offset=60";
    previous = "http://ditto.lomotif.com/v1/video/motif/search/?q=nicki minaj&page=2";

**Comment by tsukisa** [comment]
issue has been resolved
