### ISSUE TITLE
Refresh problem in My Music

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#21]
1. Open Lomotif App
2. Click on Start Button in Home Screen
3. Select Photos and videos
4. Add music files into My Music 
5. Goto My Music and check music files are added
6. But newly added music files are not showing but when we search with search option then it will show
   So here mainly its not getting refreshed.

![img_0120](https://cloud.githubusercontent.com/assets/5388768/12263975/48c2fbea-b959-11e5-9fc5-a8850af9bace.PNG)

![img_0121](https://cloud.githubusercontent.com/assets/5388768/12263972/3fee0366-b959-11e5-842e-9e2cd4da6638.PNG)

**Comment by benchang** [comment]
@xiuie can you try to replicate this one?
