### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App Crashes - During open created lomotif and try to export

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#210]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select 3-4 videos from Camera Roll
4. Select any song from My Music tab
5. Select and ON the filter
6. Select and ON the Enter a title (Enter any text)
7. Select added song and slight move it forward by dragging its waves
8. Create Lomotif
9. Save lomotif in local directory by clicking on Home button
10. Now, select and open previously created lomotif
11. Click on Export button

Expected result: Lomotif should be exported or should go to export screen

Actual result: Application Crashes

**Comment by xiuie** [comment]
I can't replicate this. @paulyangzhiwen Can you try?

**Comment by paulyangzhiwen** [comment]
also can't replicate (using iPhone 6s, OS version 9.2)

**Comment by xiuie** [comment]
@hiteshbheda Can you take a video of this please? Thanks!

**Comment by hiteshbheda** [comment]
@xiuie @paulyangzhiwen  Please find attached video as still i can replicate the same issue every time.

Video link

https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UcUxyUUlBaUp5MDQ

**Comment by xiuie** [comment]
@tsukisa Please refer to the attached video.

**Comment by hiteshbheda** [comment]
@xiuie  I can still replicate this bug now.

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce it for build [1.8.6] on iPhone 6 / iOS 9.3.1
