### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - App Crashes - During Sharing lomotif on Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#211]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any video or pictures from Camera Roll or from Motif tab
4. Select any song from My Music or Find Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select Facebook to share created lomotif

Expected: Lomotif should be shared on Facebook account

Actual: Application crashes

![img_0901](https://cloud.githubusercontent.com/assets/9691390/13626694/4ee1dc36-e5ea-11e5-9744-b530920a3588.PNG)

![img_0902](https://cloud.githubusercontent.com/assets/9691390/13626695/4eecf35a-e5ea-11e5-9b1a-9116051b8b84.PNG)

**Comment by xiuie** [comment]
I can't replicate this. @benchang Is this a permissions issue? If so, can close for now.

**Comment by hiteshbheda** [comment]
@xiuie @benchang  I can still replicate this. I don't know the problem. It may be caused because of permission issues.

**Comment by tsukisa** [comment]
@xiuie @hiteshbheda  this issue is caused by app running in development mode, Facebook is unable to authenticate users that is not in testers list
