### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2.1 - Unable to play shared Lomotif on Facebook Messanger  - After sharing lomotif to Facebook Messanger, unable to play video

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#212]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any pictures / video from Camera Roll
4. Select any song from My Music tab
5. Create Lomotif
6. Tap on export button, on top right corner
7. Select Facebook Messanger to share created lomotif
8. Select a contact from Messanger to share/send created lomotif
9. Send lomotif
10. After sent, click on play button to play shared lomotif
11. It will play lomotif
12. Back to contact list and again select the contact to whom you have shared lomotif
13. Click on shared lomotif to play

Expected: Shared Lomotif should be played after sharing on Facebook Messanger

Actual: Error - Unable to play shared lomotif in Facebook Messanger

![img_0903](https://cloud.githubusercontent.com/assets/9691390/13627008/01cf0574-e5ed-11e5-98ea-9a4a6a47e2b8.PNG)

![img_0904](https://cloud.githubusercontent.com/assets/9691390/13627009/01d4f2e0-e5ed-11e5-9ffb-284b34a7187e.PNG)

![img_0905](https://cloud.githubusercontent.com/assets/9691390/13627012/02504fc6-e5ed-11e5-9e59-fa97f14364e3.PNG)

![img_0906](https://cloud.githubusercontent.com/assets/9691390/13627010/022981c0-e5ed-11e5-9f9a-889029171b40.PNG)

![img_0907](https://cloud.githubusercontent.com/assets/9691390/13627011/022eb104-e5ed-11e5-96e4-0176ab703174.PNG)

**Comment by xiuie** [comment]
I can't replicate it. Also suspect this might be a messenger problem since you can play it at least once. Other messenger users with the same problem. https://www.facebook.com/help/community/question/?id=10202660038077004
