### ISSUE TITLE
[1.8.2] iPhone 5S / 8.4.1 - Albums - Motifs from search result appear on Camera Roll tab

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#213]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Switch to Motif tab on Albums screen
4. Enter search text 'water' and tap Search button
5. Sroll items on search results screen
6. Switch to Camera Roll tab when items are scrolling

Expected result: User sees default folders on Camera Roll tab (for example Facebook, Instagram, All Videos ...)

Actual result: Motifs from search result appear on Camera Roll tab

Video: [Recording.zip](https://github.com/Lomotif/lomotif-ios-issues/files/171001/Recording.zip)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@edd77d2249
