### ISSUE TITLE
[1.8.2] iPhone 5S / 8.4.1 - Create - Black Create screen appears (or application crashes) if user taps Apply button when song is loading

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#215]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Switch to Motif tab on Albums screen
4. Select any motif
5. Tap Apply button on Albums screen
6. Select Addele's Hello song
7. Tap Use Music button
8. Tap Apply button on Find Music screen when song is loading
9. Tap OK button on dialog

Expected result: Dialog 'CANCEL. Are you sure you want to proceed without adding music? ...' appears on Find Music screen

Actual result: Dialog 'CANCEL. Are you sure you want to proceed without adding music? ...' appears on black Create screen (or application crashes)

Video: [Recording.zip](https://github.com/Lomotif/lomotif-ios-issues/files/171039/Recording.zip)

**Comment by xiuie** [comment]
I can replicate this @tsukisa

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@5d757e7842
