### ISSUE TITLE
[1.8.2] iPad Mini / iOS 8.3 - Albums - Some motifs don't have thumbnails

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#216]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Switch to Motif tab on Albums screen
4. Enter search text 'water' and tap Search button
5. Sroll items on search results screen

Expected result: All motifs have thumbnails

Actual result: Some motifs don't have thumbnails

Video: [Recording.zip](https://github.com/Lomotif/lomotif-ios-issues/files/171043/Recording.zip)

**Comment by xiuie** [comment]
I can't replicate this on my iPhone 6/1.9.2

**Comment by tsukisa** [comment]
@xiuie possible caused by blocked domain, has added new domain to whitelist
Lomotif/lomotif-ios@ce91b3fddd554a4857effeede58b0c7ec71607c9
