### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Find Music - Application crash on choose item from suggested list.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#218]
Frequency: Every Time

Action:
1. Tap on Start button.
2. Tap on "Motif" on Albums page.
3. Search for any keyword. E.g. Romantic.
4. Make sure you get result for romantic. 
5. Scroll down result for 4-5 pages.
6. Go back and then again search for similar word where you can see multiple result in suggested list. E.g. Roman
7. Select anyone from displayed list.

Expected Result: It should open result for selected list.

Actual Result: Application is crash.
[Application Crash.zip](https://github.com/Lomotif/lomotif-ios-issues/files/172356/Application.Crash.zip)

**Comment by Dipamit** [comment]
Attaching Video for same.

[Crash on search.zip](https://github.com/Lomotif/lomotif-ios-issues/files/172455/Crash.on.search.zip)

**Comment by xiuie** [comment]
I can replicate this on my iPhone 6 / 9.2

**Comment by hiteshbheda** [comment]
I can't replicate this in build [1.7.12] with iPhone 6 / iOS 9.3

There is now search bar available in new released build. So i can't move forward from step 3.

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1
