### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Create - Error is displayed when doing On/Off watermark option from settings.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#219]
Frequency: Every Time

Action:
1. Open any existing project from main screen. You can also create new one.
2. Go to Main create page.
3. Check that you can see Watermark option.
4. Do On/Off 1-2 times.

Expected Result: It should not display any error pop-up.

Actual Result: It showing error pop-up.
[Watermark Error.zip](https://github.com/Lomotif/lomotif-ios-issues/files/172476/Watermark.Error.zip)

**Comment by xiuie** [comment]
As mentioned in tester's instructions, please do not log this issue as the testing version will show this error. It will no longer be an error once you can connect to the App Store.
