### ISSUE TITLE
Music is playing when we click second time before playing music in Find Music

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#22]
1. Open Lomotif App
2. Click on Start Button in Home Screen
3. Select Photos and videos
4. Select any of the music from the list
5. Click on 'Use 30 Seconds preview' and click again before playing music then preview option gets closed. But music will start playing.

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@fd42c1e303fa76125b78f20ef9c2379ed4bc8b60
