### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Create - Sticker displayed on video even after Off it.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#220]
Frequency: Every Time

Action:
1. Choose any project from existing.
2. Keep Sticker ON and choose any sticker.
3. Check that sticker is displayed at bottom left corner.
4. Save it and then again open same project.
5. Make sticker OFF.

Expected Result: Sticker should not be displayed on video when it's off.

Actual Result: Sticker remains on video even after make it OFF.
[Sticker Off.zip](https://github.com/Lomotif/lomotif-ios-issues/files/172496/Sticker.Off.zip)

**Comment by xiuie** [comment]
I can replicate this.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@1f2be6b
