### ISSUE TITLE
[1.8.1] iPhone 6 / 9.2 - Create - Watermark displayed on video even after Off it.

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#221]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Click on Settings
3. Click on Restore purchases
4. Tap START button
5. Switch to Motif tab on Albums screen
6. Select any motif
7. Select Music
8. Turn off watermark

Note: I have previously purchased watermark removal.

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@1f2be6b
