### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Create- All music started at same time when open application after minimize.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#222]
Frequency: Every Time

Action:
1. Make sure you have two projects created in list with different music.
2. Open any single video then minimize the application.
3. Resume the application and check the page.

Expected Result: It should play only single music, when you are at home page it should not play any music.

Actual Result: It starts playing two projects music at same time. Same issue when you on home page.
[Double Sound.zip](https://github.com/Lomotif/lomotif-ios-issues/files/172552/Double.Sound.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can't replicate this in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Every time

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1
