### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Create- Font style is changed when you come back to create page.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#223]
Frequency: Every Time

Action:
1. Create any project with different font style.Check that preview of Font is displayed.
2. Save and go to Home page.
3. Open same project again and check selected Font style and actual text style.

Expected Result: Font style should be remains as per selected font style.

Actual Result: Font style selection remains but actual font style gets changed to default one.

**Comment by xiuie** [comment]
I can't replicate this @Dipamit

**Comment by hiteshbheda** [comment]
@xiuie I can't replicate this in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Every time

![img_1056](https://cloud.githubusercontent.com/assets/9691390/14040781/ac7ca2ce-f290-11e5-8946-e43a0343dda9.PNG)

![img_1057](https://cloud.githubusercontent.com/assets/9691390/14040779/ac69e8fa-f290-11e5-8cfa-a88e291f8834.PNG)

![img_1058](https://cloud.githubusercontent.com/assets/9691390/14040780/ac76e276-f290-11e5-910d-52b3f2dfc20c.PNG)

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by 87Swati** [comment]
I can't reproduce it on build 1.8.6 on iPadAir/ iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce it for build [1.8.7] on iPhone 6 / iOS 9.3.1
