### ISSUE TITLE
[1.8.2] iPhone 6 / 9.2 - Create Alogorithm - When 1 slowmo video is selected, exported video is too short 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#225]
Frequency: Every Time

Action:
1. Press Start
2. Select 1 x slow mo video (e.g. slow mo vid shot for 5 secs = actual playback length 28secs )
3. select any music
4. Note preview and exported video is too short 

Expected Result: Video fills out 15secs unless Duration is adjusted

Actual Result: Video is 5secs

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@046a28a15a
