### ISSUE TITLE
[1.7.10] iPhone 6 / 9.2.1 - App Crashes - Export lomotif 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#227]
Frequency: Once
Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Motifs from Motif tab
4. Add any song from Find Music
5. Now Add stickers
6. Apply filter value ON
7. Apply some text on the screen
8. Now, change the song and select new song from Find Music tab
9. Slightly forward the song by dragging audio waves
10. Click on export button (Right top corner)
11. Click on "No Thanks" button

Expected result: Created lomotif should be saved to camera roll when clicked on "No Thanks" button on export screen

Actual result: Application Crash

**Comment by xiuie** [comment]
Happened to me twice out of 5 tries.

However for step 11, I clicked "Export".

Try resetting cache and export count and restart before reproducing.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this bug in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Tried minimum 25 to 30 times with reloading lomotif as well with clicking on cancel button. Not crashing now.

**Comment by tsukisa** [comment]
@xiuie issue resolved with commit Lomotif/lomotif-ios@4ab7b941e8
