### ISSUE TITLE
iPhone 6/9.1- Loding a video - On loading a video is causing app to crash

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#23]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. Create a movie
5. Go back to app home 
6. Select the movie for play
7. Press app home button before movie loads 
8. Press yes to Go back to home 
9. Wait for 5 secs
Application crashed
When a user creates a movie and selects a movie to play and immediately go back to home before loading of the movie. It goes back to home but crashes after few seconds

Expected Result: User should navigate to app home screen without crash

Actual Result: App crashing all the time

**Comment by benchang** [comment]
can't replicate on build 1.7.2
