### ISSUE TITLE
[1.7.10] iPhone 6 / 9.2.1 - App Crashes - During click on added motif while playing

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#231]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any created lomotif
3. Now, add few motifs from any Motif category
4. Click on newly added motif

Expected result: Clicked / Selected motif should be highlighted

Actual result: Application Crashes

![img_1017](https://cloud.githubusercontent.com/assets/9691390/13944720/a6f45de8-f02d-11e5-99e5-57f1e6e16eba.PNG)

![img_1018](https://cloud.githubusercontent.com/assets/9691390/13944719/a6e56414-f02d-11e5-9a53-7e24943eef92.PNG)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa The same issue can be replicated when i add any pictures / videos even from Camera Roll and select / click on any item / motif / picture / video (not only last added, but applicable to all).

Frequency: Every time for all

**Comment by xiuie** [comment]
Thanks @hiteshbheda This is important. Only closing this because I wrote comments in 235 already.
