### ISSUE TITLE
[1.7.10] iPad Mini / iOS 8.3 - Find Music - Application crashes when user uses only spaces in search text

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#234]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button
3. Select any picture or video on Albums screen
4. Tap apply button on Albums screen
5. Switch to My Music tab on Find Music screen
6. Enter some spaces into search field and try to search

Expected result: User sees error message that no search result

Actual result: Application crashes

Video: [Recording35.zip](https://github.com/Lomotif/lomotif-ios-issues/files/184592/Recording35.zip)

**Comment by hiteshbheda** [comment]
@vysohanych  I can replicate this every time with iPhone 6 / iOS 9.2.1

**Comment by xiuie** [comment]
@vysohanych @hiteshbheda Can you replicate it now?

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this issue in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Every time
