### ISSUE TITLE
[1.7.10] iPad Mini / iOS 8.3 - Create - Application crashes when user taps on different clips on Create screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#235]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open any exists lomotif with many motifs [Correction: Open any project]
3. Tap on different motifs on Create screen [Correction: Tap on ANY clip]

Expected result: Motifs should be switched

Actual result: Application crashes

Video: [Recording45.zip](https://github.com/Lomotif/lomotif-ios-issues/files/184944/Recording45.zip)

**Comment by xiuie** [comment]
@tsukisa I can replicate this too all the time.

**Comment by xiuie** [comment]
Duplicate of #231

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@626a770208
