### ISSUE TITLE
[1.7.10] iPad Mini / iOS 8.3 - Albums / Find Music - Ambiguous behavior with swipe in the application

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#237]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Select any motif on Album screen
4. Tap apply button on Albums screen
5. Switch to My Music tab from Find Music tab during swipe -> User can switch to My Music tab
6. Switch to Find Music tab from My Music tab during swipe -> User can switch to Find Music tab
7. Switch to Albums screen from My Music screen during swipe -> User can switch to Albums screen
8. Try switch to My Music screen from Albums screen during swipe -> User can not switch to Albums screen
9. Try switch to Camera Roll tab from Motif tab during swipe -> User can not switch to Camera Roll tab
10. Try switch to Motif tab from Camera Roll tab during swipe -> User can not switch to Motif tab

Expected result: User can switch to all screens and tabs during swipe or user can not switch to any screen/tab during swipe

Actual result: User can switch to some tabs

Video: [Recording47.zip](https://github.com/Lomotif/lomotif-ios-issues/files/185009/Recording47.zip)

**Comment by xiuie** [comment]
@pmtheint UX issue for consideration. Please close after the necessary.

**Comment by hiteshbheda** [comment]
@xiuie @pmtheint I can replicate this issue in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Every time

**Comment by pmtheint** [comment]
Noted and logged.
