### ISSUE TITLE
[1.7.10] iPhone 6 / iOS 9.2 - Video - Videos and photos disappeared on swipe.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#238]
Frequency: Every Time

Action:
1. Tap on Start.
2. Make sure you have Photos and Videos in Camera Roll.
3. Tap on Camera Roll or All Photos/ All Videos.
4. Swipe down from screen.

Expected Result: It should not clear the list.

Actual Result: All videos/ photos list cleared.

Note: I can reproduce this issue on iPhone-5 with 8.2.

![photo swipe-1](https://cloud.githubusercontent.com/assets/17335200/13976026/a1db0636-f0e1-11e5-8680-eab546cb0746.PNG)
![photo swipe-2](https://cloud.githubusercontent.com/assets/17335200/13976025/a1d94ac6-f0e1-11e5-8e57-40f9b835b4cd.PNG)
![video swipe-1](https://cloud.githubusercontent.com/assets/17335200/13976027/a1e716ba-f0e1-11e5-894b-fe480c0740fd.PNG)
![video swipe-2](https://cloud.githubusercontent.com/assets/17335200/13976028/a1eda462-f0e1-11e5-8194-9034a40dd045.PNG)

**Comment by hiteshbheda** [comment]
I can't replicate it with iPhone 6 / iOS 9.2.1

**Comment by hiteshbheda** [comment]
@xiuie I can't replicate this in build [1.7.12] with iPhone 6 / iOS 9.3

Frequency: Twice

**Comment by Dipamit** [comment]
Not able to replicate this issue in new build[1.7.12 ] with iPhone 5/8.3

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3
