### ISSUE TITLE
[1.7.10] iPhone 6 / iOS 9.2 - Export- "Test Request" pop-up on trying to export any video.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#239]
Frequency: Every Time

Action:
1. Choose any created Lomotif.
2. Tap on Export and check the page..

Expected Result: Test request pop-up which can be used for Debug the code should not be there for testing build. Safe side is to remove it from testing build so that will not be attach by mistake on production build as well.

Actual Result: Test Request pop-up is displayed which may be used by developer to debug the code.
![test request](https://cloud.githubusercontent.com/assets/17335200/13976069/1cbfe844-f0e2-11e5-8f8b-7390742604dc.PNG)

**Comment by tsukisa** [comment]
@xiuie the dialogue is not removed in dev build

**Comment by hiteshbheda** [comment]
I can replicate the same every time with iPhone 6 / iOS 9.2

**Comment by xiuie** [comment]
@tsukisa Now worries. This only appears in dev since I'm testing it.
