### ISSUE TITLE
[1.7.10] iPhone 6 / 9.2.1 - App Crashes - Export lomotif 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#240]
Frequency: Once

Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Motifs from dance category from Motif tab
4. Go to My Music
5. Search for "Work" word
6. Select any song from searched results
7. Click on '+' sign to add another motif
8. Add any motif from any category of motifs
9. Create lomotif
10. Click on Export button

Expected result: Created lomotif should be Exported or should display social media sharing page

Actual result: Application Crash

**Comment by Dipamit** [comment]
Not able to Replicate this issue on iPhone 5 IOS 8.3

**Comment by xiuie** [comment]
Not able to replicate on iPad Mini/8.1
