### ISSUE TITLE
[1.7.10] iPhone 5/ 8.3 - Application crash on tapping selected video.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#241]
Frequency : Every time

Action:
1. Open application and tap on any created Lomotif video.
2. Tap on any playing video next to add album  while running video.

Expected result: It should jumps to selected video.

Actual result: Application crash.

**Comment by xiuie** [comment]
@tsukisa Ben and I can replicate this some time.. And Ben suspects this is what is causing the most problems (related to the music loop)

**Comment by tsukisa** [comment]
@xiuie is this lomotif project crash?

**Comment by xiuie** [comment]
Yes!

Loh Xiu Hui  
Co-Founder, Lomotif
Mobile: +65 96863007
Email: xiu@lomotif.com
Website: www.lomotif.com

**Comment by tsukisa** [comment]
Duplicate of #235
The issue is caused by opening a project that contains a song
