### ISSUE TITLE
[1.7.12] iPhone 6 / 9.3 - Error 404 / Not Found - Terms of Use & Privacy in Settings

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#242]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Settings button (Top right corner at Home screen)
3. Tap on Terms of Use & Privacy Policy

Expected result: Terms of Use & Privacy Policy should be displayed

Actual result: Error 404 - Not found

![img_1052](https://cloud.githubusercontent.com/assets/9691390/14039405/e75080be-f281-11e5-9878-6236e00fb184.PNG)

**Comment by Dipamit** [comment]
Able to replicate this issue on iPhone 5/8.3 for Lomotif (1.7.12)

**Comment by vysohanych** [comment]
@xiuie @tsukisa I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue on build version [1.8.4] on iPhone 6 / iOS 9.3.1
