### ISSUE TITLE
[1.7.12] iPad Mini / iOS 8.3 - Create - Music doesn't play on Create screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#247]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Open any existing lomotif with song or create a new lomotif with song

Expected result: Music should play on Create screen

Actual result: Music doesn't play on Create screen

Video: [Recording #16.mp4.zip](https://github.com/Lomotif/lomotif-ios-issues/files/189784/Recording.16.mp4.zip)

**Comment by xiuie** [comment]
@vysohanych Can you try turning on your ringer? Do you hear the music now?

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa @vysohanych I can't replicate it neither with opening existing lomotif nor by creating new one in iPhone 6 / iOS 9.3

Tried 3 - 3 times each by creating new lomotif and opening existing lomotif

**Comment by vysohanych** [comment]
I can't reproduce this issue now. You can close it.

**Comment by tsukisa** [comment]
unable to reproduce, case closed
