### ISSUE TITLE
[1.7.12] iPad Mini 2 / iOS 9.2.1 - Export - Error 11847 appears when user starts export on Create screen and moves the application to background

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#248]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open any existing lomotif or create a new lomotif
3. Tap export button on Create screen
4. Move the application to background when lomotif is exporting
5. Move the application from background

Expected result: User sees share screen

Actual result: Error 11847 appears on Create screen

Video: [Recording #56.zip](https://github.com/Lomotif/lomotif-ios-issues/files/190165/Recording.56.zip)

**Comment by xiuie** [comment]
If nothing can be done about this just close it. :) @tsukisa

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa @vysohanych I can't replicate this with iPhone 6 / iOS 9.3

I have tried both options: 1. create lomotif and export and 2. open existing lomotif and export

**Comment by tsukisa** [comment]
@xiuie this is iOS limitation, opengl cannot run on background
