### ISSUE TITLE
[1.7.12] iPhone 6 / 9.3 - App Crashes - Swapping between videos by disabling wi fi

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#249]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Motifs from Motif tab
4. Add any song from Find Music
5. Save lomotif on local directory
6. Now, Disable wi fi / Internet
7. Again start lomotif 
8. Open previously created lomotif
9. Click on any motif / frame

Expected result: Frame should be selected in opened lomotif

Actual result: Application Crashes

![img_1069](https://cloud.githubusercontent.com/assets/9691390/14057850/90327f4c-f332-11e5-8540-959121766e45.PNG)

![img_1070](https://cloud.githubusercontent.com/assets/9691390/14057851/90412272-f332-11e5-996d-ce45f5d5696b.PNG)

![img_1071](https://cloud.githubusercontent.com/assets/9691390/14057849/902d748e-f332-11e5-89cb-138f72a53e05.PNG)

**Comment by xiuie** [comment]
@hiteshbheda Do you have a crash log for this?

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Yes, Please find attached crash logs for this issue.

[Crash logs #249](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4URnBvVUVxRXFnQzg)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.4] on iPhone 6 / 9.3.1

**Comment by vysohanych** [comment]
@xiuie @tsukisa I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3
