### ISSUE TITLE
[1.7.12] iPad Mini 2 / iOS 9.2.1 - Find Music - Songs don't appear when user cancel searching

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#250]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on home screen
3. Switch to Motif tab on the Albums screen
4. Select any motif
5. Tap apply button on Albums screen
6. Enter search text when no search result and tap search button
7. Tap cross button and then Cancel button on search field

Expected result: User sees all list of song

Actual result: User don't see any song. Songs appears only after pull down to refresh

Video: [Recording #60.zip](https://github.com/Lomotif/lomotif-ios-issues/files/190651/Recording.60.zip)

**Comment by xiuie** [comment]
@pmtheint I suspect this happens when there's no results. May need some sort of message. "Oops! We couldn't find something that matches "PPCDYDJC". Please try again."

**Comment by pmtheint** [comment]
It's more of a problem of users not being able to go back to the top 20 list. Even with valid search result, there's no way to return to that list. Will work on a UX fix.
