### ISSUE TITLE
[1.7.12] iPad Mini 2 / iOS 9.2.1 - Albums - Empty folder present on the list of motifs

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#251]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on home screen
3. Switch to Motif tab on the Albums screen
4. Sroll down the current screen

Expected result: Empty folder shouldn't present in list of motifs

Actual result: Under winter sport folder present empty folder without label

Video: [Recording #61.zip](https://github.com/Lomotif/lomotif-ios-issues/files/190652/Recording.61.zip)

**Comment by xiuie** [comment]
@benchang Any idea what causes this? If so, let me then can close this. Thanks!

**Comment by hiteshbheda** [comment]
@xiuie @benchang I can replicate this issue on iPhone 6 / iOS 9.3.

Please find attached screenshots.

![img_1098](https://cloud.githubusercontent.com/assets/9691390/14087673/ca821a0a-f548-11e5-913f-d2de570c5e67.PNG)

![img_1099](https://cloud.githubusercontent.com/assets/9691390/14087674/ca8515ac-f548-11e5-8ae1-5e4229ca28f3.PNG)

**Comment by hiteshbheda** [comment]
@xiuie @benchang I can reproduce this issue on build [1.8.4] on iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @benchang I can reproduce this issue on build [1.8.6] on iPhone 6 / iOS 9.3.1
