### ISSUE TITLE
[1.7.12] iPad Mini 2 / iOS 9.2.1 - Sharing screen - Song is playing when user returns to application when preparing export via twitter on sharing screen

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#252]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open any exists lomotif or create a new lomotif with song
3. Tap export icon on Create screen
4. Tap Twitter icon on sharing screen -> Appears Share dialog via twitter
5. Move the application to background
6. Move the application from background

Expected result: Song shouldn't play automatically when user move the application from background if is opened sharing dialog via twitter on sharing screen

Actual result: Song is automatically playing when user move the application from background when is opened sharing dialog via twitter on sharing screen

Video: [Recording #63.zip](https://github.com/Lomotif/lomotif-ios-issues/files/190664/Recording.63.zip)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa  I can replicate this issue on iPhone 6 / iOS 9.3.

It's not only happening with twitter but also happen with whatsapp, Facebook, Messanger, Instagram and Message. 

When application switch from lomotif to background and again from background to main screen, it automatically plays audio which we have inserted.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this issue for build [1.8.4] on iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by tsukisa** [comment]
@xiuie this is fixed with commit Lomoti/lomotif-ios@dbbad8a0799ce7aa7407b86a1bdf8ef2f641957b
