### ISSUE TITLE
[1.7.12] iPhone 6 / iOS 9.2 - Create - Not able to delete last image.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#254]
Frequency: Every Time

Action:
1. Select any created Lomotif.
2. Hold images/ videos of Lomotif and drag it to - sign to remove all.
3. Try for all displayed images.

Expected result: If we are no allowing user to remove last image, no need to show - sign for user.

Actual result: It is not allowing to delete last item. 
[Last Item Delete.zip](https://github.com/Lomotif/lomotif-ios-issues/files/191062/Last.Item.Delete.zip)

**Comment by xiuie** [comment]
@pmtheint See above suggestion. For consideration. Please close after reading.

**Comment by pmtheint** [comment]
Not an issue to me but noted for improvements.
