### ISSUE TITLE
[1.7.12] iPad Mini / iOS 8.3 - Albums - Icons for motif's folders don't appear after 'winter sports' folder

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#256]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Switch to Motif tab on Albums screen
4. Scroll the page down

Expected result: All folders on Motif tab have icons

Actual result: Folders after 'winter sports' folder don't have icons

![img_1127](https://cloud.githubusercontent.com/assets/3593359/14081036/28b1a6f0-f511-11e5-9c63-47b14afb1ce1.jpg)

**Comment by hiteshbheda** [comment]
@xiuie @vysohanych I can replicate it on iPhone 6 / iOS 9.3

Frequency: Every time

![img_1095](https://cloud.githubusercontent.com/assets/9691390/14086129/23f91db6-f541-11e5-91d4-fda1f1f27b76.PNG)

![img_1096](https://cloud.githubusercontent.com/assets/9691390/14086130/23fff050-f541-11e5-8c43-c148ffc89f12.PNG)

**Comment by xiuie** [comment]
@vysohanych Thanks but we are removing the album art soon.
