### ISSUE TITLE
[1.7.12] iPhone 6 / 9.3 - WhatsApp error - While exporting at export page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#257]
Frequency: Every Time

Action:
1. Open any created lomotif
2. Click on export button at top right corner
3. Select WhatsApp icon to share created lomotif

Expected Result: Lomotif should be shared on WhatsApp 

Actual Result: Gives error to open WhatsApp from mobile home screen before sharing lomotif through Lomotif app

![img_1104](https://cloud.githubusercontent.com/assets/9691390/14133446/b4cb0968-f66c-11e5-88b0-68ceaf0f866e.PNG)

**Comment by xiuie** [comment]
Thanks @hiteshbheda For every build, this and subsequent, can you check that you can share to the following platforms: Instagram, Text Message, Twitter, Email, Facebook without errors?

**Comment by hiteshbheda** [comment]
@xiuie Thanks Xiuie to encourage me.

Yes, i have tried on all platforms like instagram, Twitter, message and Email. It works correctly.

But on Facebook, it continue crashes as you suggested last time due to No Rights on facebook by Lomotif app.

Requesting you to authorize me on Facebook, so i can test it correctly.

**Comment by xiuie** [comment]
@tsukisa Can authorize the testers for FB sharing on dev builds pls?

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Thanks Xiuie. I wanted to be authorize on FB as during sending lomotif to messenger, lomotif screen displays "Unable to Play" error.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue now for build [1.8.4] on iPhone 6 / iOS 9.3.1
