### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - Search audio Bug - Wrong result for audio search

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#258]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select any picture from camera roll
4. Click on Apply button on top right corner
5. On Find Music tab, tap on search bar 
6. Search for the keyword "be"
7. Check the result in search list

Expected result: Audio songs containing the word "be" should be available / displayed

Actual result: Wrong search result - It also gives the first result as "Rude" song in which no "be" keyword available anywhere.

![img_1525](https://cloud.githubusercontent.com/assets/9691390/14390770/53f01dc4-fdd6-11e5-9169-8d197ca40386.PNG)

**Comment by xiuie** [comment]
@hiteshbheda Will close this one as I suspect the alogorithm is taking into account spelling and associations (not just what you see in the titles), but if you have more examples, please flag it out as it is useful to note. Thanks.
