### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - Watermark Bug - Disabling or Enabling "Enter a Title" value automatically ON (Enable) the Lomotif watermark

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#259]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any created lomotif
3. Click on Setting tab at bottom of the screen
5. Disable watermark
6. Click on Home Button and save the lomotif
7. Again open the same lomotif
8. Now, click on "Enter a Title" tab
9. Enter any value as a text and click on Done from keyboard
10. Observe the playing screen.

Expected result: When entering value in "Enter a Title" tab it should only display on the lomotif playing screen without Lomotif watermark

Actual result: Entering value in "Enter a Title" tab automatically on (enable) the Lomotif watermark

**Comment by xiuie** [comment]
@hiteshbheda I can't replicate this. 

Not sure if I understand the problem correctly.

**Comment by vysohanych** [comment]
I can't reproduce it on 1.8.4 on iPad mini (iOS 8.3)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce it now
