### ISSUE TITLE
[1.6.8] iPhone 5s/9.1 - Login failed error message displayed when user cancel login authentication.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#26]
Frequency: Always

Action:
1. Launch the app.
2. Tap on settings.
3. Tap on linked accounts.
4. Tap on any social sites name.
5. Tap on cancel.
6. Check whether login failed error message display or not.

Expected Result: Login failed error message displayed when user cancel login authentication.

Actual Result: There is no confirmation message come when user share the Lomotif to any social sites.

![login_error](https://cloud.githubusercontent.com/assets/9127217/12326197/513f970e-baf5-11e5-9655-9aa85846a3f1.png)

**Comment by xiuie** [comment]
Works as designed? I don't quite understand this. It failed because you cancelled log-in. You're not sharing your Lomotif video on this page, just linking accounts.

**Comment by benchang** [comment]
Invalid
