### ISSUE TITLE
[1.8.4] iPad Mini / 9.3.1 - Shake to shuffle -Doesn’t work after you use the “Add Videos” button in the Create screen

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#260]
Frequency: Every time

Action:
1. Launch Lomotif
2. Select Motifs
3. Select Music
4. Shake to shuffle (it works)
6. Tap pink “Add clips” button
7. Select more Motifs
8. Shake to shuffle

Expected result: Clips are reordered

Actual result: Clip order does not change.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce it every time on iPhone 6 / 9.3.1

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@fc8131593f2811a966d81aa7e9d7aa4130070942
