### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - Time frame bug (15s / 30s) - Switching between 15s / 30s time from setting

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#261]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few pictures from Camera roll
4. Select audio from My Music
5. Go to bottom of the screen and expand setting tab by clicking on it
6. Drag the arrow to 30 second from 15 second
7. Now, click on Home button and save the lomotif
8. Again open that lomotif
9. Click on setting tab, select 30s option
10. Click on Home button and save the lomotif again
11. Open that lomotif again
12. Click on setting tab and observe time

Expected result: 
1. Time frame should be 30s Or 
2. When we switch the option from 15s to 30s, it should be disabled.

Actual result: When we select switch from 15s to 30s (1st option to 2nd option), time frame created for only 15 seconds

![img_1547](https://cloud.githubusercontent.com/assets/9691390/14422072/77926f5c-fff2-11e5-9b4e-750bf568e87b.PNG)

![img_1548](https://cloud.githubusercontent.com/assets/9691390/14422073/779ad16a-fff2-11e5-9333-4ffd533919e3.PNG)

![img_1549](https://cloud.githubusercontent.com/assets/9691390/14422076/77c0d3d8-fff2-11e5-9d53-259bd03229bc.PNG)

![img_1550](https://cloud.githubusercontent.com/assets/9691390/14422074/77b9476c-fff2-11e5-917b-6a4522de5fd5.PNG)

![img_1551](https://cloud.githubusercontent.com/assets/9691390/14422075/77ba3078-fff2-11e5-9975-beb4716835a5.PNG)

![img_1552](https://cloud.githubusercontent.com/assets/9691390/14422078/77dbe718-fff2-11e5-8170-c4e108f5f8a7.PNG)

![img_1553](https://cloud.githubusercontent.com/assets/9691390/14422077/77c4f242-fff2-11e5-999a-3b623c91b5cc.PNG)

![img_1554](https://cloud.githubusercontent.com/assets/9691390/14422070/77776b4e-fff2-11e5-8317-8ee12fd52a42.PNG)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@ad1f5844de2f30eb8aa87a525c821bf6583c6152
