### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - App crash during sharing on Twitter - Without Internet connection share lomotif on Twitter

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#262]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few motifs from any category of Motif
4. Select any audio from My Music or from Find Music
5. Enable stickers and then again disable it.
6. Enable Filters
7. Enable "Enter a Title" and write any name
8. Disable Internet (Disable wifi or mobile data)
9. Click on Export button from Right Top corner and select "Yes" to export your Lomotif
9. Click on Twitter 
10. Observe the screen

Expected result: As internet is disabled, expert and sharing on Twitter should display Error Message

Actual result: Error message is displayed for a second and then immediately App crash

**Comment by vysohanych** [comment]
I can't reproduce it on 1.8.4 on iPad mini (iOS 8.3)

**Comment by hiteshbheda** [comment]
@xiuie @jpaulo1205 I can still replicate this issue.

Please have a look into attached video. It would be helpful to identify problem.

[Twitter - App Crash](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UZWc0SnhRY3d6TE0)

**Comment by tsukisa** [comment]
@hiteshbheda still not able to reproduce, do you have crash log for this?

**Comment by hiteshbheda** [comment]
@tsukisa @xiuie @jpaulo1205 Please find attached crash logs for it.

[Twitter Crash logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UQWF4OFJSZVVybVk)

Currently, I'm unable to reproduce it for build [1.8.7] on iPhone 6 / iOS 9.3.1

I suspect that at that time, i might not have authorized Twitter for Lomotif for testing purpose. Request you to please have insight into attached crash logs.
