### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - Stickers Bug  - Once apply stickers and then disable it does not affect to lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#263]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few pictures from Camera roll
4. Select audio from My Music
5. On the stickers and select any one
6. Click on Home button and save the created lomotif
7. Open the previously saved lomotif
8. Disable (OFF) the stickers
9. Observe the effect on the screen

Expected result: Stickers should be disabled when disable (OFF) it from stickers tab

Actual result: Disable stickers tab not working properly.

![img_1557](https://cloud.githubusercontent.com/assets/9691390/14434318/c7f7a1b4-002f-11e6-97c9-0f70c7fa5939.PNG)

![img_1558](https://cloud.githubusercontent.com/assets/9691390/14434320/c8e2e2f0-002f-11e6-9b44-b765487548c1.PNG)

![img_1560](https://cloud.githubusercontent.com/assets/9691390/14434319/c7f7110e-002f-11e6-94aa-b311db922c30.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on 1.8.4 on iPad mini (iOS 8.3)
