### ISSUE TITLE
[1.8.4] iPad Mini / iOS 8.3 - “Too few video clips” message shown wrongly 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#268]
Frequency: Every Time

Action:

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Select any picture/photo on the Albums screen
4. Tap apply button on the Albums screen
5. Tap apply button on the Find Music screen
6. Skip adding music
7.Export video

Expected result: Video with 15secs of a still image is exported
Actual result: “Too few video clips” message shown

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this on iPhone 6 / 9.3.1

**Comment by vysohanych** [comment]
@xiuie @tsukisa I can't reproduce it on iPad mini iOS 8.3

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3 with Lomotif [1.8.4]

**Comment by tsukisa** [comment]
@xiuie problem found, it will appear when there is photo. Already fixed

**Comment by hiteshbheda** [comment]
@tsukisa @xiuie I can still replicate this issue for photos only during exporting
