### ISSUE TITLE
[1.8.4] iPhone 6 / 9.3.1 - Rating Popup Bug - Drag cursor to the left end or right end fast, it will hang the popup window

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#269]
Frequency: Every time

Action:
1. Launch Lomotif
2. Popup window will appear
3. Now drag the cursor either at the left end or at right end with single fast movement
4. Try to move cursor at different position

Expected result: Cursor should move between left end to right end at any position

Actual result: Once reached at left end or at right end quickly, cursor is unable to move further

[Popup Bug video](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UZlNrV3huTk8yWHM)

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3

**Comment by xiuie** [comment]
Thanks @hiteshbheda I'm testing something. This does not appear on the live build.

**Comment by hiteshbheda** [comment]
@xiuie Thanks for update..!!!
