### ISSUE TITLE
iPhone 6 9.1 - There is no confirmation message comes when user saves a movie

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#27]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. Tap right mark (save button) on top right corner
There is no confirmation message comes when user saves a video

Expected Result: There should be confirmation message pop out regarding movies saved

Actual Result: There is no confirmation message pop out

**Comment by benchang** [comment]
@casey There should be toast notification after export saying "Lomotif saved to Camera Roll"

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.4 on iPad mini iOS 8.3
