### ISSUE TITLE
[1.8.4] iPad Mini / iOS 8.3 - Rating popup dialog - User can tabs on SUBMIT button when it is disabled

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#270]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap SUBMIT button on the home screen

Expected result: Rating popup dialog still shown. User can't tab on disabled SUBMIT button

Actual result: Rating popup dialog disappears

Video: [Recording #26.mp4.zip](https://github.com/Lomotif/lomotif-ios-issues/files/217317/Recording.26.mp4.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce it on iPhone 6 / 9.3.1

**Comment by xiuie** [comment]
Thanks @vysohanych I'm testing something. Please ignore the pop up this time.
