### ISSUE TITLE
[1.8.5] iPad 2 / iOS 9.3.1 - Export - Created lomotif doesn't come to mail

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#273]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Open one of exists lomotif or create new lomotif
3. Tap export button on lomotif screen
4. Tap email button on sharing screen
5. Enter your valid email and tap Send button
6. Wait some hours

Expected result: User receives the email with lomotif

Actual result: Created lomotif doesn't come to mail

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this for build [1.8.5] on iPhone 6 / iOS 9.3.1

I'm receiving mail with proper content of created lomotif every time.

[Images](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UdnlCTTZ4U3A1a0E)

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.6]

**Comment by 87Swati** [comment]
I am not able to reproduce this issue on iPadAir/9.3.1 for build [1.8.6]

**Comment by xiuie** [comment]
@vysohanych Is this still a bug for you?

**Comment by vysohanych** [comment]
@xiuie No, I can't reproduce it on build 1.8.7 on iPad 2 iOS 9.3.1.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.7] on iPhone 6 / iOS 9.3.1
