### ISSUE TITLE
[1.8.5] iPad 2 / iOS 9.3.1 - UI Issue/Albums/Find Music - Search box should stay in place

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#274]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Switch to Motif tab on the Albums screen
4. Scroll the current screen down and observe that search box disappears
5. Select any motif and tap apply button on the Albums screen
6. Scroll the Find Music screen down and observe that search box disappears

Expected result: Search box should always stay in place

Actual result: Search box disappears after scrolling

Video: [Recording #16.zip](https://github.com/Lomotif/lomotif-ios-issues/files/221584/Recording.16.zip)

**Comment by xiuie** [comment]
@pmtheint Hmm quite a good UX suggestion

**Comment by pmtheint** [comment]
That's a good one. I'll put it on Asana.
