### ISSUE TITLE
[1.8.6] iPad 2 / iOS 9.2.1 - Lomotif successfully exported dialogue needs to have a longer delay

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#276]
[1.8.6] iPad 2 / iOS 9.2.1 - Lomotif successfully exported dialogue needs to have a longer delay

Frequency: Every Time

Action:
1. Launch Lomotif
2. Create Lomotif
3. Export Lomotif

Expected result: User sees that it’s been successfully exported (at least 1 sec?)

Actual result: User can’t see that it’s been exported if they blinked

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1.

It is exported but it does exporting process every time and takes around 3 to 4 secs

**Comment by Dipamit** [comment]
[1.8.6] iPhone 5/8.6 Exporting function is working but Not receiving any dialog for exporting lomotif successfully

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by tsukisa** [comment]
@xiuie delay is added before sharing screen is shown to user
