### ISSUE TITLE
[1.8.6] iPhone 6 / 9.3.1 - Rating Pop-up menu Bug - No submit button on Rating popup menu

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#277]
Frequency: Every time

Action:
1. Launch Lomotif
2. Rating popup menu will appear on the screen
3. Observe menu and try to submit your feedback

Expected result: Feedback should be submitted through submit button

Actual result: No submit button available in Rating popup menu

![img_1684](https://cloud.githubusercontent.com/assets/9691390/14584917/7d43b288-047c-11e6-8952-9f4b5fbfc48b.PNG)

**Comment by xiuie** [comment]
Noted @hiteshbheda

**Comment by hiteshbheda** [comment]
@xiuie Thanks.!!
