### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - Facebook  login screen is not shown after clicking on facebook icon in camera roll

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#278]
1.Open the app.
2.Click on Start
3. By default Camera roll is select
4. Tab on Facebook Icon
5. Facebook get open with error message
6.Error: App Not Setup: This app is still in development mode, and you don't have access to it.Switch to
registered test user or ask an app admin for permissions.

Expected Results: Facebook login page should be shown

Actual Results: Error messages is shown as mentioned in step 6.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

@garimaojha, this issue may be occurred because of no authorization on Facobbok for this development build.

**Comment by xiuie** [comment]
@hiteshbheda I think you're right. @garimaojha Ignore facebook linking/sharing for now. Will have the "older" testers look into this.

**Comment by garimaojha** [comment]
I am still getting this bug only on facebook not on instagram.

**Comment by garimaojha** [comment]
I able to open facebook  app installed on my phone. But not able to open through your app.
