### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - What do you think pop message is annoying

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#279]
1.Open the app
2. start using the app
3. In between the app using the popup message is displayed
4. It  displays the message How likely is that you would recommend to your friends and colleagues
5. There is no options like Don't shown this message again.
6. Also applying the rating the message keeps on poping up.

Expected results : The message should stop poping up if user applying its rating. There should be options to don't show this message again.
Actual Results: The messages keeps on poping and there is no options to for Don't show this message.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this. Similar to #277 
I think it works as design and that's why display popup every time when the app opens

**Comment by xiuie** [comment]
@garimaojha @hiteshbheda I'm just testing this on the dev build. Don't worry about it. I have removed it.
