### ISSUE TITLE
[1.6.8] iPhone 5s/9.1 - User able to enter white space value in title field.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#28]
Frequency: Always

Action:
1. Launch the app.
2. Tap on start.
3. Choose any media file and tap on done icon.
4. Again tap on done icon.
5. Enable the title field and enter white space value.
6. Export the Lomotif
7. Check whether user able to enter white space in title field or not.

Expected Result: User should not be able to enter white space value in title field.

Actual Result: User able to enter white space value in title field.

**Comment by tsukisa** [comment]
This is by design.
