### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - Download issue when installing the app

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#281]
1. Install the app
2. After putting your email id and name
   3.Installation screen will be shown
3. When click on Install first time
4. Download Problem detected :(
5. After repeated click on  Install button the app get installed on phone.
   ![img_0856](https://cloud.githubusercontent.com/assets/18511322/14586254/f8f8c318-04af-11e6-90a8-6d7100acba89.PNG)

**Comment by xiuie** [comment]
@garimaojha Have you got the build on the phone yet? I'm closing this because this doesn't have anything to do with our developers.
