### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - On start page not able to select any tab which is numbered as 1 pick video, 2 Pick music, 3 Pick movie

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#283]
1.Open the app
2. On the app page.
3. There are three options
4. pick video, pick music, pick movie
5. Not able to select any of the options given as 1,2 ,3

 Expected Results. Pick video , pick music, pick movie tabs should be select able. Only one options should be select able and if the user selects one he should be able to move forward.

Actual results : None of the options is select able.
![img_0869](https://cloud.githubusercontent.com/assets/18511322/14588987/f3fcaa74-04f4-11e6-9d22-cf75da7ad7e4.PNG)

**Comment by hiteshbheda** [comment]
@xiuie @garimaojha It's a static design and shows the highlight of Lomotif app (like this app is very simple to create any lomotif / video with only 3 steps).

It works as design.

Right @xiuie ?

**Comment by xiuie** [comment]
Yes @hiteshbheda 

@garimaojha For now, please focus on crash bugs or errors around the creation process.
