### ISSUE TITLE
[1.8.6] iPhone 6 / 9.3.1 - Shake to Shuffle button bug - Disable Shake to shuffle button in Adjust tab, save it and reopen 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#284]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on START button
3. Select few Pictures from Camera roll tab on Albums
4. Select any audio song either from My Music tab or from Find Music tab
5. Click on Adjust tab
6. Disable (Off) Shake to shuffle button
7. Save the created lomotif by clicking on Home button
8. Reopen saved lomotif
9. Again click on adjust tab
10. Observe the state / behavior of Shake to shuffle button

Expected result: Shake to shuffle button should be disabled (Off) when it is saved and reopened

Actual result: Shake to shuffle button enable (ON), even if i have made it disable (OFF) previously and saved it

**Comment by 87Swati** [comment]
I am able to reproduce this issue on iPadair/IOS 9.3.1 with build [1.8.6]

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@f2752e23e797808e6836bf6f60ae74f6e4bf956f
