### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 - On Find music top right corner when click on check mark message box shows cancel on the top

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#285]
1.open the app
2.Click on start
3.select album
4.Go to Find music
5.After selecting music
6.Click on check mark
7.Message displayed should be not cancel at the top.
![img_0870 1](https://cloud.githubusercontent.com/assets/18511322/14589088/2d35639c-04f7-11e6-9854-0297abf9c8ed.PNG)

**Comment by xiuie** [comment]
@tsukisa Text as proposed in Asana was:

Proceed without Music?

Are you sure you want to proceed without adding music?

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can replicate this. But i think it's a proper way to display message.

**Comment by 87Swati** [comment]
The same message box  opens when user want to cancel the sharing of lomotif video on the social networking site .But on that box  message is "Cancel sharing" .

in case of not adding the music ,message can be" Cancel Adding music" or something that.it is just a suggestion.

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by tsukisa** [comment]
@hiteshbheda @vysohanych @garimaojha this is actually by design, you need to press download button not the tick button to use the song. The behavior will change in next build
