### ISSUE TITLE
[1.8.6] iphone 5s/iso 9.3 -On settings tab the font and color does not get selected and changed

### ISSUE THREAD

**Issue by garimaojha** [Lomotif/lomotif-ios-issues#290]
1.Open the app.
2. On settings tab click on fonts or color
3. On selected any font or color it is not select able.
4. Font or color is not applied on  app.

Frequency: always.
![img_0875](https://cloud.githubusercontent.com/assets/18511322/14589318/9a519ffe-04fc-11e6-9554-70ba44575303.PNG)
![img_0874](https://cloud.githubusercontent.com/assets/18511322/14589320/aa89059c-04fc-11e6-86e8-14093ce16dbc.PNG)

**Comment by xiuie** [comment]
I can't replicate this on my iPad mini / 8.1

**Comment by tsukisa** [comment]
@xiuie @garimaojha font color and font under settings are for debugging purpose only, you can ignore that

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I think font color and fonts in setting tab, display that these will be available in creation of lomotif under "Enter a title" tab.

**Comment by tsukisa** [comment]
@hiteshbheda you are correct, those are there for easier access for our designer to see. They are hidden in app store build which includes reset export count as well.

**Comment by hiteshbheda** [comment]
@tsukisa @xiuie Okay. Thanks..!! @tsukisa
