### ISSUE TITLE
[1.8.6] iPhone 6 / 9.3.1 - Invite Friends function Not working - Invite Friends through facebook not working

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#292]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Setting button on top right corner
3. Click on "Invite Friends" button
4. It will open "Invite Friends" module through Facebook authorization
5. Now, click on "Next" button on top right corner of the screen
6. Select few facebook friends from the list 
7. Click on send button

Expected result: Invitation to use Lomotif app should be sent to selected facebook friend / user

Actual result: It displays "Invitation sent" but in real time, my facebook friend not receiving invitation

![img_1697](https://cloud.githubusercontent.com/assets/9691390/14598749/6348242c-0571-11e6-8968-b1f040293575.PNG)

![img_1698](https://cloud.githubusercontent.com/assets/9691390/14598747/6345c132-0571-11e6-9145-10a7ded36909.PNG)

![img_1699](https://cloud.githubusercontent.com/assets/9691390/14598748/63467f50-0571-11e6-9195-17470578a67b.PNG)

![img_1700](https://cloud.githubusercontent.com/assets/9691390/14598750/63488462-0571-11e6-92ea-b4d5ad20c3cf.PNG)

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3.

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by tsukisa** [comment]
@vysohanych @hiteshbheda probably because your friends are not in our testers list, will verify this
