### ISSUE TITLE
[1.8.6] iPhone 5S / 9.3.1-  The audio of the montages stucks when clicked on the images after the phone is unlocked 

### ISSUE THREAD

**Issue by anishtpt** [Lomotif/lomotif-ios-issues#294]
Frequency:Everytime

Steps:
1.Create a project
2.Open the project and play the project
3.lock the iphone
3.Unlock the iphone
4.Play the project and click on any of the picture
5.Observe that the audio of the montage stucks

Expected result:The audio of the montage shouldn't get stuck

**Comment by anishtpt** [comment]
Please refer to the video link:
https://www.dropbox.com/s/rb2qn7k349qwa3p/music%20stucks.MOV?dl=0

**Comment by hiteshbheda** [comment]
@xiuie @anishtpt I think it works as design. And @anishtpt when you click and select any of the picture, only selected frame of created lomotif / video will be played along with synchronized audio.
