### ISSUE TITLE
[1.8.6] iPhone 6 / 9.3.1 - Filter Bug - Appear regular screen for sometime even if applied filter

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#296]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any lomotif
3. Enable Filter Tab
4. Swipe on screen to right direction and select B & W filter
5. Now click on Home button and save lomotif
6. Again, reopen saved lomotif
7. Observe the screen of playing lomotif 

Expected result: Lomotif should be played on screen with "B & W" filter

Actual result: Lomotif plays with "Paris" filter even though i have select "B & W" filter

![img_1707](https://cloud.githubusercontent.com/assets/9691390/14600667/8b249b06-057b-11e6-9916-e6e16121065b.PNG)

![img_1708](https://cloud.githubusercontent.com/assets/9691390/14600668/8b91e49a-057b-11e6-95b9-5b4aa6def611.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.6 on iPad 2 iOS 9.3.1

**Comment by 87Swati** [comment]
I can reproduce it on build 1.8.6 on iPadAir iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can still reproduce this issue for build [1.8.7] on iPhone 6 / iOS 9.3.1

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@4af4d92e818fdedbdc168ef586123da245ee356f
