### ISSUE TITLE
[1.8.6] iPhone 5S / 9.3.1 - Share - The montage is played even after the montage is shared on facebook messenger 

### ISSUE THREAD

**Issue by anishtpt** [Lomotif/lomotif-ios-issues#297]
Frequency:Everytime

Steps:
1.Create a new montage
2.Share and select messenger option
3.Login and share the montage 
4.Click on the "back to lomotif-dev" link
5.Observe that the montage is played on the share page

Expected result:The montage should not be played on the share page

**Comment by anishtpt** [comment]
https://www.dropbox.com/s/21e4a3ctvvmq73t/share-messenger.MOV?dl=0

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.6] on iPhone 6 / iOS 9.3.1

Similar to #252

**Comment by xiuie** [comment]
Thanks @anishtpt 
Will be scored as a bug.. But for organisation, have marked it as duplicate and closing.
