### ISSUE TITLE
[1.8.6] iPhone 5S / 9.3.1- The loader keeps on loading For videos under Motif section in absence of internet

### ISSUE THREAD

**Issue by anishtpt** [Lomotif/lomotif-ios-issues#299]
Steps:
1.Open the app and click on start
2.Check the Motif tab
3.Select any category and click on the play button in the middle of the thumbnail

Expected result:The loader keeps on loading for videos

**Comment by anishtpt** [comment]
https://www.dropbox.com/s/iwvhz14z6e6nbue/loader.MOV?dl=0

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue on iPhone 6 / iOS 9.3.1

But when i create lomotif using some motifs without internet then it plays correctly.

**Comment by xiuie** [comment]
@pmtheint How do we inform the users they have to use Motifs with internet connection?

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.7 on iPad 2 iOS 9.3.1.

**Comment by pmtheint** [comment]
This will be solved when we cover timeout.
