### ISSUE TITLE
[1.6.5] Music is not playing for 30 seconds preview if we made the video

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#3]
1. Open Lomotif App 
2. Click on Start Button in Home Screen 
3. Select Photos and videos 
4. Select any of the music from the list
5. Click on 'Use 30 Seconds preview' then it shows preview but music is not playing.

Please find here with attached screenshots,
![img_0100](https://cloud.githubusercontent.com/assets/5388768/12230249/0ad9cf3c-b875-11e5-8839-089be51e0bcf.PNG)

![img_0098](https://cloud.githubusercontent.com/assets/5388768/12230223/c34fb53c-b874-11e5-8173-2b85a655e832.PNG)

**Comment by tsukisa** [comment]
Bug has been resolved with commit at Lomotif/lomotif-ios@2fe00e278380b83cec42ad007f6f4336c8acadb9
