### ISSUE TITLE
While exporting, music plays in the background when user locks and unlocks the device.

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#303]
Device: iPhone 5c, iPhone 6, iPad 2,3 

Steps to reproduce:
1. Launch the application.
2. Add a video
3. Add a music.
4. Create a video
5. Click on the export icon on the header
6. When social media sharing list get displayed, lock the device screen
7. Unlock the device now.

Actual Result: The music starts playing in the background

Expected Result: While exporting music shouldn't play in backgound

**Comment by tsukisa** [comment]
@xiuie can you reference the duplicate issue? Thanks!

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.8 on iPad 2 iOS 9.3.1.
