### ISSUE TITLE
Not able to connect to Facebook from anywhere in the whole application

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#304]
Device: iPhone 5c, iPhone 6

At following places the facebook is not working -
1. Launch the application.
2. Go to Settings.
3. Not able to 'Invite Friends' through Facebook"

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai Actually you are not authorized on Facebook for Lomotif app for this development build. That's why you won't be able to test Facebook from app.

Similar to #278
