### ISSUE TITLE
Sometimes when it takes too much time to load the video, the loading sign alignment is not centered

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#305]
Device: iPhone 6

Steps to reproduce: 
1. Launch the application.
2. Add a video
3. Add a music.
4. Create a video
5. Add more video or photo from the '+' icon near the thumbnails. http://prnt.sc/atr7o0

Actual Result: While loading, the loading sign is not centered

Expected Result: http://prnt.sc/atr957

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce it on iPhone 6 / iOS 9.3.1

It's centrally aligned.

**Comment by tsukisa** [comment]
@hiteshbheda @pallavipillai i noticed this issue doesn't always appear, it's pretty random

**Comment by pallavipillai** [comment]
@tsukisa - Yes, this issue is random

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.8 on iPad 2 iOS 9.3.1.
