### ISSUE TITLE
Unknown symbol on News page, which doesn't get convert to any smiley/symbol

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#307]
Device: iPhone 5c, iPhone 6, iPad 2,3
1. Go to Settings.
2. Go to News page
3. See, the unknown symbol. http://prnt.sc/atr3sg

Actual Result: Unknown symbol is present at the end of the paragraph

Expected Result: The unknown symbol, if its an smiley/symbol then it should be converted into it.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue on iPhone 6 / iOS 9.3.1

But I think it's not a big issue even sometime few stickers and smileys are not supportable then it may happens.

**Comment by xiuie** [comment]
Haha @pallavipillai It's a heart shape symbol. :D
