### ISSUE TITLE
Not able to 'Invite Friends' through Facebook

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#308]
Devcie: iPhone 5c, iPhone 6
1. Launch the application.
2. Go to Settings.
3. Go to Invite Friends.

Actual Result: Not able to 'Invite Friends' through Facebook

Expected Result: User should be able to invite friends through facebook.

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai Please ignore Facebook related links and testing. You are not yet authorized on Facebook for Lomotif app.

**Comment by xiuie** [comment]
Thanks @pallavipillai but am closing this for now. I've tested on my end and it works so I guess it's authorization issues.
