### ISSUE TITLE
[1.6.8] iPhone 6/9.2 - Exporting with filters - Error 11841 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#31]
Frequency: Always

Action:
1. Start
2. Select 10 screenshots
3. Select Music
4. Turn on filter and swipe to Mini Me
5. Export

Expected: Video exports

Actual: Error 118421, and fails to export

Note: Export works with 10 x video clips

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@c9635f2c66ab4eba5e48c9793e2c8e1c0a4c69d9
