### ISSUE TITLE
[1.8.6] iPhone 5S / 9.3.1-  Additonal inbuilt share overlap is displayed when user wants to share the montage via whatsapp

### ISSUE THREAD

**Issue by anishtpt** [Lomotif/lomotif-ios-issues#312]
Frequenct:Always

Steps:
1.Create a montage
2.Export it to share the montage
3.click on whatsapp
4.Observe that a additonal inbuilt overlap is displayed to select the whatsapp

Expected result:When user selects the whatsapp option , user should be redirected directly on whatsapp.

**Comment by anishtpt** [comment]
https://www.dropbox.com/s/ak8w7o69gld47tf/whatsapp.mov?dl=0

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue on iPhone 6 / iOS 9.3.1

@anishtpt May be, you have not yet authorized your WhatsApp account

**Comment by xiuie** [comment]
@anishtpt Yes. You need to sign in to Whatsapp. What you're seeing (Whatsapp authorization, is beyond our control.)
