### ISSUE TITLE
Cannot delete all the clips from the video

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#314]
Description: When there are more than one clips in the video, the user is not able to delete all the clips, the last clip couldn't be deleted.

Device: iPAD 2, 3

Build Version: 1.8.6

iOS version: 9.3.1

Steps to reproduce:
1. Launch the application
2. Add 3 videos
3. Add any music.
4. Create a video
6. Try to delete all the clips

Actual Result: User is not able to delete the last clip

Expected Result: User should be able to delete all clips.

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai Please follow the instructions and create test cases in proper prescribed format

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai I can reproduce this issue on iPhone 6 / iOS 9.3.1

But I think, It works as design

**Comment by pallavipillai** [comment]
@hiteshbheda  - are you mean for defects ?

**Comment by hiteshbheda** [comment]
@pallavipillai As per application design, there should be at least one image / video in lomotif. Without it we can not create lomotif. So as per validation last image / video will not be deleted.
