### ISSUE TITLE
When user deletes all clips except anyone, the video keeps playing in Create screen

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#318]
Description: When user add more than two video clips and then deletes all video clip except anyone, the video clip which is left keep playing and never stops.

Device: iPAD 2, 3

Build Version: 1.8.6

iOS Version: 9.3.1

Steps to reproduce:
1. Launch the application
2. Add 2 videos
3. Add any music.
4. Go to Create screen.
5. Delete 1 video clip

Actual Result : The video clip which is left keeps playing and never stop

Expected result: The video clip should play and should stop after playing

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai It works properly as designed.

When you delete any clip, it automatically select next clip from frame. And will continue playing till you will click on apply button from top right corner.

Similar to #316
