### ISSUE TITLE
Suggestion : User cannot add more than one sticker

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#319]
Description: As per the user flexibility, user should be able to add more than one sticker in the video

Device: iPAD 2, 3

Build Version: 1.8.6

iOS version: 9.3.1

Steps to reproduce:
1. Launch the application
2. Add a video.
3. Add any music.
4. Create a video
5. Add a sticker
6. Try to add 2nd sticker

Actual Result: User is not able to add more than one sticker.

Expected result: User should have the flexibility to add more than one sticker in the video

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai I can replicate this,

But i think it works as design.
