### ISSUE TITLE
[1.6.7] iPhone 6/9.2 -Saved Motifs-only project doesn't appear in "Saved Projects" section 

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#32]
How to replicate:

Start
Select Motifs tab, and select ONLY Motifs
Select Music
On the Create screen, edit your project e.g. resize a clip (Note: Otherwise the project can't be saved!)
Hit Home and choose to save your project
Expected: You see the new Motifs-only project thumbnail

Actual: No new thumbnail is created

Note: The thumbnail only appears once you select another project and then hit home again. However, if you do a non-Motifs project, you do not have to go through that extra step to see your saved project.

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@e7f42ee80a3fad278ef45f32f16852b0924a8824
