### ISSUE TITLE
Suggestion: Cannot change the position of added sticker

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#320]
Description: As per the user flexibility, user should be able to change the position of added sticker in the video.

Device: iPhone 6, iPAD 2, 3

Build Version: 1.8.6

iOS version: 9.3.1

Steps to reproduce:
1. Launch the application
2. Add a video.
3. Add any music.
4. Create a video
5. Add a sticker
6. Try to change the position of sticker.

Actual Result : User is not able to change the position of the sticker.  http://prnt.sc/au5ase

Expected Result : User should have the flexibility to change the position of added sticker

**Comment by hiteshbheda** [comment]
@xiuie @pallavipillai I can replicate this.

But i think it works as design.
