### ISSUE TITLE
[1.8.7] iPhone 6 / 9.3.1 - Stickers Bug - Stickers appears even if disabled it and save motif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#322]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing motif
3. Enable and apply stickers by clicking on Stickers tab
4. Click on Home button and save lomotif
5. Open previously saved lomotif
6. Again, tab on the stickers and disable it
7. Click on Home button and save lomotif
8. Again open the same lomotif
9. Observe the stickers on the screen

Expected result: Stickers should be disabled as it was disabled/OFF in previous process

Actual result: Stickers are still available on the screen even if i have disabled it last time

![img_1729](https://cloud.githubusercontent.com/assets/9691390/14669737/cecbaf42-0707-11e6-9844-48461e3a9124.PNG)

![img_1730](https://cloud.githubusercontent.com/assets/9691390/14669738/cecdaa68-0707-11e6-83ca-1521babf50fe.PNG)

![img_1731](https://cloud.githubusercontent.com/assets/9691390/14669739/cee631aa-0707-11e6-80f2-e41425a44eca.PNG)

![img_1732](https://cloud.githubusercontent.com/assets/9691390/14669736/cec708d4-0707-11e6-8a64-cd9c8032742a.PNG)

**Comment by Dipamit** [comment]
It seems like working as design. When you tap on to go back it will not save value.

**Comment by hiteshbheda** [comment]
@Dipamit I'm not going back in any step. I'm saving stickers effect in all steps by clicking on Home button.

**Comment by Dipamit** [comment]
Unable to reproduce this issue on iPhone 5/8.3 for build [1.8.7].
I am able to Enable and Disable Stickers on saving Motif.

**Comment by 87Swati** [comment]
I am able to reproduce this on build 1.8.6 on IPad Air/9.3.1.

Even when i switch the stickers states on saved lomotif and click on home button ,app does not ask for confirm the changes ,App asks for directly go to the home page only.
