### ISSUE TITLE
[iPhone 6/1.8.7] While exporting the video, the message is displayed as "Your lomotif has been saved in your.."

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#323]
Frequency: Always
1. Launch the application
2. Add a video
3. Add a music
4. Go to Create screen
5. Export the video

Actual Result: While exporting the message get displayed as "Your lomotif has been saved in your..." http://prnt.sc/aukw8a

Expected Result: The message should be completely display as "Your lomotif has been saved in your Camera Roll"

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this on iPhone 6 / iOS 9.3.1

**Comment by xiuie** [comment]
@tsukisa Hmm this is not critical. But maybe can fix this before launch (the definition of our Critical label) if you can just split it into two lines?

**Comment by tsukisa** [comment]
@xiuie i will mark it high and set milestone to v1.8.8

**Comment by 87Swati** [comment]
In IPadAir/9.3.1  on build 1.8.6 ,message is displaying" Saving lomotif to Camara Roll".

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@8e6d6226e53bf3108098fbd946a141c0f03a54ea
