### ISSUE TITLE
[1.8.7] iPhone 6 / 9.3.1 - Invite Friends Select button not working - In Invite Friends, Radio (Round) button not working to select facebook friends

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#326]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Menu button from Top Right corner of the screen
3. Click on Invite Friends tab
4. On next screen, click on next button
5. Now, click on Radio button to select / invite facebook friends from the Recommended friends' list

Expected result: Facebook friends should be selected by clicking on Radio (Round) button appear at left to the name of facebook user

Actual result: Radio (Round) button not working to select facebbok friend

[Invite Friends Selection Button Bug - Video](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UX3N3TWYxanhNRnc)

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.7]

**Comment by tsukisa** [comment]
@hiteshbheda the Facebook app invite is a web page created by Facebook so we can't fix it if it's broken

**Comment by hiteshbheda** [comment]
@tsukisa Ok. Thanks for Information and Update..!!!
