### ISSUE TITLE
[1.8.7] iPhone 6 / 9.3.1 - Play button not available - Lomotif paused and play button not available on the screen during selection of image from lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#327]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing motif with multiple images or videos clips
3. Now select any image or video clip from playing lomotif
4. Selected image or video will continue play with music
5. Minimize the app (Take the lomotif app in background)
6. Again resume the app from background
7. Now, click on the screen to play that selected image / video clip

Expected result: Clicking on screen should start play selected image / video clip with music

Actual result: Clicking on screen not working when switching app from background to running mode

**Comment by Dipamit** [comment]
Able to reproduce this issue on iPhone 5/8.3 for [1.8.7]

**Comment by tsukisa** [comment]
@hiteshbheda @Dipamit thanks for reporting, this is a known issue

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.8 on iPad 2 iOS 9.3.1.

**Comment by hiteshbheda** [comment]
I can still reproduce it on build [1.8.8] on iPhone 6 / iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @pmtheint This issue is still reproducible for build [1.8.9] on iPhone 6 / iOS 9.3.1

**Comment by tsukisa** [comment]
tap anywhere to play/pause video has been implemented since 1.8.19
