### ISSUE TITLE
[1.8.7] iPhone 6 / 9.3.1 - Shake to shuffle control Bug - Disable "Shake to shuffle" button still provides control through playing screen 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#328]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on start 
3. Select 2 images from Camera roll and click on apply button
4. Select any song and apply
5. Now, tap on Adjust tab
6. "Shake to shuffle" button will Enable (On) by default
7. Shake your iPhone once, Shake to shuffle control will appear on the screen
8. Now, disable (OFF) "Shake to shuffle" button from Adjust tab
9. Observe the Shake to shuffle control on screen

Expected result: By disabling (OFF) "Shake to shuffle" button from Adjust tab should remove Shake to shuffle control from the screen

Actual result: After disabling (OFF) "Shake to shuffle" button from Adjust tab, Shake to shuffle control still available on the screen and we can shake images from the screen control

![img_1744](https://cloud.githubusercontent.com/assets/9691390/14685642/f90f4764-0752-11e6-9337-71153eb1cfe9.PNG)

![img_1745](https://cloud.githubusercontent.com/assets/9691390/14685643/f93842b8-0752-11e6-93c1-a17c0e1fefbe.PNG)

![img_1746](https://cloud.githubusercontent.com/assets/9691390/14685641/f8e17136-0752-11e6-8394-fa6923f0caf0.PNG)

**Comment by xiuie** [comment]
@hiteshbheda It disappears after awhile though.

I suspect it's work as designed because the user may need to "undo" his shake to shuffle, which is what the control is primarily for.

**Comment by hiteshbheda** [comment]
@xiuie If it works as design then Good. 

I thought that once we disable through button, it should disappear from screen.

**Comment by pmtheint** [comment]
Agreed. The button group is supposed to stay there for 3osecs in case users want to undo. You can just hit tick to dismiss.

**Comment by hiteshbheda** [comment]
@pmtheint Thanks for the update.!!
