### ISSUE TITLE
[1.8.7] iPhone 5/8.3 : Wrong spell for "Acknowldgement" in Licenses tab.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#329]
Frequency: Every time
1. Open App and tap on "Settings"
2. Tap on "Licenses"  
3. Verify the displayed label.

Expected result: Spelling should proper.

Actual result: Wrong spell for "Acknowledgement"
![img_2951](https://cloud.githubusercontent.com/assets/17335200/14686386/14f5a466-0756-11e6-9979-e1743e1f3bf3.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@c7b253ae62c012181aaab2212910ccb412453644
