### ISSUE TITLE
[1.6.7] iPhone 6/9.2 - Crash bug: When turning filters on

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#33]
How to replicate:

Start
Add a lot of photos e.g. 31-35 (I used ALL photos)
Select Music and hit next
While the photos are still loading, turn on filters
App crashes

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@818649d0b17ff76e967a257d4c9503a8f3c9377c
