### ISSUE TITLE
[1.8.7] iPhone 6 / 9.3.1 - "Invite Friends" not working from iOS to Android device- Invitation sent from iOS device but not received on Android device

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#330]
Frequency: Every time

Action:
1. Launch Lomotif on iOS device
2. Click on Menu button from Top Right corner of the screen
3. Click on Invite Friends tab
4. On next screen, click on next button
5. Now, select friend who have installed Lomotif-staging app on Android device
6. Click on send button and send invitation

Expected result: Invitation should be received by the Android user to whom i have selected from list

Actual result: Invitation sent from iOS device but not received at Android device even if lomotif-staging app is already installed

**Comment by tsukisa** [comment]
The receiver has to be in tester list to receive the invite.

**Comment by hiteshbheda** [comment]
@tsukisa Ok. Thanks.!
