### ISSUE TITLE
[1.8.8] iPhone 5/8.3 : It seems like text on FAQ is different for different language.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#332]
Frequency : Always
1. Open application.
2. Tap on top right for Menu.
3. Tap on "Frequently Asked Question"
4. Verify  full page then tap on top right to change Language.
5. Verify displayed page.

Expected result: Text on FAQ should same for different language.

Actual result: It seems like text on FAQ is different for different language.
[FAQ.zip](https://github.com/Lomotif/lomotif-ios-issues/files/231664/FAQ.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this for build [1.8.8] on iPhone 6 / iOS 9.3.1

**Comment by xiuie** [comment]
Not a bug.
