### ISSUE TITLE
[iPad 2&3/1.8.8]Title added by the user doesn't display in video

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#333]
Frequency: Always
1. Launch the application
2. Add videos
3. Add a music
4. Go to Create screen
5. Add a title in "Enter A Title" field.
6. Play the video

Actual Result - The title entered by user is not displayed in video. http://prntscr.com/aveuzb

Expected Result - The title should be displayed in video.

Twitter link - https://twitter.com/tmsuser01/status/723480537457790977

**Comment by Dipamit** [comment]
Able to reproduce this issue on iPhone 5/8.3 for build [1.8.8]

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this issue for build [1.8.8] on iPhone 6 / iOS 9.3.1
