### ISSUE TITLE
[1.8.8] iPhone 6 / 9.3.1 - "Enter a title" not working - Providing test in "Enter a title" not appearing on screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#334]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few pictures from Camera roll or few motifs from any motif category
4. Select audio from My Music or Find Music
5. Tap on "Enter a title" and provide any text value
6. Observe the effect on the screen

Expected result: Text value entered in "Enter a title" should appear on lomotif playing screen

Actual result: No text appear even if i have entered some text on "Enter a title" tab

![img_1759](https://cloud.githubusercontent.com/assets/9691390/14743776/edc438aa-08c0-11e6-993b-ff10d33485ee.PNG)

![img_1760](https://cloud.githubusercontent.com/assets/9691390/14743775/edbde5e0-08c0-11e6-82e1-cc0219f3e3e2.PNG)

**Comment by tsukisa** [comment]
duplicate of #333
