### ISSUE TITLE
[1.8.8] iPad 2 / iOS 9.3.1 - Export - Quality of video is lower than original video when user uses for lomotif previously created lomotif

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#338]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Switch to Motif tab on the Albums screen
4. Select any motif
5. Tap apply button on the Albums screen
6. Tap apply button on the Find Music screen and tap OK button on the Cancel dialog
7. Tap export button on the Create screen
8. Back to home screen and tap again START button
9. Select the just created lomotif from Camera Roll folder
10. Tap apply button on the Albums screen
11. Tap apply button on the Find Music screen and tap OK button on the Cancel dialog
12. Tap export button on the Create screen
13. Back to home screen and compare two lomotifs

Expected result: Two lomotifs have the same quality

Actual result: The second lomotif has lower quality than first lomotif

Video: [Recording #126.zip](https://github.com/Lomotif/lomotif-ios-issues/files/232242/Recording.126.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this for build [1.8.8] on iPhone 6 / iOS 9.3.1

But, I think it's obvious as we are making copy from the original, so definitely it won't have that great quality compared to original.
