### ISSUE TITLE
[1.8.8] iPhone 6 / iOS 9.3.1 - Shake to shuffle (playing screen) controller bug - Undo button works only once and

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#340]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select pictures / videos or motifs
4. Select any song
5. Create lomotif
6. Shake your iPhone once
7. Shake to shuffle controller appears on the screen
8. Shuffle clips 3 - 4 times
9. Now, click on Undo (2nd) button from the screen controller
10. Observe the effect on the screen
11. Again, Click Undo button multiple times
12. Observe the effect on the screen

Expected result: 
1. Clicking Undo button multiple times should effect multiple undo effects / steps OR
2. After clicking one time, the undo button should disable

Actual result: Undo button works only once, After that multiple clicks apply but not affecting on the screen

![img_1769](https://cloud.githubusercontent.com/assets/9691390/14750321/d2ecd2aa-08e1-11e6-9678-2bb7a68b66c8.PNG)

**Comment by pmtheint** [comment]
It was supposed to disable after one undo because so far we only support one undo step. Will note enhancement.

**Comment by hiteshbheda** [comment]
@pmtheint Thanks for update..!!

If it support one undo step, then after one click the undo button should be disabled.
