### ISSUE TITLE
[1.8.8] iPad Mini / iOS 8.1 - titles not working

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#341]
[1.8.8] iPad / iOS 8.1 - titles not working

Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Select pictures / videos or motifs
4. Select any song
5. Add title

Expected result: Video replays with title

Actual result: No titles

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this issue every time for build [1.8.8] on iPhone 6 / iOS 9.3.1

Similar to #339 #334 #333

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.9] on iPhone 6 / iOS 9.3.1

**Comment by xiuie** [comment]
Fixed in 1.8.9
