### ISSUE TITLE
[1.8.8] iPad 2 / iOS 9.3.1 - Export - Application crashes when try to export lomotif with filter and sticker

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#342]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Select any picture On Camera Roll tab
5. Tap apply button on the Albums screen
6. Select any song On Find Music screen
7. Tap apply button on the Find Music screen
8. Enable Stickers and select the first sticker
9. Enable Filters
10. Tap export button on the Create screen

Expected result: User sees sharing screen

Actual result: Application crashes

Video: [Recording #127.zip](https://github.com/Lomotif/lomotif-ios-issues/files/232480/Recording.127.zip)

Crash log: [Lomotif-2016-04-22-195014.zip](https://github.com/Lomotif/lomotif-ios-issues/files/232482/Lomotif-2016-04-22-195014.zip)

**Comment by tsukisa** [comment]
@xiuie seems like it's memory related issue

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can replicate this issue for build [1.8.8] on iPhone 6 / iOS 9.3.1

**Comment by Dipamit** [comment]
This issue is reproduced just once on iPhone 5/8.3 for build [1.8.8]

**Comment by hiteshbheda** [comment]
@xiuie I can't replicate this issue for build [1.8.9] on iPhone 6 / iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.12] on iPhone 6 / iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.14] on iPhone 6 / iOS 9.3.1
