### ISSUE TITLE
[1.8.8] iPhone 6 / iOS 9.3.1 - App Crash - Create lomotif with multiple videos from camera roll and Find music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#343]
Frequency: Most of the time

Action:
1. Launch Lomotif
2. Tap on start
3. Select few videos from camera roll
4. Click on apply button from top right corner
5. Tap on Find Music tab from Find Music screen
6. Click on any song from the list and click on apply button
7. Play created lomotif

Expected result: Lomotif should be played on the screen

Actual result: Application crash 

[Crash log](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4URUxDTlNUNngza0U)

**Comment by Dipamit** [comment]
Not able to reproduce this issue on iPhone 5/8.3 for build [1.8.8]

**Comment by xiuie** [comment]
@hiteshbheda What's the ratio of crashes to total tries? e.g. 1/9 times?

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.9] on iPhone 6 / iOS 9.3.1 

This issue was very frequent today morning for me approx 70 % times from total attempts. 

In fact, i have already discuss this issue with you today morning on Slack if you remember.

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.9 on iPad 2 iOS 9.3.1
