### ISSUE TITLE
[1.8.9] iPad 2 / iOS 9.3.1 - Export - Facebook tries to open in Safari browser when user has installed facebook app

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#349]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap START button on the home screen
3. Switch to Motif tab on the Albums screen
4. Select any motif
5. Tap apply button on the Albums screen
6. Select any song on the Find Music screen
6. Tap apply button on the Find Music screen
7. Tap export button on the Create screen
8. Tap Facebook button on the sharing screen

Expected result: User should see that lomotif is shared via facebook app

Actual result: User sees opened facebook page in Safari browser

Video: [Recording #135.zip](https://github.com/Lomotif/lomotif-ios-issues/files/233183/Recording.135.zip)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.9] on iPhone 6 / iOS 9.3.1

When I'm trying to perform same steps, it directly posts lomotif on Facebook wall without opening Facebook app or even Facebook site on safari.

**Comment by vysohanych** [comment]
@xiuie @tsukisa I can reproduce it on 1.8.10 build. Probably I don't have access. I asked You to give me access on FB account id=100011841667606

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.10]
