### ISSUE TITLE
There is no message displayed when user search music with wrong text.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#35]
Frequency: Always

Action:
1. Launch the app.
2. Tap on start.
3. Choose any media file and tap on done icon.
4. Enter any invalid text in search music field.
5. Check whether there is any message display or not.

Expected Result: "No music found" message should display when user search music with wrong text.

Actual Result: There is no message displayed when user search music with wrong text.
![no_message_music](https://cloud.githubusercontent.com/assets/9127217/12347513/6235d4d0-bb84-11e5-81cf-1a07398bbd37.jpg)

**Comment by benchang** [comment]
@pmtheint please decide whether you want this enhancement, if so, add to asana and close, otherwise just close

**Comment by pmtheint** [comment]
Moved to Asana.
