### ISSUE TITLE
[1.8.9] iPad 2 / iOS 9.3.1 - Terms of Use & Privacy Policy - Links from Terms of Use & Privacy Policy  screen should be opened in browser

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#350]
Frequency: Every Time

Action:
1. Launch Lomotif
2. Tap menu button on top right corner on the home screen
3. Tap Terms of Use & Privacy Policy button on right menu
4. Scroll the current screen down
5. Tap on any link like www.lomotif.com or email

Expected result: All links and emails should work. Links should be opened in browser and emails should be opened in mail client (if it installed)

Actual result: When user taps www.lomotif.com link appears web-page into application but buttons on this page don't work. Also nothing happened when user taps another links or emails.

Video:[Recording #136.zip](https://github.com/Lomotif/lomotif-ios-issues/files/233189/Recording.136.zip)

**Comment by xiuie** [comment]
@vysohanych Lomotif.com works for me.

**Comment by vysohanych** [comment]
@xiuie Yes, it works. I wrote it in actual result but I think that this page should be opened in browser not in application
