### ISSUE TITLE
[1.8.9] iPhone 5 / iOS 8.3 - Application crash on trying to minimize and open application during file saved to photo.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#352]
Frequency: Everytime

Action:
1. Launch Lomotif
2. Open any exists lomotif having some big size.
3. Tap export button which ask to save Lomotif in photo.
4. Tap on Yes and then during saved photo process minimize the application.
5. Open application again and check it resume from remaining and then again do same. 

Expected result: It should show Error message and Application should not crash.

Actual result: Application is crashed. 
[Crash on Trying to Open app during Export.zip](https://github.com/Lomotif/lomotif-ios-issues/files/233553/Crash.on.Trying.to.Open.app.during.Export.zip)

**Comment by xiuie** [comment]
I can't crash it but I get error 11847 on my iPhone 6/1.9.2 @tsukisa 

Can we have a message when people are export, and they minimize the application to the background.. @pmtheint for consideration.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.9] on iPhone 6 / iOS 9.3.1

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.9 on iPhone 5S iOS 8.4.1

**Comment by Dipamit** [comment]
Not able to reproduce this issue on iPhone 5/8.3 for build [1.8.10]

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.10] on iPhone 6 / iOS 9.3.1

**Comment by Dipamit** [comment]
@xiuie : I am able to reproduce this issue on iPhone 5/8.3, But not able to reproduce this issue on iPhone 5/9.3.1 for build[1.8.12]

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.14] on iPhone 6 / iOS 9.3.1

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3 for build [1.8.16] 
Frequency : Sometime

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.18] on iPhone 6 / iOS 9.3.1
