### ISSUE TITLE
[1.6.8] iPhone 6/9.1 - There is no option to enable access camera roll in the app if user don't allow the app to access his gallery

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#36]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. During installation don't allow app to access the data from the gallery
4. Navigate to App home 
5. Tap Start button
6. Observe under Camera Roll there is no option to access the photos from phone

When a user installs app and don't allow app to access the gallery or personal photos during installation. Now after the app completely installed and user navigate to app home screen and tap on Start button then if user wants to access his photo to make movie using his photos then there is no option to access the gallery again.

Expected Result: There should be a option to access to the Camera Roll with in the app even after not allowing the app to access the photos during installation
Actual Result: There is no such option.

**Comment by tsukisa** [comment]
This is works as design, in iOS you cannot change privacy setting within the app.
