### ISSUE TITLE
[1.8.10] iPhone 6 / iOS 9.3.1 - New update message  Bug- Display "New Build available" message even if i have installed the same version

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#360]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on start
3. Observe the message "New Build available" on the screen

Expected result: Message should not be displayed as i have already installed the same (new updated) version of the app

Actual result: "New build available" message displayed even if i have installed the same version of the app

![img_1882](https://cloud.githubusercontent.com/assets/9691390/14807306/f5137636-0b98-11e6-8a34-726a479a7065.PNG)

![img_1883](https://cloud.githubusercontent.com/assets/9691390/14807307/f5146852-0b98-11e6-8b40-785f6e76f8f6.PNG)

**Comment by xiuie** [comment]
@tsukisa Is this a bug? If not we can close it.

**Comment by tsukisa** [comment]
@xiuie I accidentally uploaded a new build with same version number.

**Comment by hiteshbheda** [comment]
@tsukisa Ok. Even i have installed new build second time. Now it doesn't give me that popup message.

Thanks..!
