### ISSUE TITLE
[1.8.10] iPAD 3 / iOS 9.3.1 - Application get closed while exporting, this happens only when videos are taken from Camera roll and not from motif

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#361]
Frequency: Every time

Steps to reproduce -
1. Create 3 videos from your iOS device
2. Launch the application
3. Click on Start
4. Take those 3 videos from Camera roll that you just created from your iOS device
5. Add a music
6. Go to Create Screen
7. Add a sticker to the video
8. Add a Filter, for example, Richie Rich
9. Enter Title
10. Export the video

Actual Result - When user clicks on Export icon, export get started, but the application get closed.

Expected Result - Lomotif video should be exported properly

Note - This issue only happens when user first create some videos from iOS device camera and then uploads those videos on Lomotif app from Camera roll.

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this issue for build [1.8.10] on iPhone 6 / iOS 9.3.1

Even when i'm trying to create lomotif using camera roll it get crashed.

**Comment by pallavipillai** [comment]
I checked this issue on build [1.8.10] iPhone 5c / iOS 9.3.1 - An error is displayed - http://prntscr.com/ax04re

**Comment by Dipamit** [comment]
Application does not closed or not even crash, I am getting one pop-up while selecting already created video and tap on export on iPhone 5/8.3 for build[1.8.10]

![img_3024](https://cloud.githubusercontent.com/assets/17335200/14849389/4e1804f2-0c90-11e6-9744-ab2fb80242b2.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on build v1.8.2 (1.8.10) on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.12] on iPhone 6 / iOS 9.3.1

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 and iPhone 5/9.3.1 for build [1.8.12]

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.14] on iPhone 6 / iOS 9.3.1
