### ISSUE TITLE
[1.8.10] iPhone 5c / iOS 9.3.1 - On settings page, the text "Libraries" is overlapping on build and dev version information

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#362]
Frequency: Every time

Steps to reproduce -
1. Launch the application
2. Click on Menu icon on the upper right corner.

Actual Result - The text "Libraries" is overlapping on build and dev version information. http://prntscr.com/awzemg

Expected result - There should be no overlapping and the text should be clearly readable.

**Comment by hiteshbheda** [comment]
@xiuie Duplicate of #356
