### ISSUE TITLE
[1.8.10] iPhone 6 / iOS 9.3.1 - FB Messenger sharing Broken Album art - Click on Messenger and Message at the same time will display broken lomotif album art

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#365]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing lomotif
3. Click on Export button at Top Right Corner
4. Tap on Messenger and Message icon at the same time
5. Observe the messenger screen and observe Album art (Thumbnail)

Expected result: Perfect Album art (Thumbnail) should be displayed on the Messenger screen

Actual result: Broken Album art (Thumbnail) display on the Messenger screen

![img_1899](https://cloud.githubusercontent.com/assets/9691390/14827558/9d1de020-0c00-11e6-88fb-1341e948ba3d.PNG)

![img_1901](https://cloud.githubusercontent.com/assets/9691390/14827557/9d1787c0-0c00-11e6-9968-1fd53358ce49.PNG)

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.10]
