### ISSUE TITLE
Login failed error message displayed when user try to link with Twitter and Instagram having no wifi.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#37]
Frequency: Always

Action:
1. Launch the app.
2. Tap on settings.
3. Tap on linked accounts.
4. Turn off the wifi.
5. Tap on Twitter or Instagram.
6. Check whether login failed error message display or not.

Expected Result: "No internet connection" message should display when user try to link with Twitter and Instagram having no wifi.

Actual Result: Login failed error message displayed when user try to link with Twitter and Instagram having no wifi.

**Comment by benchang** [comment]
@pmtheint please decide whether you want this enhancement, if so, add to asana and close, otherwise just close

**Comment by pmtheint** [comment]
Moved to Asana
