### ISSUE TITLE
[1.8.12] iPhone 6 / iOS 9.3.1 - Notify me (Email) Bug - Send mail to help@lomotif.com and enable "Notify me" option does not affect on any updation

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#372]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Menu button at Top Right Corner on Home screen
3. Click on Send Feedback option
4. Tap on Subject line
5. It will show "Notify Me" and "Cancel" option
6. Enable "Notify Me" option by clicking on it
7. By receiving any mail or update from help@lomotif.com, you should be notified

Expected result: User should be notified when receiving any mail from help@lomotif.com

Actual result: No Notification or Alert available when receiving mail from help@lomotif.com

![img_2074](https://cloud.githubusercontent.com/assets/9691390/15022956/b52db13a-124b-11e6-813f-399ceb1e5fd0.PNG)

![img_2075](https://cloud.githubusercontent.com/assets/9691390/15022957/b62e5aee-124b-11e6-83ca-f813047ac523.PNG)

**Comment by xiuie** [comment]
@hiteshbheda If anything this is a gmail bug. :) We didn't design this. Likely you weren't notified by gmail because the reply didn't come directly from help@lomotif.com.

**Comment by hiteshbheda** [comment]
@xiuie Ok. Understood
