### ISSUE TITLE
[1.8.12] iPhone 6 / iOS 9.3.1 - Menu doesn't disappear during My Music Search - In My Music, open menu and then search for a song does not hide menu during search results / songs

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#373]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few images from Camera Roll
4. Click on Apply button at Top Right corner
5. Now Tap on My Music tab on Find Music screen
6. Click on Menu button Left to search bar
7. Type a keyword Which is available in song list (eg: Aaj phir)
8. Now, click on Search button from iPhone Keyboard
9. Check the result / songs on the screen

Expected result: Results / Songs should be available /display on the screen and My Music Menu should be disappear

Actual result: My Music Menu still available on the screen and searched result / song does not display (Actually, search works properly but searched results / songs are hidden behind My Music Menu, so it's not visible)

![img_2077](https://cloud.githubusercontent.com/assets/9691390/15025266/1433a5ae-1256-11e6-99fd-d6e716e4a386.PNG)

![img_2078](https://cloud.githubusercontent.com/assets/9691390/15025268/1466ff3a-1256-11e6-9544-c399c7a0a43c.PNG)

![img_2079](https://cloud.githubusercontent.com/assets/9691390/15025265/142c778e-1256-11e6-8217-5ae213bab8c0.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.12 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue now for iOS build [1.8.14] on iPhone 6 / iOS 9.3.1
