### ISSUE TITLE
[1.8.12] iPhone 6 / iOS 9.3.1 - Application Crash - Clicking on Messenger and Message at same time crash the app

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#376]
Frequency: Most of the time

Action:
1. Launch Lomotif
2. Click on Start
3. Select Camera Roll
4. Select few images from Camera Roll and tap on Apply button 
5. Click on My Music tab on Find Music screen
6. Select any song from My Music
7. Apply Filter
8. Tap on Adjust tab
9. Disable / OFF Watermark and Shake to shuffle option
10. On Song Wave, slightly forward the song by dragging wave 
11. Click on Export button at Top Right corner
12. Now, click on Messenger and Message icon at the same time

Expected result: Clicking on Messenger and Message should open and share lomotif on either Messenger or on Message

Actual result: Application crashes

[Pictures](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UY2g3MUN3d2RSQ0E)

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UOWhQX1dhbnN6Ukk)

**Comment by xiuie** [comment]
Similar to #358 where the fix will be to not allow them to click on multiple
