### ISSUE TITLE
iPhone 6S - Editor not loading certain high-res pictures

### ISSUE THREAD

**Issue by pmtheint** [Lomotif/lomotif-ios-issues#38]
For the same pic, Xiu could create a Lomotif of the picture but I couldn't. Tried both VSCO-edited version of the pic and the original quality one. Both gets loaded with black screen on editor. On a side note, most VSCO-edited pics in Lomotif appear quite pixelated.

**Comment by tsukisa** [comment]
@pmtheint can you please confirm if the problem still persist in version 1.6.9?

**Comment by benchang** [comment]
@pmtheint can you please confirm if this persists in version 1.7.2?

**Comment by pmtheint** [comment]
Still have problems. I noticed the problems exist in those pictures taken with professional camera. Those from phone work fine.

**Comment by benchang** [comment]
This requires investigation (I'll tag it as low for now)

**Comment by pmtheint** [comment]
Realised it's been fixed. While the photos are being loaded there is no feedback so it looks like a bug. Will fix UX for it.
