### ISSUE TITLE
[1.8.12] iPhone 6 / iOS 9.3.1 - Black screen appears - At Export screen, Clicking "Back" and "Close" button together creates Black screen 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#382]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing lomotif
3. Click on Export button at Top Right corner
4. Now, at Export screen, Click on "Back" and "Close" button together
5. Observe the screen with message and background
6. Click on Cancel on "Cancel Sharing" popup message screen
7. Check the screen now

Expected result: Clicking on Cancel on "Cancel Sharing" popup message screen should redirect user to Home screen

Actual result: Black screen appears

![img_2176](https://cloud.githubusercontent.com/assets/9691390/15222045/99940398-188b-11e6-9546-52c21ca5a715.PNG)

![img_2178](https://cloud.githubusercontent.com/assets/9691390/15222046/9995bf44-188b-11e6-8e34-ff5f9f04e09d.PNG)

![img_2179](https://cloud.githubusercontent.com/assets/9691390/15222047/99977e92-188b-11e6-87fb-37a28dc5657c.PNG)

![img_2180](https://cloud.githubusercontent.com/assets/9691390/15222044/999048f2-188b-11e6-88d1-bb2f68de06e4.PNG)

**Comment by xiuie** [comment]
Similar to #383

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can still reproduce this issue for build [1.8.14] on iPhone 6 / iOS 9.3.1

![img_2195](https://cloud.githubusercontent.com/assets/9691390/15241109/754f3c7a-190b-11e6-9820-34cfc17c1da1.PNG)

![img_2196](https://cloud.githubusercontent.com/assets/9691390/15241108/7517bea8-190b-11e6-91ce-3ff79f3a3114.PNG)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can reproduce this issue for build [1.8.26] on iPhone 6 / iOS 9.3.2
