### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Unable to add My Music Songs - Create lomotif using My Music song but song not added

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#384]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few images from Camera Roll
4. Click on Apply button at Top Right corner
5. Now Tap on My Music tab on Find Music screen
6. Select any song from the list
7. Create lomotif

Expected result: Lomotif should be played with added song

Actual result: Unable to add song from My Music

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3 and iPhone 5/9.3.1 for build [1.8.14].

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@b579dd8787edf227a06d91a65bfdb5d359311f4f
