### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Application Crash - Click on Motif and any Camera Roll folder at same time

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#390]
Frequency: Most of the time

Action:
1. Launch Lomotif
2. Tap on Start
3. Click on Motif tab and on any folder of Camera Roll tab (Facebook, Instagram, All Videos, All photos, Camera Roll, ...) at same time

Expected result: Either motif category videos should be opened or Camera Roll sub folder should be opened

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UcWdGRHYwOFFwT3M)

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@3d3c6cb308dc1666e2da5b46067510164811e7aa
