### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Few songs from Find Music continue loading - Select song from Find Music without internet continue loading

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#392]
Frequency: Every time

Action:
1. Turn off Internet / Wi Fi
2. Launch Lomotif
3. Tap on Start
4. Select few images from Camera roll
5. Tap on Apply button on Top Right corner
6. On Find Music screen Error Message displays as "The Internet connection appears to be offline"
7. Select any song below "Vespers" song or even "Vespers" song
8. Check the process on the screen

Expected result: Without internet selection of song should give error message

Actual result: Selecting song from a list gives continue loading process on the screen

![img_2232](https://cloud.githubusercontent.com/assets/9691390/15265948/e566d86e-19b1-11e6-91a1-6b1927327ca8.PNG)

**Comment by xiuie** [comment]
@hiteshbheda Do you face this problem on the live build? (The one in the App Store) Seems to be a separate list.

**Comment by hiteshbheda** [comment]
@xiuie I'll check it and will let you know.

**Comment by hiteshbheda** [comment]
@xiuie No, in live build without internet, songs list doesn't appear on the screen. So no option of selection.

But again, when we try to reload the songs list by dragging list down wards, loading process continues for infinite time.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.8.15] on iPhone 6 / iOS 9.3.1
