### ISSUE TITLE
[1.8.14] iPad 3 / iOS 9.3.1 -  Sticker is overlapping with Lomotif logo.

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#394]
Frequency: Every time

Action:
1. Launch Lomotif
2.Tap on Start
2. Select Video
3. Select any Music
4. Select the last Sticker from the stickers list
5. Select any filter

Expected result: Sticker should not  overlapped with Lomotif logo

Actual result: Sticker is overlapping with Lomotif logo

Please see screenshot : http://prnt.sc/b3vkjb

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.14] on iPhone 6 / iOS 9.3.1

**Comment by xiuie** [comment]
@pallavipillai Thanks.. Our dev is not responsible for this though so I will just close this and pass feedback on to interns who are designing the stickers.
