### ISSUE TITLE
[1.8.14] iPhone 6 / iOS 9.3.1 - Application Crash - On application launch screen, try to delete existing lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#397]
Frequency: Every time

Action:
1. Launch Lomotif
2. Make sure you have created few lomotifs earlier
3. Click on Delete (X) Button on existing lomotif to delete selected lomotif

Expected result: Clicking on Delete (X) button should delete that lomotif

Actual result: Application crash and when we launch lomotif app again, it has deleted previously tried molotif

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UaXcxZ2xhTlVsQjg)

**Comment by pallavipillai** [comment]
I am able to reproduce the issue on [1.8.14] iPAD 3/iOS 9.3.1

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@1db1eb4d2a85d4585cc361824de7b4d2966646e4
