### ISSUE TITLE
[1.8.15]  - Cannot use song from Music Discovery

### ISSUE THREAD

**Issue by tsukisa** [Lomotif/lomotif-ios-issues#399]
Frequency: Everytime

Action:
1. Launch Lomotif
2. Select some clips
3. Select a top song and press on tick button
4. Song doesn't get added to lomotif

Expected result: Song get downloaded and added to lomotif

Actual result: Song didn't get added to lomotif

**Comment by hiteshbheda** [comment]
@tsukisa @xiuie I can replicate this issue for build [1.8.15] on iPhone 6 / iOS 9.3.1

**Even Application CRASHES every time when selecting motifs and select song from My Music category.**

[Crash logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UYktNZnBZMXJ1Mjg)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa Similar to #384

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.15 on iPhone 5S iOS 8.4.1.
