### ISSUE TITLE
Thumbnails are not working in Find Music

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#4]
1. Open Lomotif and Click on Start button
2. Add any videos or photos and click on Tick(✓) mark
3. Click on Find Music then thumbnails are not showing. All are showing like in progress or empty

Please find herewith attached screenshots,
![img_0101](https://cloud.githubusercontent.com/assets/5388768/12230341/ddfe217e-b875-11e5-9445-4041a2a5a6f3.PNG)

![img_0102](https://cloud.githubusercontent.com/assets/5388768/12230351/efbadf56-b875-11e5-8428-ec1c62ca85ea.PNG)

**Comment by xiuie** [comment]
@ravichandranaidu I can't replicate this. Did it only happen once?

**Comment by tsukisa** [comment]
Probably slow connection?

**Comment by ravichandranaidu** [comment]
Connection is proper and it it's connected with broadband wifi. It's happening every time.
Please let me know your email so I can send you the video.

**Comment by xiuie** [comment]
@ravichandranaidu My email address: xiu[at]Lomotif.com

**Comment by tsukisa** [comment]
Seems like this is iPad only issue.

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@867bd04b33ff4c8cf7f44e596177188d999ac046
