### ISSUE TITLE
[1.8.15] Motif search does not load more data when scroll to bottom

### ISSUE THREAD

**Issue by tsukisa** [Lomotif/lomotif-ios-issues#400]
Frequency: Everytime

Action:
1. Launch Lomotif
2. Search motif
3. Scroll to bottom

Expected result: Load more motif search result

Actual result: Does not load more motif search result

**Comment by hiteshbheda** [comment]
@tsukisa @xiuie I can reproduce this issue for build [1.8.15] on iPhone 6 / iOS 9.3.1

**It loads only 30 motifs from all valid search.**

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.15 on iPhone 5S iOS 8.4.1.
