### ISSUE TITLE
[1.8.15] iPhone 6 / iOS 9.3.1 - Application crash - Create lomotif using any motifs without adding song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#402]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start button
3. Select few motifs from any Motif category
4. Click on apply button at Top Right Corner
5. Create lomotif WITHOUT adding any song
6. Check whether app crash or not

Expected result: Lomotif should be created without music

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UMHVMMFRvamNFYXc)

**Comment by xiuie** [comment]
I can reproduce this on my iPhone 6 / 1.9.2

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.15 on iPhone 5S iOS 8.4.1

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/8.3 for build [1.8.15]

After adding song getting message " Are you sure you want to proceed without adding Music?", after conform it showing crash.

**Comment by pallavipillai** [comment]
I can reproduce the issue on iPAD 3/9.3.1 for build [1.8.15]

Application crashes in both the situations -
1. when user create a video by selecting motif from My Motif and by adding a music.
2. when user create a video by selecting motif from My Motif and without adding a music.

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.16 on iPad mini iOS 8.3

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.16]

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.16] on iPhone 6 / iOS 9.3.1

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.18] on iPhone 6 / iOS 9.3.1.
