### ISSUE TITLE
[1.8.15] iPhone 5S / iOS 8.4.1 - Find Music - Application crashes when user tries to select song from My Music tab

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#403]
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Select any motif on the Albums screen and tap apply button
4. Switch to My Music tab on the Find Music screen
5. Select any song on the My Music tab from the Find Music screen and tap apply button

Expected result: Create screen appears after tapping apply button on the Find Music screen

Actual result: Application crashes

Video: [Recording #180.zip](https://github.com/Lomotif/lomotif-ios-issues/files/264950/Recording.180.zip)

Crash log: [Lomotif_2016-05-15-143019_iPhone.zip](https://github.com/Lomotif/lomotif-ios-issues/files/264946/Lomotif_2016-05-15-143019_iPhone.zip)

**Comment by Dipamit** [comment]
Not able to reproduce this issue on iPhone 5/8.3 for build [1.8.15]

Note: Application crash on selecting music from "Find Music" and save it.

**Comment by hiteshbheda** [comment]
@xiuie Similar to #402 

@xiuie @vysohanych The problem is with the Motifs. Whenever select any motif and create lomotif (With or Without Music), application crashes every time.

I can replicate this on iPhone 6 / iOS 9.3.1
