### ISSUE TITLE
[1.8.15] iPhone 6 / iOS 9.3.1 - Application Crash - Select song from My Music -> Albums / Artists / Playlists

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#406]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start button
3. Select few images or Videos from Camera Roll
4. Click on apply button at Top Right Corner
5. Select My Music tab
6. Click on Menu option available at Left to Search Music bar
7. Select Albums or Artists or Playlists
8. Select any song from selected option
9. Click on apply button at Top Right corner
10. Check whether application crash or not

Expected result: Song should be selected

Actual result: Application crash every time

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4Ud3FUVHVFSGRjajA)

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@7725876a94581f9e1d0a15427de67abe52fe6256

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't reproduce this issue for build [1.8.16] on iPhone 6 / iOS 9.3.1.

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.18] on iPhone 6 / iOS 9.3.1.
