### ISSUE TITLE
[1.8.17] iPad 3 / iOS 9.3.1 Not able to open Lomotif application, application crashes while opening

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#407]
Frequency - Always

Steps 
1. Install latest build of lomotif Application which is 1.8.17
2. Try to open the Lomotif Application

Actual Result - Application doesn't open, as soon as user opens the application, the application crashes

Expected Result - Lomotif Application should be opened

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue every time for build [1.8.17] on iPhone 6 / iOS 9.3.1

**Comment by tsukisa** [comment]
@hiteshbheda @pallavipillai thanks for reporting, please ignore 1.8.17 at the moment because the build is broken

**Comment by hiteshbheda** [comment]
@tsukisa Ok. I have started testing 1.8.16 again. Please let us know once 1.8.17 ready to test

**Comment by pallavipillai** [comment]
The issue is not reproducible for build [1.8.18] on iPad 3/iOS 9.3.1
