### ISSUE TITLE
Play music while in individual view

### ISSUE THREAD

**Issue by pmtheint** [Lomotif/lomotif-ios-issues#41]
The editor should play the portion of music relevant to the clip when in individual clip view.

**Comment by benchang** [comment]
it's playing the actual audio of the clip when you have the bubble selected

**Comment by benchang** [comment]
@paulyangzhiwen escalate this to critical if we really need it for version 1.7.2 (we would have to remove the build currently uploaded to apple)

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@543bb65c3c
