### ISSUE TITLE
[1.8.19] iPad 3 / iOS 9.3.2 When user click on + icon to add more video clips, the song get selected but user doesn't redirect to Create screen page immediately

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#422]
Frequency - Always
1. Launch app
2. Click on Start
3. Select a video from Camera roll
4. Select a music from Find Music tab
5. Click on apply on top right corner
6. On Create screen, click on + icon present on the left of the video clips
7. Select any video clip from Camera roll
8. Click on apply on top right corner

Actual Result - User doesn't get redirect to Create screen page immediately. It takes sometime to get redirect to Create screen page

Expected Result - User should be redirected to Create screen page immediately, after clicking on apply on top right corner.

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.19 on iPad mini 2 iOS 9.3.1.

**Comment by Dipamit** [comment]
I am able to reproduce this issue on iPhone 5/9.3.1 for build [1.8.19]

**Comment by hiteshbheda** [comment]
@xiuie I can replicate this issue for build [1.8.19] on iPhone 6 / iOS 9.3.2

**Comment by xiuie** [comment]
@pallavipillai Great bug.. Thanks!

**Comment by tsukisa** [comment]
@xiuie fixed with commit lomotif/lomotif-ios@01c1977fccd27ab2b6ca15a0208110bc51127230
