### ISSUE TITLE
[1.8.20] iPad 3 / iOS 9.3.2 Application crash when user search any music with the help of Search field in My Music tab

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#430]
Frequency - Always

Steps to reproduce - 
1. Launch the app
2. Click on Start
3. Select any 4-5 video clips from Camera roll tab or Motif tab
4. Click on apply on top right corner
5. Go to My Music tab
6. Type any music name in the Search field
7. Click on Search

Actual Result - Application get crash

Expected Result - Search Result should get display according to the search keyword entered in the Search field

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.20 on iPad mini 2 iOS 9.3.1.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.20] on iPhone 6 / iOS 9.3.2.

Frequency: Every time

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UbkxhY1AxUmJ0Tjg)
