### ISSUE TITLE
[1.8.20] iPhone 5C / iOS 9.3.1 On clicking on 'Camera roll' tab, Albums screen get closed and user get redirect to landing page of the application

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#431]
Frequency - Always

Steps to reproduce - 
1. Launch the app
2. Click on Start
3. Click on Motif tab
4. Now click on camera roll tab.

Actual Result :- Album screen get closed and take user to landing page.

Expected Result :- On clicking on camera roll tab, it should redirect to camera roll page.

Screenshot :- http://prntscr.com/b6a94c

Note - This issue exists when the user clicks on the Camera Roll tab and the focus of clicking is not proper, the focus of clicking is slightly outside the 'Camera Roll' tab

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.20 on iPad mini 2 iOS 9.3.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.20] on iPhone 6 / iOS 9.3.2

**Comment by xiuie** [comment]
@pallavipillai I think you're clicking on the "X", which closes the window. I think it works as designed / is invalid but let me know if you think otherwise
