### ISSUE TITLE
[1.8.20] iPhone 5c / iOS 9.3.1 Stickers get display 2 times in the stickers list

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#432]
Frequency - Always

Steps to reproduce -
1. Launch app
2. Click on Start
3. Add any video from Camera Roll
4. Add any music from Find Music tab
5. Go to Create screen
6. Enable the Stickers
7. Observe all the available stickers.

Actual Result - 
1. All stickers are displayed 2 times. 
2. The stickers available are different from the stickers available on other device for example, build [1.8.20] iPAD 3/iOS 9.3.2

Expected Result - 
1. All stickers should be available for only 1 time
2. The stickers available should be same in every device for the 1.8.20 build

![sticker](https://cloud.githubusercontent.com/assets/18537545/15426173/7203c3d4-1eaa-11e6-90c1-8adddfcea21e.jpg)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.20 on iPad mini 2 iOS 9.3.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.20] on iPhone 6 / iOS 9.3.2

**Comment by xiuie** [comment]
@tsukisa RW checked that as far as he can tell this is not an issue with the manifest.

**Comment by Dipamit** [comment]
Able to reproduce this issue on iPhone 5/9.3.1 for build [1.8.24]

Note: Not able to reproduce this issue on iPhone 5/8.3 but only few stickers are displayed in box.
![img_3219](https://cloud.githubusercontent.com/assets/17335200/15470267/41ee1f90-210d-11e6-916e-59ec95eee0d1.PNG)

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can't replicate this issue for build [1.8.24] on iPhone 6 / iOS 9.3.2
