### ISSUE TITLE
[1.8.20] iPad 3 / iOS 9.3.2 When internet is off on device, loading sign never ends on Find Music page, when user tries to proceed without adding any song.

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#433]
Frequency - Always 

Steps to reproduce - 
1. Launch app
2. Click on Start
3. Add any video from Camera Roll
4. Switch off the internet on the device.
5. Click on any song on Find Music Tab
6. Click on 'OK' on 'Could not load review' error message
7. Click on apply button on top right corner
8. Again click on 'OK' on 'Could not load review' error message

Actual Result - Loading sign appears which never ends.

Expected Result - After clicking on Apply button on top right corner, message should display 'Are you sure you want to proceed without adding music'

Screenshot - 
![loading_1](https://cloud.githubusercontent.com/assets/18537545/15431010/83f2d812-1ec5-11e6-97c0-45344d479a46.JPG)

**Comment by xiuie** [comment]
Very interesting @Pallavinpillai! Just realized many may think they can no longer proceed without internet connection. They can deselect the song but it's pretty non-intuitive. Especially when the message prompts them to select another song which doesn't solve the problem.

**Comment by tsukisa** [comment]
fixed with commit lomotif/lomotif-ios@3cc9d24dc71e634936366ebfde11e783adf0a57f
