### ISSUE TITLE
[1.8.22] iPad 3 / iOS 9.3.2 When user clicks on + icon, new video clip doesn't get added

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#434]
Frequency - Always

Steps to reproduce -
1. Launch app
2. Click on Start 
3. Add 4 videos from camera roll
4. Click on apply on top right corner
5. Add any music from Find Music tab
6. Click on apply on top right corner
7. On create screen, click on + icon present near the video clips
8. Select any 1 video from camera roll
9. Click on apply on top right corner
10. On create screen, observe the video clips

Actual Result - The new video clip added by clicking on the + icon, doesn't display.

Expected Result - The new video clip added by clicking on the + icon should be added successfully and should get display

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for iOS App Version 1.8.4 build [1.8.22] on iPhone 6 / iOS 9.3.2

**Comment by xiuie** [comment]
@pallavipillai did you wait till the whole video plays? Realize the 5th thumbnail isn't visible, but the 5 video clips play

**Comment by tsukisa** [comment]
@xiuie it's UI bug, list doesn't get refresh immediately

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@344a4045622f788c51fce7faf29db8dfd73a4dcd
