### ISSUE TITLE
[1.8.24] iPhone 5/8.3 - Application crash, when photo permission is disable from device settings and user click on Lomotif logo on home screen

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#438]
Frequency - Always

Steps to reproduce -
1. Go to iOS device settings.
2. Search for Lomotif app
3. Disable the Photo persmission for Lomotif app
4. Launch the Lomotif app
5. Click on Lomotif logo on home screen

Actual Result - Application get crash.

Expected Result - Application should not get crash.

![settings_1](https://cloud.githubusercontent.com/assets/18537545/15476006/787918ae-212a-11e6-824e-eff2185025f8.png)

![homescreen_2](https://cloud.githubusercontent.com/assets/18537545/15476025/8f1315e2-212a-11e6-945e-e3e9f1995ba9.png)

**Comment by pallavipillai** [comment]
@xiuie - Please ignore this issue. I was facing some problem while reporting the issue, so I mistakenly reported the issue 2 times. The original issue is here - 
https://github.com/Lomotif/lomotif-ios-issues/issues/439

Thank you

**Comment by hiteshbheda** [comment]
@xiuie Duplicate of #439
