### ISSUE TITLE
[1.8.24] iPhone 6 / iOS 9.3.2 - Wrong Lomotif length - Create video of 1-2 sec from lomotif logo and then insert video in Lomotif will display wrong time

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#446]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap and Hold Lomotif App icon to create video 
3. Create video of 1 - 2 seconds only
4. Now Click on Start button
5. Select All Videos folder from Camera Roll -> Albumm screen
6. Select recently captured video of 1 - 2 seconds
7. Click on Apply button from Top Right corner
8. Select any song from Find Music or My Music
9. Click on Apply button from Top Right corner
10. Create lomotif
11. Now tap on Adjust Tab
12. Change the length of created lomotif from 15 seconds to Minimum 3 seconds
13. Play created lomotif
14. Observe lomotif length whether it is 3 seconds or not

Expected result: Created lomotif should be of minimum 3 seconds length OR In Adjust tab, it should also display the length min, 1 second instead of 3 seconds

Actual result: Lomotif is of original length (1 - 2 seconds) AND Adjust tab allows user to select video length of minimum 3 seconds

**Comment by xiuie** [comment]
@hiteshbheda we don't want them to create videos less than 3 secs if they're making a montage.. hence adjust is min 3secs. But of course if they're video is shorter than 3secs, we'll still allow them to export. @pmtheint just for info or in case we can think of something better.

**Comment by pmtheint** [comment]
Agreed that it works as designed.

**Comment by hiteshbheda** [comment]
@xiuie @pmtheint Ok. Can we do one thing like when user input video less than 3 sec at that time any alert message (input video should be min of 3 sec in length) or something else?

Or if it works correctly now then it's fine!

**Comment by pmtheint** [comment]
@hiteshbheda thing is, the algorithm recalculates based on the duration change (i.e. when you put it at 7 sec, it calculates the clips based on a 7-sec total duration) so in most cases where there are (fewer clips), the actual output will be slightly less than the duration set.

**Comment by hiteshbheda** [comment]
@pmtheint Ok. Thanks!
