### ISSUE TITLE
[1.8.26] iPhone 6 / iOS 9.3.2 - Stickers not available - Create Lomotif and Enable stickers tab doesn't load stickers

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#449]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Start
3. Select few motifs from any Motif category
4. Click on Apply button at Top Right corner
6. Select any song from Find Music
7. Click on Apply button at Top Right corner
8. Create lomotif
9. Now, Enable (ON) Stickers Tab
10. Check whether all stickers load or not

Expected result: By Enabling stickers tab, all stickers should be loaded

Actual result: Stickers not loaded / displayed

![img_2520](https://cloud.githubusercontent.com/assets/9691390/15590275/789d7294-23b4-11e6-9dfc-0c4ec1a5fdf5.PNG)

**Comment by tsukisa** [comment]
fixed with commit Lomotif/lomotif-ios@ba7081ca4cb9cdbef55f417f11114cbf8e21610e

**Comment by hiteshbheda** [comment]
@xiuie @tsukusa I can't replicate the same issue but still only few stickers are visible for build 1.8.29 on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie @tsukisa I can again replicate this issue for build [1.8.29] on iPhone 6 / iOS 9.3.2

**Currently, it is not showing any sticker in the list. Yesterday few stickers were present.**

**Comment by Dipamit** [comment]
Able to reproduce this issue on iPhone 5/8.3 and iPhone 5/9.3.1 for build [1.8.29]

Note: No stickers are displayed in list.
