### ISSUE TITLE
[1.8.26] iPhone 6 / iOS 9.3.2 - Zoom in / out doesn't save - Create Lomotif and pinch Zoom in / out on specific video / image

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#454]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Start
3. Select few motifs from any Motif category
4. Click on Apply button at Top Right corner
6. Select any song from Find Music
7. Click on Apply button at Top Right corner
8. Create lomotif
9. Now, tap on the first motif from different frames
10. Zoom In / Zoom out the selected motif on the screen
11. Click on Home button and Save lomotif
12. Reopen the saved lomotif 
13. Observe the Zoom in / zoom out saved changes applied or not

Expected result: Previously made changes like Zoom in / Zoom out should be applied on the lomotif

Actual result: Zoom In / Zoom Out effect doesn't save in the lomotif

![img_2549](https://cloud.githubusercontent.com/assets/9691390/15628174/6fe284c2-2518-11e6-9122-efcb64aa35b5.PNG)

![img_2550](https://cloud.githubusercontent.com/assets/9691390/15628173/6fe1c118-2518-11e6-923d-42a7f71a564c.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build 1.8.29 on iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.29 on iPad 2 iOS 9.3.2

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.33 on iPhone 5S iOS 8.4.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.33] on iPhone 6 / iOS 9.3.2
