### ISSUE TITLE
[1.8.26] iPad Mini / iOS 9.3.2 - Error -3000 on export - Export a video while disconnected from the internet

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#456]
Frequency: Sometimes

Action:
1. Launch Lomotif
2. Click on Start
3. Launch project with Motifs (Preview looks normal)
4. Turn on airplane mode
6. Try to export

Expected result: Lomotif is exported 

Actual result: Error -3000

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.26] on iPhone 6 / iOS 9.3.2

Does it only occur with iPad?

**Comment by hiteshbheda** [comment]
@xiuie Its similar to #452

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.29 on iPad 2 iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.29] on iPhone 6 / iOS 9.3.2
