### ISSUE TITLE
[1.8.26] iPad Mini / iOS 9.3.2 - Forever "Prcoessing" - D/C when using iCloud clips

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#457]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Start
3. Select 10 iCloud clips
4. Select song
5. Turn on Airplane mode
6. Turn off Airplane mode

Expected result: Lomotif clips are downloaded once airplane mode is off

Actual result: Blank/black screen with a never ending "Processing" sign.. When attempt to export, "Saving Lomotif to Camera Roll" stays on screen forever

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.26] on iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.29 on iPad 2 iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.29] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.31] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.33] on iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.8.36 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.36] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

In fact, I don't iCloud folder in Camera Roll tab.
