### ISSUE TITLE
[1.8.29] iPhone 5/8.3 : Application crash on selecting Motif.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#458]
Frequency: Always
1. Open application and tap on start.
2. Tap on Motif and open any category.
3. Tap on "back" quickly and again open any category from motif.

Expected result: Motif category should open

Actual result: Application crash.

[Crash Log and video.zip](https://github.com/Lomotif/lomotif-ios-issues/files/295014/Crash.Log.and.video.zip)

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/9.3.1 and iPad mini/9.3.2 for build [1.8.29]

**Comment by pallavipillai** [comment]
I am able to reproduce the issue for build 1.8.29 on iPAD mini/9.3.2 and iPAD 3/9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.29] on iPhone 6 / iOS 9.3.2

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UMXNjUWRLdzE5cXM)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.30] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.31] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.32] on iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.33 on iPhone 5S iOS 8.4.1
