### ISSUE TITLE
[1.8.29] iPhone 5/8.3 Error -11847 on export video and minimize app.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#459]
Frequency: Always
1. Open app and tap on Start
2. Tap on Camera roll and select some photos/videos
3. Tap on Next and select any song.
4. Tap on "Export" from top right.
5. Minimize app while export process is running.

Expected result: Export process should run while open app after minimize.

Actual result: Error 11847 occurs
![img_3286 1](https://cloud.githubusercontent.com/assets/17335200/15778661/336ed21a-29b5-11e6-9f69-1e34233667bf.PNG)

Note: Not able to reproduce this issue on iPhone 5/9.3.1
.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.29] on iPhone 6 / iOS 9.3.2

**Comment by tsukisa** [comment]
This is not a bug. Apple doesn't allow OpenGL to run on background therefore export will fail when app is minimize.
