### ISSUE TITLE
[1.8.31] iPhone 6 / iOS 9.3.2 - Audio continue playing - Play any camera roll video and stop it will continue playing song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#465]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select Camera Roll Tab on Album screen
4. Open any folder which contains video
5. Click on Play button (center of the video) to start playing (Don't select video)
6. Now again tap at Center to stop playing video
7. Check whether audio playing continue or stopped

Expected result: Clicking on Stop button should stop the video / audio

Actual result: By clicking on Stop button, still audio playing continue

![img_3106](https://cloud.githubusercontent.com/assets/9691390/15860252/e0ca402e-2ce5-11e6-8c64-09a949762b80.PNG)

![img_3105](https://cloud.githubusercontent.com/assets/9691390/15860319/300effc6-2ce6-11e6-9e18-50abcde8237b.PNG)

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.31 on iPad mini iOS 8.3

**Comment by tsukisa** [comment]
same issue as #465

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.36] on iPhone 6 / iOS 9.3.2
