### ISSUE TITLE
[1.8.31] iPhone 6 / iOS 9.3.2 - Audio overlapping - Play any camera roll video and then create lomotif with motifs and Find Music / My Music song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#466]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select Camera Roll Tab on Album screen
4. Open any folder which contains video
5. Click on Play button to start playing 
6. Now tap on Motif tab on Albums screen
7. Select few motifs and click on Apply button at Top Right corner
8. On Find Music / My Music tab, Tap on any song
9. Check whether both the songs overlapping or not

Expected result: Both the song should not overlap

Actual result: Song from Video and Find Music / My Music overlapped

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.31 on iPad mini iOS 8.3

**Comment by tsukisa** [comment]
same issue as #465
