### ISSUE TITLE
[1.8.31] iPad mini / iOS 8.3 - Create - Play button doesn't appear when lomotif finished playing

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#469]
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Switch to Motif tab on the Albums screen
4. Select some motifs on the on the Albums screen
5. Tap apply button on the on the Albums screen
6. Select any song on the on the Find Music screen
7. Tap apply button on the on the Find Music screen
8. Wait when created lomotif finished playing

Expected result: Play button should appear when lomotif finished playing

Actual result: Play button doesn't appear when lomotif finished playing

Video: [Recording #50.mp4.zip](https://github.com/Lomotif/lomotif-ios-issues/files/302938/Recording.50.mp4.zip)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.8.31] on iPhone 6 / iOS 9.3.2

But without Play button, when we click anywhere on the screen it starts playing
