### ISSUE TITLE
[1.8.31] iPhone 6 / iOS 9.3.2 - Application Crash - Changing audio from created lomotif and swapping between My Music and Find Music tabs

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#470]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few motifs and apply from top right corner
4. Now Tap on My Music category
5. Select any song and apply from top right corner
6. Scroll down the screen
7. At Bottom of the screen, tap on audio change icon
8. Select any song from My Music tab
9. Again tap on Audio change icon
10. Tap Find Music and My Music (Continue swapping)
11. Observe whether application crash or not

Expected result: Application should not crash and swapping between My Music to Find Music should work

Actual result: Application crash

[Crash Logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UdFZsbXBfV0pwMXM)

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.31 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue every time for build [1.8.32] on iPhone 6 / iOS 9.3.2

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build [1.8.32] on iPhone 6 / iOS 9.3.2

Application crash Every time for following steps:
1. Select 10 to 12 videos from iCloud folder of Camera roll
2. Add song from My Music
3. Click on Audio change icon at Bottom of the screen
4. Again select any other song from My Music
5. Again, tap on Change audio icon
6. Swap between My Music and Find Music

Actual result: Application crashes every time

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.33] on iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.33 on iPhone 5S iOS 8.4.1
