### ISSUE TITLE
[1.8.32] iPhone 6 / iOS 9.3.2 - Unable to add audio - My Music -> Select Albums / Artists / Playlists -> Add any song from this category

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#471]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select few motifs and apply from top right corner
4. Now Tap on My Music tab
5. Tap on Menu button of My Music available at Left to Search Music
6. Select any category either Albums OR Artists OR Playlists (Don't select Songs category)
7. Select any song from Albums OR Artists OR Playlists
8. Apply from top right corner
9. Play lomotif 
10. Check whether the song / audio available or not in lomotif

Expected result: Selected Audio from Albums OR Artists OR Playlists should be added

Actual result: Audio not added

![img_3115](https://cloud.githubusercontent.com/assets/9691390/15884321/4b8a96d4-2d6d-11e6-8e54-ef6ebb372cc1.PNG)

**Comment by pallavipillai** [comment]
Able to reproduce the issue for build 1.8.32 on iPAD 3/iOS 9.3.2 and iPhone 6/iOS 9.3.2

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.32 on iPad mini iOS 8.3

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.8.33] on iPhone 6 / iOS 9.3.2
