### ISSUE TITLE
[1.8.32] iPhone 6 / iOS 9.3.2 - Audio not added - Create lomotif using camera roll video (with audio) doesn't add audio

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#473]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. Select any video from camera roll which has audio with video
4. Tap on Apply button at Top Right corner
5. Don't add any audio from My Music / Find Music
6. Create lomotif
7. Play lomotif 
8. Check whether the song / audio available or not in lomotif

Expected result: Lomotif should contain the audio with video as it was inbuilt

Actual result: Audio not added

**Comment by Dipamit** [comment]
I am not able to reproduce this issue on iPhone 5/8.3 for build [1.8.32]

**Comment by vysohanych** [comment]
I can reproduce it on build 1.8.32 on iPad mini iOS 8.3
