### ISSUE TITLE
[1.8.33] iPhone 5S / iOS 8.4.1 - Albums - Motifs are not selected after collapsing the folder where they were selected

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#476]
Frequency: Every Time

Action:
1. Open the application
2. Tap START button on the home screen
3. Switch to Motif tab on the Albums screen
4. Expand any folder on the Albums screen
5. Select some motifs
6. Colapse the current folder

Expected result: Motifs should be selected after collapsing the folder where they were selected

Actual result: Motifs are not selected after collapsing the folder where they were selected

Video: [Recording #224.zip](https://github.com/Lomotif/lomotif-ios-issues/files/310681/Recording.224.zip)

**Comment by hiteshbheda** [comment]
@xiuie @vysohanych It looks similar to #464

**Comment by xiuie** [comment]
thanks vysohanych :) but i will be closing this for now.
