### ISSUE TITLE
Instagram connection error.

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#486]
Instagram connection error.

When trying to connect to Instagram from Lomotif, the following error message is displayed.

{"code":403,"error_type":"OAuthForbiddenException","error_message": "You are not a sandbox user of this client"}

Able to log in to instagram from PC and instagram's native application for iPad with the same credentials.

Steps to reproduce:
1. Open Lomotif.
2. Tap 'start'.
3. In the 'Albums' screen, choose 'Instagram' from the displayed options.
4. Enter the credentials in the login page displayed.

Find attached the screenshot of the error message.

Device : iPad Mini.
iOS Version : 8.4.1
Lomotif Version : 1.8.7 build 1.8.29

Reported by Selvi/Portnov

**Comment by hiteshbheda** [comment]
@xiuie I can't replicate this issue for build [1.8.33] on iPhone 6 / iOS 9.3.2

**I have tried by logged out from linked account of Lomotif app and then again followed the steps. When i click on Instagram folder, it asks for credentials. By entering correct credentials, I'm able to see the content (videos) of Instagram.**

**Comment by vysohanych** [comment]
I can't reproduce it on build 1.8.34 on iPad mini 2 iOS 9.3.2
