### ISSUE TITLE
[1.6.9] iPhone 6/9.1 - Application crashed while clearing/deleting any video in the Home Screen (Critical Bug)

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#49]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap cross button on created movies on the home screen
3. Application crashed

When a user tries to clear the movies from this App home screen on tapping cross button of any video then Application is crashed.

Expected Result: Application should not crash

Actual Result: App crashing all the time

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@88f994a0908749cba78abd21487325349b41bd3e
