### ISSUE TITLE
[1.8.36] iPhone 6 / iOS 9.3.2 - Black screen appear - Create lomotif by adding Facebook folder images and video

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#497]
Frequency: Every time

Action:
1. Launch Lomotif
2. Tap on Start
3. On Albums screens, Tap on Camera Roll
4. Tap on Facebook folder to expand it
5. Select all images and videos from the Facebook folder (I have added total 27 images and videos)
6. Don't add any song 
7. Create lomotif
8. Now on the screen check whether added all the images and videos are playing or not

Expected result: All the images and videos added from facebook folder should be played

Actual result: 
1. All the images are added but all are not playing. 
2. Clicking on few images black screen appears

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.8.36 on iPad mini iOS 8.3.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
