### ISSUE TITLE
Turnoff watermark then it shows error message.

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#5]
1. Open Lomotif App and click on Start button
2. Add photos/videos then click on tick (✓) button
3. Add any music into selected photo/video by using Use 30 seconds preview option 
4. Now try to turnoff watermark by toggle button then it shows error message

Find the error screenshot
![img_0103](https://cloud.githubusercontent.com/assets/5388768/12230559/5ac73140-b877-11e5-897d-3965eee4fea3.PNG)

**Comment by xiuie** [comment]
@ravichandranaidu This connects to the App Store. It only works once the build is live on Apple, and cannot work on test builds
