### ISSUE TITLE
[1.6.9] iPhone 6/9.1 - Videos are not playing in categories itself and problem in selecting the videos in that category

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#50]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Start 
3. Click on Motif
4. You will see some categories, select nicki minaj
5. Tap in the center of any video in this category all videos will be played
6. Now minimize this category and select other category i.e. happy birthday!
7. Tap on the center of any video
8. You can see the video will not play.
Second bug
9. Select and mark any other video in that category, the video will not be selected, 
In case if selected then tap multiple times in the center of any unselected video (that must not play, select any video that is unable to play. Try this until they are unable to select. 

The videos are playing in some categories and they are not playing in some other categories.

Expected Result:  Video should be play in all category and able to select

Actual Result: Some videos are unable to play and select

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@41c1bb525166fc93080cfcdfda38bb52bda390b5
