### ISSUE TITLE
[1.9.0] iPhone 6 / iOS 9.3.2 - Wrong icons at Landing page - Home button and Media icons display at App landing page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#504]
Frequency: Every time

Action:
1. Launch Lomotif
2. Check whether Media and Home button icon display on the landing page or not

Expected result: Home button and Media icon should not be displayed on landing page.

Actual result: Home button and media icon available at landing page; Home button icon doesn't work

![img_3502](https://cloud.githubusercontent.com/assets/9691390/17014738/caf47a46-4f43-11e6-8968-701ffa1a0181.PNG)

**Comment by xiuie** [comment]
@hiteshbheda Nothing should happen if you click Home as you're already on Home.. Clicking Media should bring you to the Lomotif feed. Does it work this way?

**Comment by hiteshbheda** [comment]
@xiuie Yes, it works as you say
