### ISSUE TITLE
[1.9.0] iPhone 6 / iOS 9.3.2 - Getting error on Motif tab - Create lomotif with motif will give Error message

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#505]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on start
3. On Albums screen switch to Motif tab
4. Check whether all motifs display or not

Expected result: All motifs should be displayed on motif tab

Actual result: 
1. No motifs available in Motif tab. 
2. Getting error message "The data couldn't be read because it isn't in the correct format"

![img_3503](https://cloud.githubusercontent.com/assets/9691390/17014878/9b690304-4f44-11e6-95c0-2aeb658841e6.PNG)

**Comment by xiuie** [comment]
I can't reproduce this in my  iPhone 6 / iOS 9.3.2

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.0 on iPad mini iOS 8.3.

**Comment by testershub** [comment]
I can't reproduce this issue for build [1.9.0] on iPhone 6S / 9.3.2, iPhone 6 Plus / 9.2.1 and iPad Mini 3 / 9.3.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.9.0] on iPhone 6 / iOS 9.3.2
