### ISSUE TITLE
[1.6.10] iPhone 6/9.1 - Music is not playing in video

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#51]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select video files
4. Select Audio files

You will find that audio is not playing with video files

Expected Result: Audio should be played with video
Actual Result: Audio in not playing

**Comment by xiuie** [comment]
@rahulskylo I can't replicate this. Do you mind sending us a quick video of this?

**Comment by rahulskylo** [comment]
ok i will make a video and send you
