### ISSUE TITLE
[1.6.10] iPhone 6/9.1 - Font and color list not working

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#52]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Click Setting
3. Click Font list
and
4. Color List

The fonts and colors are clickable but not set as default.  Although selecting the CARTON font and RED color from list When user tries to create the movie by selecting video and audio and enter any title in "Enter A Title" field then the by default font and color will be seen HelveticaNeue as font and white color. That should not be happen. 

Expected Result: Either the Font and Color list should remove (or make unclickable) or on selecting the font and color from the list should be set as default.

Actual Result: While selecting the fonts and colors they are not set as default.

**Comment by tsukisa** [comment]
Font list and color list under settings are for testing purpose only

**Comment by Dipamit** [comment]
I am able to reproduce this issue. on iPhone 5 with 8.3.
