### ISSUE TITLE
[1.6.10] iPhone 6/9.1 - Terms of Use & Privacy Policy - Wrongly links to Lomotif.com homepage

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#53]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Click Setting
3. Click Term of Use & Privacy Policy 
4. Click on Facebook icon
5. Click back button
On clicking back button it should navigate to previous page i.e. Term of Use & Privacy Policy but it is navigated to Setting page. That should not happen

Expected Result: On clicking back Term of Use & Privacy Policy page should be open
Actual Result: Setting page is opening

**Comment by xiuie** [comment]
@tsukisa Seems like in1.6.10 Terms of Use & Privacy Policy is pointing to lomotif.com homepage instead of TOC.
