### ISSUE TITLE
[1.9.1(1.9.6)] iPhone 6S / 9.3.2, iPhone 6 Plus / 9.2.1- Alignment options are missing for "Title". 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#547]
Frequency: Every time

Action: 
1: :Launch the app.
2: Tap on "START" and select any motifs from any category.
3: Skip the music and proceed to "Create" screen.
4: Tap on "Title" and check if alignment options are missing.

Expected result: Alignment options "Left, right and Center" should be displayed for title.

Actual result: Alignment options are missing for "Title".

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.6] on iPhone 6 / iOS 9.3.3

**But i think it's design issue which is not yet implemented and not a bug**

**Comment by xiuie** [comment]
@testershub @hiteshbheda Yes title alignments have not been introduced yet on iOS
