### ISSUE TITLE
[1.6.10] iPhone 6/9.1 - Mailing service not working

### ISSUE THREAD

**Issue by rahulskylo** [Lomotif/lomotif-ios-issues#55]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Click Setting
3. Click Term of Use & Privacy Policy 
4. Scroll Down and Click on Android
Here are two issues
1) Do not enter email id and click Get Lomotif (Android), It should give an error message but there is no error message is coming.
2) Enter any registered email id click Get Lomotif (Android). Check your Mailbox there is no any such mail found regarding Android link

Expected Result: If there is no such app on android then a message of unavailability of app should display to user.
Actual Result: there is no such message

**Comment by xiuie** [comment]
@rahulskylo terms of use is currently being directed to the wrong page.
