### ISSUE TITLE
[1.9.6] iPhone 6 S/9.3.2- Continuous loading is displayed when user exports a lomotif which has no images/videos.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#550]
Frequency: Every time.

Action:
1: Launch the app.
2: Tap on "START", user will be navigated to "Albums" folder.
3: Select some image/video from camera folder.
4: Complete the process till "Create" screen.
5: Tap on home icon >> "Yes" option of the pop up message.
6: Navigate to the camera folder and delete the added image/video.
7: Navigate back to home screen and tap on the created lomotif of which image/video is deleted.
8: Pop up message "Lomotif project could not be loaded.." will be displayed, tap on "OK" option.
9: Tap on "Export" option and check if continuous loading is displayed.

Expected result: User should not be able to tap on "Export" option when there is no image/video added in the project. Pop up message should be displayed to the user informing him that adding image/video is mandatory before exporting.

Actual result: Continuous loading is displayed on the screen.

Refer screenshot for more details.

**Comment by testershub** [comment]
![continuousloading](https://cloud.githubusercontent.com/assets/18608449/17287818/743a53f6-57ef-11e6-86f8-3fcc9aba0442.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.6] on iPhone 6 / iOS 9.3.3

Issue looks similar to #533

**Comment by xiuie** [comment]
@hiteshbheda It's a different issue as we fixed the former. It doesn't crash now on launching project, but will hang on export.

**Comment by hiteshbheda** [comment]
@xiuie Ok. Thanks for update!

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.7] on iPhone 6 / iOS 9.3.3

**Comment by testershub** [comment]
@xiuie Issue is resolved on the latest build [1.9.9].
