### ISSUE TITLE
[1.9.6] iPhone 6 / iOS 9.3.3 - Export and share lomotif on Twitter does not redirect to Twitter app - Open existing lomotif and export it on Twitter

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#554]
Frequency: Every time

Action:
1. Launch Lomotif
2. Open any existing lomotif
3. Click on Export button on Top Right of the screen
4. Share lomotif on Facebook or Instagram and observe behavior, It will redirect you on Facebook and Instagram app
5. Now, share lomotif to Twitter, User will get confirmation message about twitter sharing
6. Check whether after sharing lomotif on Twitter, user is redirected to Twitter app or not as like Instagram and Facebook

Expected result: After sharing lomotif on Twitter, user should be redirected to Twitter app as like the behavior of Facebook and Instagram sharing

Actual result: Lomotif shared successfully but user is not redirected to Twitter app (Twitter app is not opening)

**NOTE: Behavior should be same for Facebook, Instagram and Twitter. If in Facebook and Instagram sharing, App opens then with Twitter also app should be opened.**

**Comment by xiuie** [comment]
@hiteshbheda Instagram doesn't allow sharing without launching the app. Otherwise, we would prefer not to direct users to another app.

**Comment by hiteshbheda** [comment]
@xiuie Ok. Agree. Thanks! :+1:
