### ISSUE TITLE
[1.9.7] iPhone 5/8.3 Error 404 page displayed while login Instagram.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#566]
Frequency: Always
1. Open application and tap on Setting.
2. Tap on Linked account and Sign Out from Instagram.
3. Close application and open again and tap on Start.
4. Tap on Instagram and enter valid credential.
5.  Verify Error page displayed.
6. After tapping on Close sign from top left page navigate to Instagram.

Expected result: User should login without displaying error page.

Actual result: Error 404 displayed while login Instagram.

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on iPhone 5S iOS 8.4.1 on build 1.9.7

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.7] on iPhone 6 / iOS 9.3.3

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.9

**Comment by testershub** [comment]
@xiuie Issue is resolved on latest build [1.9.9].

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4
