### ISSUE TITLE
[1.9.7] iPhone 6 S/9.3.2- User is not able to select the desired section of the song on the create screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#569]
Frequency: Every time.

Actions:
1: Launch the application.
2: Tap on "START" button,  user will be navigated to "Add Photos & Video" screen.
3: Add some video/image and navigate to the next screen.
4: Tap on any song- more than 2 minutes of duration, it will play.(keep a track of duration in the song preview).
5: Tap on "Next" icon, user will be navigated to "Create" screen.
6: Scroll on the bar till the desired section of the song and check if song plays for next 15-30 seconds(as per user has selected).

Expected result: User should be able to select the desired section of the song.

Actual result: User is able to select only the first 30 seconds of the song, if user scrolls till the middle of the song the remaining 15 seconds song is getting played and for remaining 15 seconds only images/videos are getting played without any music.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on iPhone 5S iOS 8.4.1 on build 1.9.7

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.7] on iPhone 6 / iOS 9.3.3

**Comment by xiuie** [comment]
@testershub For featured songs in "Find Music" page, it's only 30secs long. On "My Music" it is however long the song is. I will reopen this bug if the sogn selected is a more than 2 minute song from My Music page.
