### ISSUE TITLE
[1.6.10] iPhone 6/9.2 - Music Search Results - view the middle of the list

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#57]
After scrolling down, then performing a search, the results don't jump back to the top, ie. view appears in the middle of the list.

How to replicate:
1. Create Lomotif
2. Scrub down to reveal more songs
3. Search keyword

Expected result: Shows top results
Actual results: We're shown a view of the middle of the list.

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@92c272960fc94fbb21fdc78f1d43ad43e77c8f58
