### ISSUE TITLE
[1.9.7] iPhone 6 S/9.3.2- Irrelevant "Time line" view is displayed when user clones/duplicates the existing video.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#570]
Frequency: Every time.

Action:
1: Launch the application.
2: Tap on "START" button, user will be navigated to "Add Photos & Videos" screen.
3: Select 2-3 slow-mo videos and navigate to "Create" screen.
4: Clone/Duplicate the added videos by drag-drop on "+" icon.
5: Check if irrelevant "Time line" frame is displayed.

Expected result: User should be able to clone the video and it should appear in the end of the videos/images.

Actual result: Irrelevant "Time line" frame is displayed when user clones the slow-mo video.

**Comment by xiuie** [comment]
@testershub Thanks for highlighting this. You have a point but currently it's work as designed.
