### ISSUE TITLE
[1.9.7] iPhone 6S / 9.3.2 - Error message "Could not load preview..." is displayed when user taps on music on "Find Music" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#576]
Frequency: Every time

Action:
1: Launch the app.
2: Turn off the internet connection.
3: Tap on "START" and select any motifs from any category.
4: Tap on any song(Could not load preview... will be displayed)
5: Turn on the internet connection and tap on same song.(Could not load preview... will be displayed)
6: Refresh the "Find Music" screen and tap on same song.
7: Check if error message "Could not load preview..." is displayed.

Expected result: Preview should get played when user taps on music in online mode.

Actual result: Error message "Could not load preview..." is displayed when user taps on music on "Find Music" screen even when user is in online mode.

Refer following video for more details:
http://www.screencast.com/t/AJrDv6VOdeeW

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.8] on iPhone 6 / iOS 9.3.3

**Comment by testershub** [comment]
@xiuie I can't reproduce the issue for build [1.9.9].

**Comment by Pankaj-Testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2
