### ISSUE TITLE
[1.9.8] iPhone 6S / 9.3.2 - Motifs are auto-played when user search for "White tiger" on "Motif" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#580]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" button >> "Motif" tab.
3: Search for "White tiger".
4: Check if motifs are auto-played for "White tiger".

Expected result: Motifs should not auto-played when user search for any "White tiger" motifs.

Actual result: All motifs are auto-played when user search for "White tiger".

**Comment by xiuie** [comment]
Yes Motifs are now autoplayed. It's a new feature for certain motifs.
