### ISSUE TITLE
[1.9.8] iPhone 6S/9.3.2 - List of more than 50 songs are displayed on "Find Music" tab.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#582]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select any motif from any category.
3: Proceed to "Find Music" screen.
4: Scroll down the screen to load more songs.
5: Check if more than 50 songs gets loaded.

Expected result: Up to 50 songs should be displayed.

Actual result: List of more than 50 songs are displayed on "Find Music" tab.

**Comment by xiuie** [comment]
Expected behavior as we have increased the featured songs.
