### ISSUE TITLE
[1.9.8] iPhone 6S/ 9.3.2 - Video is getting duplicated on create screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#585]
Frequency: Every time.

Action:
1:Launch the app.
2:Tap on start  button.
3:Add one lomotif with one video.
4:Select loading music and press on next option. 
5:Loading sign will be displayed.
6:Now continuously tap on next option and then leave tapping, create screen will displayed.
7:Check if the duplicated videos displayed on create screen.

Expected result: Video should not get duplicated on "Create" screen.

Actual result: Video is getting duplicated at create scree.

Refer the following video link for more details:
http://www.screencast.com/t/RiUTMtpwBJBr

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.8] on iPhone 6 / iOS 9.3.3

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.9

Note : I used song from My music due to Find music is not working for me.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1

**Comment by xiuie** [comment]
Not reproducible by original reporter
