### ISSUE TITLE
[1.9.8] iPhone 6 / iOS 9.3.3 - Song does not play - Create a lomotif using a motif and Find Music search song

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#587]
Frequency: Every time

Action:
1. Launch Lomotif app
2. Click on Start
3. Select any motif from any motif category
4. Go to Find Music
5. Click on Search bar and type work "Kala Chashma"
6. It will display list of songs
7. Tap on the 3rd song as display in Image
8. It will display Error Popup
9. Click on Apply and create lomotif
10. Now check the preview whether you are able to listen song or not

Expected result: Song should be included in the lomotif and it should be played

Actual result: Song included in the lomotif but can not play

![img_3703](https://cloud.githubusercontent.com/assets/9691390/17442775/219895ae-5b55-11e6-81c3-17edf83451b6.PNG)

![img_3702](https://cloud.githubusercontent.com/assets/9691390/17442670/659571e2-5b54-11e6-9586-31289f9e3eda.PNG)

**Comment by testershub** [comment]
I can't reproduce the issue for build [1.9.8] on iPhone 6S/ 9.3.2 and iPad Mini 3 / 9.3.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1
