### ISSUE TITLE
[1.9.8] iPhone 6 / iOS 9.3.3 - Instagram login without authentication - Sign out from Instagram from Linked account then Tap on Instagram folder will login without credentials

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#588]
Frequency: Few times

Action:
1. Launch Lomotif app
2. Tap on Hamburger icon
3. Select Linked account 
4. Sign out from Instagram account
5. Go to the Application launch screen (Home screen)
6. Click on Start
7. Tap on Instagram folder from Camera roll
8. Check whether does it ask for the login or not

Expected result: After signed out from Instagram linked account, when user clicks on Instagram folder from Camera roll should always ask for login credentials

Actual result: Clicking on Instagram folder does not ask for Login credentials and allows user to directly login in Instagram without login

**Frequency: 2/10 times**

**Comment by testershub** [comment]
@xiuie One more observation, the login pop up is displayed when user clears cache.

**Comment by hiteshbheda** [comment]
@testershub Thanks!

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.9

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1
