### ISSUE TITLE
There is no warning pop up displayed, when user delete video.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#59]
Steps to reproduce
1. Launch the app.
2. Home page will displayed.
3. Tap on close icon of already created video.
4. Verify whether video is deleted without showing any warning pop up or not.

Actual:- There is no warning pop up displayed, when user delete video.
Expected:- Warning pop up should displayed, when user delete any video.

Os/Browser - iPhone 5s/ iOS 9.2

Screen Shot - http://prntscr.com/9vfch8

**Comment by benchang** [comment]
@pmtheint please add this to asana and then close the issue

**Comment by pmtheint** [comment]
Moved to Asana
