### ISSUE TITLE
[1.9.9] iPad Mini 3 /9.3.2 , iPhone 6S/ 9.3.2 - Song thumbnail is not displayed on "Find Music" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#591]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "START" and select any motif from any category.
3: Proceed to "Find Music" screen.
4: Search for  song "Dangerous".
5: Check if thumbnail for fist song is not displayed.

Expected result: Thumbnail of song should be displayed.

Actual result: Thumbnail is not displayed for song on "Find Music" screen, Broken image is displayed.

Refer screenshot for more details.

**Comment by testershub** [comment]
![thumbnail](https://cloud.githubusercontent.com/assets/18608449/17455635/e5d53dec-5bdb-11e6-9b48-fad32ddbf7c2.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1

**Comment by xiuie** [comment]
Not reproducible by original reporter
