### ISSUE TITLE
[1.9.9] iPhone 6S / 9.3.2, iPad Mini 3 / 9.3.2 - Sticker is overlapping on "Lomotif".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#592]
Frequency: Every time

Action: 
1: Launch the app.
2: Tap on "START" and select any motifs from any category.
3: Skip the music and proceed to next screen.
4: Enable "Sticker" toggle button and select last sticker.
5: Check if sticker is overlapping on "Lomotif".

Expected result: Sticker should not overlap "Lomotif".

Actual result: Sticker is overlapping on "Lomotif" on preview.

Refer screenshot for more details.

**Comment by testershub** [comment]
![sticker](https://cloud.githubusercontent.com/assets/18608449/17456688/29332672-5bfe-11e6-8233-5be54b4cf2e6.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.9] on iPhone 6 / iOS 9.3.4

**Comment by vysohanych** [comment]
@xiuie I can reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1

**Comment by xiuie** [comment]
Ok this is a sticker design issue
