### ISSUE TITLE
[1.9.9] iPhone 6 / iOS 9.3.4 - All thumbnails not display for "😂" serach in motif - Search for "😂" and check resultant motifs' thumbnails

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#595]
Frequency: Every time

Action:
1. Launch Lomotif app
2. Click on Start
3. Go to Motif tab on "Motif" screen
4. Click on Search bar and search for "😂"
5. Multiple resultant motifs display
6. Observe all motifs display with Thumbnails (Album arts) or not

Expected result: Few motifs don't have Thumbnails

Actual result: All the resultant motifs should have Thumbnails (Album arts)

![img_3748](https://cloud.githubusercontent.com/assets/9691390/17456901/68ae4e98-5c04-11e6-9c98-32f63741a62a.PNG)

**Comment by xiuie** [comment]
@hiteshbheda I can't reproduce this on 1.9.9/10, The thumbnails are now colored square. the autoplayed previews all load but takes awhile

**Comment by testershub** [comment]
@xiuie I can't reproduce the issue for build [1.9.9] on iPhone 6S / 9.3.2.It is taking time to load.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1
