### ISSUE TITLE
[1.9.9] iPhone 6S / 9.3.2, iPad Mini 3 / 9.3.2 - Lomotif doesn't get saved when user saves the lomotif after tapping on "Home" icon.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#596]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select motifs from any category.
3: Skip the music and proceed to "Create" screen.
4: Tap on "Home" icon when preview is loading and save the lomotif.
5: Check if lomotif doesn't get saved and displayed at "Home" screen.

Expected result: Lomotif should get saved and displayed at "Home" screen.

Actual result: Lomotif doesn't get saved when user saves the lomotif after tapping on "Home" icon.

Refer following video for more details:
http://www.screencast.com/t/EJ8G0HWXYR

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue exactly for build [1.9.9] on iPhone 6 / iOS 9.3.4

When I use 10 or less motifs then it saves the lomotif perfectly, But if I add more than 30 motifs and clicking on Home button to save it, will save lomotif with 10-12 motifs.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce it on build 1.9.9 on iPhone 5S iOS 8.4.1

**Comment by xiuie** [comment]
Not reproducible by original reporter
