### ISSUE TITLE
[1.9.9] iPhone 6 / iOS 9.3.4 - Error 11800 and Error 11841 - Create a lomotif with slo mo video with 4 sec length

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#599]
Frequency: Every time

Action:
1. Shoot a slo mo video of length 4 sec
2. Launch Lomotif
3. Click on Start
4. Select slo mo video (4 sec length) from camera roll
5. Don't add any song
6. At create screen drag the time slider at the end (Right side)
6. Click on Apply
7. Check whether you are getting Error 11800 popup or not
8. Click on Ok on popup window and Click on Export button
9. Check whether you are getting Error 11841 or not

Expected result: Lomotif should be created perfectly and also exported successfully

Actual result: 
1. Dragging time slider at right end, displays Error 11800 popup
2. Clicking on Export, generate Error 11841

**Comment by xiuie** [comment]
I can't reproduce the error exactly but I get black frames and neverending processing on iPhone 6/10. 

iPhone 6/9.3.3 can't be reproduced at all.. Video exports in slow mo, final video is 15 secs as expected.

**Comment by testershub** [comment]
@xiuie Not able to reproduce on the latest build [1.9.9] for iPhone 6 S/9.3.2 and iPhone 6 Plus / 9.2.1.

**Comment by hiteshbheda** [comment]
@xiuie @testershub If this issue doesn't reproduce then please perform following steps:
1. Go to slo mo video from camera roll, 
2. make it as normal video (remove slo mo effect). 
3. Again edit it and apply slo mo effect and save the video. 
   4.Then try to create lomotif. 
4. This will give an Error 11800

**Comment by xiuie** [comment]
@hiteshbheda Still not able to reproduce on iPhone 6/9.3.3. Video plays in slow mo as expected

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.9.43] on iPhone 6 / iOS 10.1.1
