### ISSUE TITLE
Not able to add music in single time operation

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#6]
1. Open Lomotif App
2. Click on Start Button in Home Screen
3. Select Photos and videos
4. Select any of the music from the list
5. Click on 'Use 30 Seconds preview' then that music is not adding to video.
6. Now add music with footer video options then music will get added.

Please find here with attached screenshots,
![img_0106](https://cloud.githubusercontent.com/assets/5388768/12230899/70d8db62-b879-11e5-9952-c323961586ee.PNG)

![img_0106 1](https://cloud.githubusercontent.com/assets/5388768/12230892/610948ca-b879-11e5-9d8f-d5748a18a3bd.PNG)
![img_0108](https://cloud.githubusercontent.com/assets/5388768/12230894/67459130-b879-11e5-9658-7ffa5cdddb28.PNG)

**Comment by tsukisa** [comment]
Bug has been resolved
