### ISSUE TITLE
Lomotif media is unable to proceed, if user select/tap on any video on create lomotif page.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#60]
Steps to reproduce:- 
1. Launch the app.
2. Tap on start button.
3. Select videos from album.
4. Tap on right icon.
5. Choose music again tap on right icon.
6. Create page will displayed.
7. Lomotif Media is running.
8. Tap on any other video or image.
9. verify whether media process paused or not. 

Actual:- Lomotif media is unable to proceed, if user select/tap on any video on create lomotif page.
Expected:- Lomotif media shouldn't pause, when user tap on any image/video.

Os/Browser - iPhone 5s/ iOS 9.2
ScreenShot/Video  - https://www.dropbox.com/s/crbc93z3n1za3no/Media_process_issue.MOV?dl=0

**Comment by tsukisa** [comment]
This is worked as design. When user highlight any clip for editing, the preview change to current selected clip.
