### ISSUE TITLE
[1.9.9] iPhone 6 / iOS 9.3.4 - MSQRD folder is not available in Camera Roll - Install MSQRD app and shoot video / photo

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#605]
Frequency: Every time

Action:
1. Install MSQRD Application
2. Launch Lomotif app
3. On Camera Roll screen, check whether MSQRD app folder available or not

Expected result: MSQRD app folder should be available as like Snapchat, Boomerang, etc...

Actual result: 
1. MSQRD folder not display
2. Images and Videos shoot in MSQRD display in Camera roll folder

![img_3807](https://cloud.githubusercontent.com/assets/9691390/17616810/14798222-6094-11e6-86a1-7cad5cbee241.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for iOS Live build v1.9.1 build 1.9.6 on iPhone 6 / iOS 9.3.4

**Comment by Dipamit** [comment]
@xiuie : This seems work as designed. If you can see that there is no folder created by MSQRD on under your camera roll, where as other application like Snapchat making folder if you allowed to save. If you can see separate folder on you Camera roll then this is valid point, if not then I think current behavior is proper. You can find MSQRD video under camera roll for sure.  
Tested on iPhone-5 IOS.9.3.4
