### ISSUE TITLE
"+" & "-" options are not working, when user upload only images in lomotif. 

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#61]
Steps to reproduce:-
1. Launch the app.
2. Tap on start button.
3. Select only images from album.
4. Tap on right icon.
5. Choose music again tap on right icon.
6. Create page will displayed.
7. Tap on "+" or "-" options.
8. Verify whether options are working or not.

Actual:- "+" & "-" options are not working, when user upload only images in Lomotif. 
Expected: - "+" & "-" options should work on create Lomotif page.

Os/Browser: -iPhone 5s/ iOS 9.2

Screenshot:- http://prntscr.com/9vfgzc

**Comment by xiuie** [comment]
You have to drag and drop it to the "+" and "-" icon to duplicate or delete your pictures.
