### ISSUE TITLE
[1.9.11] iPhone 6 / iOS 9.3.4 - Endless processing - Create lomotif with 100 or  more motifs

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#612]
Frequency: Every time

Action:
1. Launch Lomotif
2. Click on Start
3. Select 100 or more motifs
4. Don't add any song and create lomotif
5. Check whether lomotif creates or not

Expected result: Lomotif should be created with all selected motifs and should be played smoothly on preview screen

Actual result: By creating lomotif with 100 + motifs, starts "processing" and it never ends. (more than 5 minutes, it does not create lomotif)

**Comment by xiuie** [comment]
I can't reproduce this on iPhone 6, 10.0

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.11] on iPhone 6S / 9.3.2 and iPhone 6 Plus / 9.2.1. 
Endless processing is displayed.

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue for build 1.9.11 on iPhone 6 / iOS 9.3.4

**Comment by xiuie** [comment]
supposedly fixed

**Comment by Pankaj-Testershub** [comment]
@xiuie Verified Fixed.
