### ISSUE TITLE
[1.9.11] iPhone 6S/ 9.3.2 - Exporting process restart when user apply filter and export the lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#617]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select any asset from any category.
3: Skip the music and proceed to "Create" screen.
4: Enable the "Filter" toggle button and apply "Mini Me/ B&W" filter.
5: Tap on "Export" icon.
6: Exporting process starts and completed.
7: Check if exporting process restarts.

Expected result: Exporting process should not be restarted when user apply filter to lomotif.

Actual result: Exporting process restart when user apply filter and export the lomotif.

Note: Please see issue is observed for "Mini Me" and "B&W" filters.

Refer following video for more details:
http://www.screencast.com/t/wrgSE07i0m0

**Comment by xiuie** [comment]
I can't reproduce this on my iPhone 6/10/0.. Do you mean there are two dialogue boxes, one for "Baking in Video Effects" and another for "Exporting"? If so, it is "Works as Designed."

**Comment by hiteshbheda** [comment]
@xiuie I think it works as design because here we are first exporting lomotif and then again make changes and export it with modification. So i think its proper behaviour
