### ISSUE TITLE
App got crashed, when user tap mutiples times on images or videos on create page.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#62]
Steps to reproduce:- 
1. Launch the app.
2. Tap on start button.
3. Select videos from album.
4. Tap on right icon.
5. Choose music again tap on right icon.
6. Create page will displayed.
7. Now tap images and video multiple times.
8. Verify whether app got crashed or not.

Actual:- App got crashed, when user tap multiples times on images or videos on create page.
Expected:- App shouldn't got crash, when user tap on images or video multiples time.

Os/Browser - iPhone 5s/ i-OS 9.2

Screenshot: -https://www.dropbox.com/s/z1ew9ecf9tfrqat/Crash_log.txt?dl=0

**Comment by xiuie** [comment]
Cannot replicate

**Comment by testinguser2018** [comment]
The issue occurred often not always.

**Comment by xiuie** [comment]
It will be especially helpful if you can describe how to replicate it @vikash2060t 

i.e. you might need to test it under different conditions e.g. is it because you use an exact combination (number) of photos/videos?

**Comment by benchang** [comment]
confusing and probably old
