### ISSUE TITLE
[1.9.11] iPhone 6 / iOS 10.0 - Video image is black, can't play - After switching to another app and back

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#620]
Frequency: Every time

Action:
1. Launch lomotif
2. Add several Motifs
3. Add music
4. While on Create screen, notice Lomotif autoplay normally
5. Put app in background mode and launch Instagram
6. Come back to Lomotif, notice that screen is black with a "Play" button
7. Tap on "Play" button
8. Lomotif does not play and is black

Expected result: Tap on play should play Lomotif

Actual result: Video cannot be played, black screen

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.11 on iPhone 6 / iOS 9.3.4

**Comment by xiuie** [comment]
supposedly fixed
