### ISSUE TITLE
User is able to add same video multiple times on create lomotif page.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#63]
Steps to reproduce
1. Launch the app.
2. Tap on start button.
3. Select videos from album.
4. Tap on right icon.
5. Choose music again tap on right icon.
6. Create page will displayed.
7. Tap on video option.
8. Select any video and tap on right icon.
9. Again try to upload same video.
10. Verify whether user is able to add same video multiple time or not.

Actual:- User is able to add same video multiple times on create page.
Expected:- User shouldn't able to add same video multiple times, if already added.

Os/Browser - iPhone 5s/ i-OS 9.2

Screen Shot/Video  - https://www.dropbox.com/s/crbc93z3n1za3no/Media_process_issue.MOV?dl=0

**Comment by xiuie** [comment]
This works as designed.
