### ISSUE TITLE
User is getting an Error "Sorry, purchase could not be restored" message instead of "Check Your Connection" while internet is in Off mode.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#67]
Steps To Reproduce :-
1. Launch the app.
2. Tap on settings icon.
3. Make internet to Off mode.
4. Tap on "Restore Purchases" option and tap on "YES".
5. User will be displayed an Error "Sorry, purchase could not be restored".
6. Observe and verify whether user is getting "Check Your Connection" message or not while internet is in Off mode.

Actual Result :-
User is getting an Error "Sorry, purchase could not be restored" message instead of "Check Your Connection" while internet is in Off mode.

Expected Result :-
User is getting an Error "Sorry, purchase could not be restored" message instead of "Check Your Connection" while internet is in Off mode.

Os/Browser - iPhone 5s/ i-OS 9.2

Screen Shot/Video - http://prntscr.com/9vw5ka

**Comment by pmtheint** [comment]
Moved to Asana
