### ISSUE TITLE
[1.9.19] iPhone 6 / 9.3.5 - Application Crash - Create lomotif with Facebook images and videos

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#676]
Frequency: Sometimes ( 3 - 4  / 10 times)

Action: 
1. Launch the app.
2. Tap on "START" button
3. Select multiple images and  videos from facebook folder
4. During processing save the lomotif by clicking on Home button
5. Check whether lomotif save or not

Expected result: Lomotif should be created and saved

Actual result: Application crash

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.19 on iPhone 5S / iOS 9.3.5 because loadind never ends on Create screen when user uses video and image from facebook folder

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.9.19] on iPhone 6 / 10.0.1
