### ISSUE TITLE
User is unable to access the app in landscape mode.

### ISSUE THREAD

**Issue by testinguser2018** [Lomotif/lomotif-ios-issues#68]
Steps To Reproduce :-
1. Launch the app.
2. Rotate the device in landscape mode.
3. Verify whether User is able to access the app in landscape mode or not.

Actual Result :-
User is unable to access the app in landscape mode.

Expected Result :-
User should able to access the app in landscape mode.

Os/Browser - iPhone 5s/ i-OS 9.2

**Comment by xiuie** [comment]
@vikash2060t What do you mean? It still works in landscape mode right? Are you saying that the user interface should be designed for landscape mode?
