### ISSUE TITLE
[1.9.19] iPhone 6 Plus / 9.2.1 - Error message " Could not load preview..." is displayed when user taps on music which has no thumbnail.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#683]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select any motifs from any category.
3: Search for the music. e.g. "1234567890"
4: Search result will be displayed.
5: Tap on any song on the list.
6: Check if error message "Could not load preview..." is displayed.

Expected result: Preview should get played.

Actual result: 
1: Error message "Could not load preview..." is displayed when user taps on music which has no thumbnail.
2: Error message "Server is little busy..." is displayed when user select music which has no thumbnail and taps on "Next" option.

**Comment by Dipamit** [comment]
@xiuie : I am getting Result-2 "Server is little busy..."

Note: I am not able to see Find music, but when type "1234567890" in search and tap on Close button of search box, List of songs are displayed and on tapping any song I am getting error message "Server Little busy..."

**Comment by vysohanych** [comment]
@xiuie I can reproduce this issue on build 1.9.19 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.19] on iPhone 6 / 10.0.1

But it is only reproducible when user Apply the selected song. By tapping on song, it plays but when we apply then it generate error.

**Comment by xiuie** [comment]
I can't reproduce this for build [1.9.19] on iPhone 6/10.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.9.19] on iPhone 6 / 10.0.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.27] on iPhone 5S / 9.3.5 and iPhone 6 Plus / 10.0.2.
To reproduce this issue search "₹&₹&".

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue now for build [1.9.27] on iPhone 6 / iOS 10.0.2

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.53] on iPhone 6 Plus / 10.1.1.
