### ISSUE TITLE
[1.6.10] iPhone 4s /9.2.1- Creating a Lomotif video with find music- No audio in the exported video

### ISSUE THREAD

**Issue by arif24888** [Lomotif/lomotif-ios-issues#69]
Frequency: Every Time

Action: 
1. Open Lomotif 
2. Start and select video
3. Add audio from find music
4. Select and start processing (15secs-Insagram)
5. Export Lomotif to camera roll
Expected Result: Music added to the video
Actual Result: No audio in the video

![image](https://cloud.githubusercontent.com/assets/17019569/12743596/ebd93d02-c9b8-11e5-813e-67fb2bb5e4df.png)

![20160201222622](https://cloud.githubusercontent.com/assets/17019569/12741625/55d2e188-c9a8-11e5-9417-7bf5e140dfe3.jpg)

**Comment by benchang** [comment]
old
