### ISSUE TITLE
[1.9.4(1.9.19)] iPhone 5C / iOS 10.0.1 - Black screen does get displayed while taping on recently exported project. 

### ISSUE THREAD

**Issue by pallavipillai** [Lomotif/lomotif-ios-issues#697]
Frequency - 7/10

Steps - 
1) Capture image from default camera application.
2) Launch Lomotif application.
3) Click on 'Start' button.
4) Select 'Camera Roll' screen and open 'Camera Roll' folder.
5) Select recently captured image.
6) Click on right icon on top right corner of screen.
7) Don't select any audio and go to the create screen.
8) Export lomotif without making any changes.
9) Select 'No thanks, I'll share later' option on share screen, now you are on home screen of application.
10) Click on recently created Lomotif project.

Expected Result - Project preview should get display properly.

Actual Result - Black screen does get displayed instead of project preview.

Please refer this video link - https://www.dropbox.com/s/go5e9rrwf9jvc52/BlackScreenRecentlyProjectPreview.mp4?dl=0

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.20 on iPad 2 / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.20] on iPhone 6 / iOS 10.0.1

Frequency: 6 / 10

**Comment by xiuie** [comment]
I can reproduce this.. on iPhone 6/10.0. Crashes when I tap the thumbnail

**Comment by hiteshbheda** [comment]
@xiuie I can still sometimes reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

**Comment by xiuie** [comment]
supposedly fixed

**Comment by Pankaj-Testershub** [comment]
@xiuie Verified Fixed.
