### ISSUE TITLE
Not closing and responding music/video in specific scenario

### ISSUE THREAD

**Issue by ravichandranaidu** [Lomotif/lomotif-ios-issues#7]
1. Open Lomotif App
2. Click on Start Button in Home Screen
3. Select Photos and videos
4. Select any of the music from the list
5. Click on 'Use 30 Seconds preview' then that music is not adding to video.
6. Click on Export button then it will get export to library
7. Now close the Lomotif App and re open it again
8. Lomotif movie on the home screen
9. Now open any of the Lomotif movie in home screen then play it
10. Click on home button which is on the top left corner then it will return to home page
11. Now select any of the movie again but it will not respond or close.

**Comment by xiuie** [comment]
@ravichandranaidu I can't replicate this. Can you send us a video of this portion:

Click on Export button then it will get export to library
Now close the Lomotif App and re open it again
Lomotif movie on the home screen
Now open any of the Lomotif movie in home screen then play it
Click on home button which is on the top left corner then it will return to home page
Now select any of the movie again but it will not respond or close.

**Comment by ravichandranaidu** [comment]
Please share your email id so I can share the video.
