### ISSUE TITLE
[1.6.2] iPhone 6 / 9.2.1- Sharing a lomotif to WhatsApp - Unable to share created lomotif to WhatsApp

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#70]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. In music screen, tap on my music tab
5. Select any song from my music
6. Create lomotif to save created video
7. Select more to share on social media
8. Select WhatsApp to share lomotif

Expected Result: Video should be added to WhatsApp

Actual Result: Getting Error (This video could not be sent. Please choose a different video.)

![img_0475](https://cloud.githubusercontent.com/assets/9691390/12755267/c26d282a-c9f4-11e5-9bbf-ec100f0f9ca5.PNG)

**Comment by xiuie** [comment]
I can replicate this

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@48ed7db4d46184a7de0d7b49bdb4aee03186acf7
