### ISSUE TITLE
[1.9.20] iPhone 6 / 10.0.1 - Black screen on preview and camera roll - Create lomotif with camera roll image and export it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#705]
Frequency: Many times (5 / 10)

Action: 
1. Capture an image from iOS device camera
2. Launch Lomotif app
2. Tap on "START" button
3. Select recently captured image from Camera Roll folder
4. Don't add any song and create lomotif
5. On preview screen, check preview screen is Black or not
6. If Preview screen displays Black then Click on Export
7. Open and play Saved lomotif from Camera Roll folder of iOS device
8. Check Exported video is also playing with Black screen or not 

Expected result: On preview screen, lomotif should play properly and when user export this lomotif then exported lomotif / video should also play properly

Actual result: Black screen displays on Preview screen and also on Camera roll app during video playing

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.20 on iPad 2 / iOS 9.3.5

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.20] on iPhone 6 Plus / 10.0.1.

But, as mentioned step- 5 black frame is not displayed at preview. Black frame is displayed when user export the lomotif and load it again.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
