### ISSUE TITLE
[1.9.20] iPhone 6 / 10.0.1 - Export process occurs Twice - Create lomotif with video, Apply sticker, Enable filter, Add text and Export it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#706]
Frequency: Everytime

Action: 
1. Launch Lomotif app
2. Tap on "START" button
3. Select any video from Camera Roll folder
4. Don't add any song and create lomotif
5. From Create screen Apply any sticker
6. Add filter
7. Add any text in Enter Title
8. Click on Export
9. Check Export process occurs once or twice

Expected result: Export process should occur only once

Actual result: Export process occurs twice

**Comment by xiuie** [comment]
Can i have video of this? I suspect it should say "Baking in video effects" and then "Exporting".

**Comment by hiteshbheda** [comment]
@xiuie Yes, you are right, First it creates "Baking in video effects" and then "Export" process
