### ISSUE TITLE
[1.6.2 Live] iPhone 6 / 9.2.1- Creating a lomotif- Using My Videos for a lomotif is causing app to crash

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#71]
Frequency: Once

Action:
Starting state: user is not logged in either to Instagram or Facebook
1.Open App
2. Click on Start
3. In My Video, select Motifs
4. Tap on any videos category (Baby)
5. Select multiple videos (more than 10) 
6. App crash

Expected result: App does not crash
Actual Result: App crashes

**Comment by xiuie** [comment]
I can replicate this in the live build.

**Comment by xiuie** [comment]
Discovered that there are black holes” in Motifs which lead to immediate crashes if a user selects it. example: in the live build, go to Motifs > Baby and select the first black thumbnail. This probably caused the crash @hiteshbheda is describing.
