### ISSUE TITLE
[1.9.20] iPhone 5/9.3.4 First news is not proper in News tab.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#713]
Frequency: Always
1. Open application and tap on Setting.
2. Tap on News Tab and tap on First News "BFF"
3. Verify page.

Expected result: News should display proper.

Actual result: News are not displayed.

![img_4009 1](https://cloud.githubusercontent.com/assets/17335200/18631920/59778236-7e92-11e6-91a3-8ebfaafea696.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this for build [1.9.20] on iPhone 6 / iOS 10.0.1

**But I think it's not a bug.**
