### ISSUE TITLE
[1.9.23] iPhone 6 / 10.0.1 - No content in Instagram folder - Open an Instagram folder and check for content

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#722]
Frequency: Every time

Pre-requisite: User has to link with Instagram account in Linked account section

Action:
1. Launch the app.
2. Tap on "START" 
3. Tap on Instagram folder
4. Check for content / assets of linked Instagram account

Expected result: Instagram Images / videos should be displayed

Actual result: No content in Instagram folder / Blank folder displays

![img_0830](https://cloud.githubusercontent.com/assets/9691390/18704160/737ce0a2-8006-11e6-872e-4a9a4738cb91.PNG)

![img_0831](https://cloud.githubusercontent.com/assets/9691390/18704159/734d69e4-8006-11e6-9943-3572472cf27b.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.23] on iPhone 6 Plus / 10.0.1 and iPhone 6S / 10.0.1.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.23 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now for build [1.9.23] on iPhone 6 / iOS 10.0.1
