### ISSUE TITLE
[1.9.24] iPhone 6 / 10.0.1 - Black screen appears by adding assets to existing lomotif - Open existing lomotif and add image

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#728]
Frequency: Many times (4 / 10)

Action: 
1. Launch Lomotif app
2. Tap on "START" button
3. Load existing lomotif
4. Click on  + icon and add image captured by device camera (preferably add image which was captured at last)
5. Check the preview screen, black screen displays or not

Expected result: On preview screen, lomotif should play properly with added asset / image

Actual result: Black screen displays on Preview screen after adding image

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.24] on iPhone 6S / 10.0.1, iPhone 6 Plus / 10.0.1 and iPad Mini 3 / 9.3.4.

**Comment by xiuie** [comment]
I can reproduce this 2/6 times on iPhone 6/10.0. Not sure if it's just completely random.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
