### ISSUE TITLE
[1.6.2 Live]  iPhone 6 / 9.2.1- Creating a lomotif - Using My Videos & My Music for a lomotif is causing app NOT Responding

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#73]
Frequency: Every Time

Action:

1.Open App
2. Click on Start
3. In My Video, select Motifs
4. Tap on any videos category
5. Select more than 50 videos
6. Go to My Music
7. Tap on Add from iTunes
8. Browse and select song
9. Continuous preparing
10. Hanged up at 44th process preparing
11. Select Close option to close app
12. Select OK
13. No Response
14. Continue preparing, application hang-up

Expected result: Lomotif should be created
Actual Result: Application Hang-up, No action performed

![img_0483](https://cloud.githubusercontent.com/assets/9691390/12759222/f05df064-ca05-11e5-9917-aca5eb37c47b.PNG)

![img_0484](https://cloud.githubusercontent.com/assets/9691390/12759221/f05d7f26-ca05-11e5-9c88-31c7f86af40e.PNG)

![img_0486](https://cloud.githubusercontent.com/assets/9691390/12759220/f05cd8be-ca05-11e5-9ac5-f2d12986b02a.PNG)

**Comment by xiuie** [comment]
@hiteshbheda Are you using all Motifs or all videos from your camera roll or a mix?

I'm using an iPhone 6 but haven't been able to replicate.

**Comment by hiteshbheda** [comment]
@xiuie I am using all motifs only. And using my music. 

It process upto certain level and then hang up (shows me "processing" and stuck at 44th out of 62)

**Comment by xiuie** [comment]
I've figured out how to replicate this on the live build @tsukisa 

The problem: Can't use the same Motif in different project in the same session.

1.Open App
2. Click on Start
3. In My Video, select Motifs
4. Tap on any videos category
5. Select first 6 videos
6. Go to My Music
7. Tap on Add from iTunes
8. Browse and select song
9. Hit home, and save project
10. Continuous preparing
11. In My Video, select the same Motifs
12. Hanged up at 44th process preparing
