### ISSUE TITLE
[1.9.24] iPhone 6 Plus / 10.0.1 - Lomotif is not playing from edited (start position) position on "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#732]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select video for "Camera roll".
3: Skip the music and proceed to "Create" screen.
4: Tap on video thumbnail and change / set the timeframe position.
5: Tap on highlighted thumbnail to exit edit mode.
6: Observe preview starts playing from edited position.
7: Now adjust / change the time to 30 secs.
8: Check if preivew starts playing from initial postion instead of edited position.

Expected result: Preview should starts playing from edited position when user change the time length to 30 secs.

Actual result: Preview starts playing from initial position instead of edited position when user change the time length to 30 secs on "Create" position.

Refer following video for more details:
http://www.screencast.com/t/2v7y7IVkFa

**Comment by vysohanych** [comment]
@xiuie I can reproduce this issue on build 1.9.24 on iPhone 5S / iOS 9.3.5

**Comment by xiuie** [comment]
@testershub
