### ISSUE TITLE
[1.6.2 Live] iPhone 6 / 9.2.1- Saving a lomotif in Notes - Created lomotif unable to play from Saved Notes

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#74]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. In music screen, tap on my music tab
5. Select any song from my music
6. Create lomotif to save created video
7. Select more to share on social media
8. Select WhatsApp to share lomotif
9. Tap on Notes (iOS in-built notes)
10. Add description in add notes section
11. Save Lomotif in Notes
12. Go to Notes (iOS notes)
13. Select saved lomotif
14. Click on saved lomotif to play
15. Does not play

Expected result: Lomotif should be played from Notes

Actual Result: Unable to play from Notes

![img_0489](https://cloud.githubusercontent.com/assets/9691390/12771960/5decf8c6-ca53-11e5-9179-66f349e1ed12.PNG)

![img_0490](https://cloud.githubusercontent.com/assets/9691390/12771964/6a6d3a0c-ca53-11e5-914f-578567b6ea00.PNG)

![img_0491](https://cloud.githubusercontent.com/assets/9691390/12771969/716110f4-ca53-11e5-8e4a-5de0ce84e062.PNG)

![img_0492](https://cloud.githubusercontent.com/assets/9691390/12771975/79311e50-ca53-11e5-98d1-8330c81222d2.PNG)

![img_0493](https://cloud.githubusercontent.com/assets/9691390/12771977/7ecc8656-ca53-11e5-9fb4-be5d1c4e6cd7.PNG)

![img_0494](https://cloud.githubusercontent.com/assets/9691390/12771983/8475ccac-ca53-11e5-88ca-522a899f730e.PNG)

![img_0495](https://cloud.githubusercontent.com/assets/9691390/12771988/89cd18e0-ca53-11e5-96c6-6f065241dcae.PNG)

![img_0496](https://cloud.githubusercontent.com/assets/9691390/12771990/8f2d76f4-ca53-11e5-89a8-9a9819473506.PNG)

![img_0497](https://cloud.githubusercontent.com/assets/9691390/12771996/9451c70c-ca53-11e5-840f-32aa5aae549a.PNG)

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@48ed7db
