### ISSUE TITLE
[1.6.2] iPhone 6 / 9.2.1- Sharing a lomotif to Facebook - App Crashing 

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#75]
Frequency: Once

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. In music screen, tap on my music tab
5. Select any song from my music
6. Create lomotif to save created video
7. Tap on Export button
8. Select Facebook from social media
9. App crash

Expected Result: Video should be added to Facebook

Actual Result: Lomotif app crashes

**Comment by tsukisa** [comment]
unable to reproduce
