### ISSUE TITLE
[1.9.24] iPhone 5S / iOS 9.3.5 - [Russian localization] - Settings - All items on the 'Mock In-App Purchase' dialog are not translated

### ISSUE THREAD

**Issue by vysohanych** [Lomotif/lomotif-ios-issues#750]
Frequency: Every time

Steps: 
1. Switch to Russian language on device
2. Launch the application
3. Tap on cogwheel button on top right corner
4. Tap three dots button on top right corner
5. Tap on the 'Mock In-App Purchase'

Actual result: All items on the 'Mock In-App Purchase' dialog are not translated

Expected result: All items on the 'Mock In-App Purchase' dialog should be translated

![2016-09-22_2310](https://cloud.githubusercontent.com/assets/3593359/18764363/beff986c-8119-11e6-8602-84c6c74c4b28.png)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.24] on iPhone 6 Plus / 10.0.1 and iPhone 5S / 9.3.5.

**Comment by xiuie** [comment]
Thanks. This dialogue should be only available in the dev.. closing issue for now but please ping me if the live build (from app store) is also not translated.
