### ISSUE TITLE
[1.9.24] iPhone 6 / 10.0.1 - Application Crash - Create lomotif with motifs / images

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#759]
Frequency: Every time

Action: 
1. Launch Lomotif app
2. Tap on "START" button
3. Select any image or motif
4. Click on Apply button at top right corner
5. Check whether application crashes or not

Expected result: Application should not crash

Actual result: Application crashes 

[Crash logs](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4Ud2h3eWYxOHFDSW8)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.24] on iPhone 6 Plus / 10.0.1 and iPhone 6S / 10.0.1.
I have tried with and without installing the "Vine" application.

**Comment by xiuie** [comment]
I can't reproduce this issue for [1.9.24] on iPhone 6 / 10.0.1

**Comment by hiteshbheda** [comment]
@xiuie I have reinstalled the app and not crashing now. You can close this issue.
