### ISSUE TITLE
[1.6.2] iPhone 6 / 9.2.1- Sharing a lomotif to Facebook - Displays "You have already authorized" message instead of sharing on Facebook

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#76]
Frequency: Once

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. In music screen, tap on my music tab
5. Select any song from my music
6. Create lomotif to save created video
7. Tap on Export button
8. Select Facebook from social media
9. Display message: "You have already authorized Lomotif" instead of posting/sharing lomotif to facebook.

Expected Result: Lomotif should be added to Facebook

Actual Result: Lomotif shows message: "You have already authorized Lomotif" instead of sharing lomotif to facebook, Lomotif not shared on facebook account.

![img_0502](https://cloud.githubusercontent.com/assets/9691390/12778046/7978d47e-ca86-11e5-87b9-5240cafff5e9.PNG)

![img_0503](https://cloud.githubusercontent.com/assets/9691390/12778045/7972e94c-ca86-11e5-9013-fd26d91316dd.PNG)

![img_0504](https://cloud.githubusercontent.com/assets/9691390/12778043/7952bcee-ca86-11e5-87df-1dbf2fa7af3d.PNG)

**Comment by tsukisa** [comment]
This message will be shown if you previously installed the app and have authorized the access. It's expected behavior.
