### ISSUE TITLE
[1.9.24] iPhone 6 Plus / 10.0.1, iPad Mini 3 / 9.3.4 - Black frame is displayed at the end of the preview.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#762]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select first three motifs from "wordmotifs" category.
3: Skip / add music and proceed to "Create" screen.
4: Preview starts autoplaying.
5: Check if black frame is displayed at the end of the preview (For few secs).

Expected result: Preview should be displayed for the selected assets.

Actual result: Black frame is displayed at the end of the preview when user creates lomotif with motifs from "wordmotifs" category.

Note: Issue is specifically observed for 3rd motif in the "wordmotifs" category.

Refer following video for more details:
http://www.screencast.com/t/DouJBpu3X8Ii

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.24 on iPhone 6 / iOS 10.0.2

But it's not the fault of application, it's a part of that specific motif.
