### ISSUE TITLE
[1.6.2] iPhone 6 / 9.2.1- Play a lomotif to WhatsApp window - Unable to play created lomotif to WhatsApp window screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#77]
Frequency: Every Time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select audio and video files
4. In music screen, tap on my music tab
5. Select any song from my music
6. Create lomotif
7. Click on Export button
8. Select and click on WhatsApp
9. Click on "Copy to WhatsApp" button
10. Select a person from WhatsApp contact to whom you want to send lomotif
11. On next WhatsApp screen, try to play created lomotif by clicking on "Play" button
12. No action / no response / Unable to play lomotif

Expected Result: Lomotif should be played on WhatsApp screen

Actual Result: Unable to play created lomotif / No action performed

![img_0508](https://cloud.githubusercontent.com/assets/9691390/12788066/1f62338a-cabe-11e5-9b8a-711274db72ce.PNG)

![img_0509](https://cloud.githubusercontent.com/assets/9691390/12788067/1f8cee7c-cabe-11e5-8717-b872a3d86148.PNG)

![img_0510](https://cloud.githubusercontent.com/assets/9691390/12788070/1fb29316-cabe-11e5-854d-3ce7c510586d.PNG)

![img_0511](https://cloud.githubusercontent.com/assets/9691390/12788065/1f368424-cabe-11e5-92da-cc2b2fd76b74.PNG)

![img_0512](https://cloud.githubusercontent.com/assets/9691390/12788107/4b3f6874-cabe-11e5-85a4-162558bd430c.PNG)

**Comment by tsukisa** [comment]
This issue has the same cause as #70
