### ISSUE TITLE
[1.6.2] iPhone 6 / 9.2.1- Save a lomotif - Does not play audio in lomotif when internet is disabled for Online Find Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#79]
Frequency: Every Time

Action: 
1. Activate Internet on mobile (wi fi / 3G)
2. Launch Lomotif 
3. Tap on Start
4. Select Motif tab
5. Select videos to create motif
6. Select Audio from Find Music
7. Create lomotif
8. Save it to lomotif library
9. Deactivate / Off internet (wi fi / 3G)
10. Play created lomotif from its library
11. Only video will be played without audio

Expected Result: 1. Lomotif should be played with video and audio both. 
                            2. If lomotif audio require internet service then why video is playing from library, we have taken both from internet.

Actual Result: Playing created lomotif with video only, NO AUDIO available in it. Infact both audio and video have been downloaded with internet access.

**Comment by tsukisa** [comment]
App doesn't cache downloaded music, user must connect to internet and redownload them.
