### ISSUE TITLE
[1.6.5] "Select Highlight" for Photos enable

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#8]
Expected: When selecting a picture/photo still image in Lomotif Create screen, you should have the "+" and "-" option.

Actual: You are able to scrub and select a "highlight moment"

**Comment by tsukisa** [comment]
Unable to replicate. Maybe you are viewing a video?

**Comment by xiuie** [comment]
Can't replicate too. I might have viewed a still video chosen from "All Photos". Let's close this.
