### ISSUE TITLE
[1.7.2] iPhone 4s / 9.2.1- Lomotif crash- Tap on Bubbles multiple times

### ISSUE THREAD

**Issue by arif24888** [Lomotif/lomotif-ios-issues#80]
Frequency-Every time

Action
1. Start
2. Select video from camera roll
3. Select vines( Select 2-4 vines)
4. Select any song
5. Press the tick sign
6. Now, at create Lomotif, change selections of the Selected video and vine(3-4 times)
7. Lomotif Crashes

Expected result: Creating the Lomotif video with video
Actual result: Lomotif Crashes
Here's the video link to the video showing the crash: 
https://drive.google.com/open?id=0B7rRbFNuvW7VazJfZ3pGYkljMGw3eV9pSEpZZkwxeHpIeVZr

**Comment by xiuie** [comment]
I can replicate this. Happens even if you do not add Motifs (all camera roll clips). Tapping quickly on thumbnails crashes the app.
