### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- Sticker Crash Bug - When tapping on sticker multiple times

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#81]
Frequency-Every time

Action
1. Start
2. Select video from camera roll
3. Select any song
4.  Now, at create Lomotif, turn on stickers
7. Tap on sticker multiple times

Expected result: Sticker loads
Actual result: Lomotif Crashes

**Comment by benchang** [comment]
looks fixed for now, closing
