### ISSUE TITLE
[1.9.27] iPhone 6 / 10.0.2 - Disable iPhone torch - Start torch from iPhone and open Lomotif app

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#813]
Frequency: Every time

Action:
1. Start the torch from iPhone / iOS device
2. Launch the app
3. Observe Torch is ON or OFF

Expected result: Torch should be ON because user has not yet started camera / user don't have camera control from Lomotif app

Actual result: Torch automatically turned OFF and also torch button disabled from iPhone access control center

**Comment by xiuie** [comment]
Haha ok. I can reproduce this. I think this is because we're using the camera for the app background. Nonetheless, I will inform the developer.

**Comment by hiteshbheda** [comment]
@xiuie Yes I agree that App using camera in Background. But I thought currently we are unable to take picture from Lomotif App icon (as it was available earlier). For this reason, I have logged this as bug. 

Thanks!
