### ISSUE TITLE
[1.9.27] iPhone 6 / 10.0.2 - Appication Crash - Create lomotif with 6-7 slo-mo video, Apply effects and Export

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#819]
Frequency: Most of the time (7/10 times)

Action:
1. Launch the app
2. Tap on "START" 
3. Select 6-7 Slo-mo video
4. Don't add any song
5. Create lomotif 
6. Click on Added First asset, it will display timeline for added video
7. Drag the rectangle box / cursor at the end of timeline 
8. Repeat Step 6 and 7 for all the added assets / videos
9. Apply and select any sticker
10. Apply filter
11. Enter text for "Enter Title", Change font style and font color
12. Click on Adjust tab and drag the time cursor at 30 seconds
13. Change aspect ratio to 16:9 from 1:1
14. Disable "hake to Shuffle"
15. Export lomotif by clicking on Export button
16. Check whether Lomotif exported or not

Expected result: Lomotif should be exported

Actual result: Application crashes

[Crash Log](https://drive.google.com/drive/u/0/folders/0B6P2U77GNA4UT1ZPT1M5X2VEdk0)

**Comment by clariceths** [comment]
Not Reproducible for build 1.9.27 on iPhone 6  / iOS 10.0.1

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.27] on iPhone 6 Plus / 10.0.2.
It is similar to #729 and #783.

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this crash every time on iPhone 6 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.28] on iPhone 6 / iOS 10.0.2
