### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- Watermark Disable Bug - When tapping on Watermark button to Disable it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#82]
Frequency-Every time

Action
1. Start
2. Select video from camera roll
3. Select any song
4. Now, at create Lomotif, turn off Watermark
5. Gives "Remove watermark" message on screen
6. Click on Cancel on displayed message

Expected result: Watermark button should not be off
Actual result: Watermark button off but still display watermark at created lomotif, Sometimes app automatically restart without manual instruction

![img_0543](https://cloud.githubusercontent.com/assets/9691390/12889197/da379c52-cea3-11e5-99ac-090fe1a2b3d4.PNG)

![img_0544](https://cloud.githubusercontent.com/assets/9691390/12889196/da35fe56-cea3-11e5-9aa6-ac25050c45cb.PNG)

![img_0545](https://cloud.githubusercontent.com/assets/9691390/12889198/daa880b6-cea3-11e5-87e1-e43e03c5524d.PNG)

**Comment by benchang** [comment]
When toggling watermark, if you don't buy, the toggle remains off

**Comment by tsukisa** [comment]
@xiuie  in debug mode, watermark will be able to toggle off even without buying it
