### ISSUE TITLE
[1.9.30] iPhone 6 / 10.0.2 - Stickers do not load - Create lomotif and enable stickers

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#829]
Frequency: Many times (7 / 10 times)

Action:
1. Launch the app
2. Tap on "START" 
3. Select any image / video or motif
4. Don't add any song and create lomotif
5. Enable stickers option
6. Check all stickers load or not

Expected result: When user enable stickers tab all the stickers should be loaded

Actual result: Stickers do not load even when user enable sticker tab

**Comment by xiuie** [comment]
Can't reproduce on iPhone 6/ 10.0.2 for build 1.9.30

@hiteshbheda Can you send over a screenshot (is everything blank or just a couple)? I tried and stickers loaded 5/5 times. Are you connected to the internet? Can you try the above steps but add music (this checks that you're connected).

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue now. 

I think it might be a server problem or Internet problem. 

It works correctly now.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.33] on iPhone 6 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build 1.9.33 on iPhone 6 / iOS 10.0.2
