### ISSUE TITLE
[1.9.33] iPhone 5s / 9.3.5 - Error message "JSON could not be serialized..." is displayed on "Lomotif Feed" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#831]
Frequency: Every time

Action:
1: Launch the app.
2: Swipe "Home" screen to right side to navigate "Lomotif Feed" screen.
3: Check if lomotif feeds are displayed.

Expected result: Lomotif feeds should be displayed,

Actual result: "JSON could not be serialized..." error message is displayed when user navigated to "Lomotif  Feeds" screen.

Refer screenshot for more details:

**Comment by testershub** [comment]
![json_error](https://cloud.githubusercontent.com/assets/18608449/19308476/583b2d2e-909d-11e6-870f-378b32ce0eb9.jpg)

**Comment by testershub** [comment]
@xiuie Please see, similar issue is observed on "Motifs" and "Find Music" tab.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.33 on iPhone 6 / iOS 10.0.2

**Comment by xiuie** [comment]
Server issue resolved. Thanks for pointing this out.
