### ISSUE TITLE
[1.9.33] iPhone 5S / 9.3.5 - Error 11800 is displayed at "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#836]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select (please select as fast as possible) more than 10 videos from "All videos" folder.
3: Add any music and proceed to "Create" screen.
4: Check if  error 11800 is displayed at "Create" screen.

Expected result: Preview should be displayed with selected assets.

Actual result: Error 11800 is displayed at "Create" screen.

Please refer video for more details:
http://www.screencast.com/t/lJ6nDuvmk

Note: Issue is specifically observed on iPhone 5S / 9.3.5.

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.33 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build 1.9.33 on iPhone 6 / iOS 10.0.2

**Comment by xiuie** [comment]
I can't reproduce this issue for build 1.9.33 on iPhone 6 / iOS 10.0.2

**Comment by vysohanych** [comment]
@xiuie I can't reproduce this issue on build 1.9.35 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 / iOS 10.0.2

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 5S / 9.3.5.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1
