### ISSUE TITLE
[1.9.33] iPhone 6 / 10.0.2 - Application Crash - Create lomotif with more than 50 images + videos from facebook and apply effects and export

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#837]
Frequency: Some times (4 / 8 times)

Action:
1. Launch the app
2. Tap on "START"
3. Select more than 50 images + video from Facebook folder
4. Add any song from Find Music and create lomotif
5. Apply any sticker
6. Apply Filter
7. Enter Title and change font and color
8. From Adjust tab, change time slider to 30 sec, make aspect ration 16:9 
9. Disable "Shake to Shuffle"
10. Export lomotif

Expected result: Lomotif should be exported

Actual result: Application crash

**Comment by xiuie** [comment]
I can reproduce this on my iPhone 6, 10.0.2 for build 1.9.33

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue sometimes for build 1.9.35 on iPhone 6 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 / iOS 10.0.2
