### ISSUE TITLE
[1.9.33] iPhone 6 / 10.0.2 - Application Crash - Refresh Facebook folder content multiple times

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#838]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "START"
3. Tap on Facebook folder, it will display facebook assets / contents
4. Drag the screen downwards to refresh facebook content
5. Repeat step 4 multiple times (15 to 20 times quickly)
6. Check if application crash or not

Expected result: Application should not crash during facebook content refresh

Actual result: Application crash

**Comment by xiuie** [comment]
Reproducible on my iPhone 6 / 10.0.2 for 19.33

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.35 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 / iOS 10.0.2
