### ISSUE TITLE
[1.9.33] iPhone 6 / 10.0.2 - Application Crash - OPEN "Wordmotifs" motif category

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#839]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "START"
3. Go to Motif tab on Camera Roll screen
4. Click on "wordmotifs" category to expand it
5. Check whether application crash or not

Expected result: "wordmotifs" category should expand / open

Actual result: Application crash

**Comment by xiuie** [comment]
Reproducible on my iPhone 6/10.0.2  for build 1.9.33

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.35 on iPhone 6 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.4] on iPhone 6s / iOS 10.1.1
