### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- "Enter A Title" Crash Bug - When tapping on (ON / OFF) Enter A Title tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#84]
Frequency - Every time

Action
1. Start
2. Select video from camera roll
3. Select any song
4. Create a Lomotif
5. OR Open any earlier created Lomotif
5. Turn ON Enter A Title
5. Turn OFF Enter A Title

Expected result: Enter A Title should be Turn OFF
Actual result: Lomotif Crashes

![img_0550](https://cloud.githubusercontent.com/assets/9691390/12891842/62d3efd8-ceaf-11e5-8130-3e84b30ee530.PNG)
![img_0551](https://cloud.githubusercontent.com/assets/9691390/12891843/62d99c4e-ceaf-11e5-8c1b-f6bc16a449cf.PNG)
![img_0549](https://cloud.githubusercontent.com/assets/9691390/12891844/62e0c1ae-ceaf-11e5-9112-160117173a16.PNG)

**Comment by xiuie** [comment]
I can replicate this @tsukisa

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@08e8aa958c8e44881dd984a46f1c733df6efaadc
