### ISSUE TITLE
[1.9.35] iPhone 6 Plus / 10.0.2 - Assets are not displayed on "Create" screen when user add more assets from "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#846]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select 1 image and 1 video.
3: Add music and proceed to "Create" screen.
4: Preview starts playing automatically.
5: Tap on "+" option to add more assets.
6: Select any image/ video and tap on "Next" option.
7: Check if added assets are displayed on "Create" screen.

Expected result: Added assets from "Create" screen should be display on "Create" screen.

Actual result: Assets are not displayed on "Create" screen when user add more assets from "Create" screen.

**Comment by testershub** [comment]
Refer following video for more details:
http://www.screencast.com/t/jJh6BLpQu

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.35 on iPhone 6 / iOS 10.0.2

**Comment by Dipamit** [comment]
@xiuie : Not able to reproduce this issue on iPhone 5/9.3.4 for build 1.9.35

**Comment by xiuie** [comment]
I can kinda reproduce this issue for build 1.9.35 on iPhone 6 / iOS 10.0.2.

Assets are added. However thumbnail does not show.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 / iOS 10.0.2

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [ 1.9.37] on iPhone 6 Plus / 10.0.2 and iPhone 5S / 9.3.5.
