### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- App Crash - When create Lomotif from vines (comedy) without Internet

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#85]
Frequency- Everytime

Action
1. Disable / Off wi fi (internet)
2. Start App
3. Click on Motif tab
4. Click on vines (Comedy)
5. Select any video
6. Tap on My Music Tab
7. Select any song

Expected result: Audio should be selected and added and create lomotif
Actual result: App crach

![img_0527](https://cloud.githubusercontent.com/assets/9691390/12893517/8ce7588e-ceb7-11e5-8da8-9bc648a6363f.PNG)

![img_0528](https://cloud.githubusercontent.com/assets/9691390/12893518/8ce8f0ae-ceb7-11e5-8816-5d2ad42c1750.PNG)

![img_0529](https://cloud.githubusercontent.com/assets/9691390/12893522/8df3b330-ceb7-11e5-8bd0-bc5df20e5b61.PNG)

![img_0530](https://cloud.githubusercontent.com/assets/9691390/12893519/8ced2b06-ceb7-11e5-9fc2-645ccc3d1e33.PNG)

![img_0531](https://cloud.githubusercontent.com/assets/9691390/12893520/8cf2cc1e-ceb7-11e5-8c1f-909246ee8885.PNG)

**Comment by xiuie** [comment]
I can replicate this @tsukisa

**Comment by benchang** [comment]
In airplane mode, the app crashes the moment you try to select motifs

**Comment by tsukisa** [comment]
@xiuie issue is fixed with commit Lomotif/lomotif-ios@cc9a2bdabe3c25bf028d7db9da1f7abb20d346d8
Please open a task in Asana if you want to change the pop up message. Current message is "Network is unavailable"
