### ISSUE TITLE
[1.9.35] iPhone 6 Plus / 10.0.2, iPhone 5S / 9.3.5 - Application is crashing when user deletes the asset from "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#851]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" and select 1 image / video.
3: Skip the music and proceed to "Create" screen.
4: Tap on "+" option to add more assets.
5: Add some image and tap on "Next" option.
6: Observe added assets are not displayed at "Create" screen.
7: Tap and hold the asset and delete it.
8: Preview starts playing.
9: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user delete added asset from "Create" screen.

**Comment by vysohanych** [comment]
@xiuie I can reproduce this issue on build 1.9.35 on iPhone 5S / iOS 9.3.5

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build 1.9.35 on iPhone 6 / iOS 10.0.2

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 / iOS 10.0.2

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.37] on iPhone 6 Plus / 10.0.2 and iPhone 5S / 9.3.5.
