### ISSUE TITLE
[1.9.37] iPhone 6 / 10.0.2 - No Content available under "wordmotifs" - Open "wordmotifs" category and check the available content under it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#853]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "START"
3. Go to motif tab and expand "wordmotifs" category
4. Check for the available motifs / content available under "wordmotifs" category

Expected result: Motifs / contents should be available under "wordmotifs" category

Actual result: 
1. No motifs / contents available under "wordmotifs" category
2. "No video under the search term "wordmotifs"" message display
3. In fact, user has not search for "wordmotifs" keyword

![img_1371](https://cloud.githubusercontent.com/assets/9691390/19408910/d608571e-92e5-11e6-910c-572ff63fa70f.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.37] on iPhone 5S/ 9.3.5.

**Comment by xiuie** [comment]
Wordmotifs does not have content in dev build

**Comment by hiteshbheda** [comment]
@xiuie Ok. Thanks for update!
