### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- App Crash - When create Lomotif from vines and Find Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#86]
Frequency - Every time

Action
1. Start App
2. Click on Motif tab
3. Click on vines (animals)
4. Select any video
5. Tap on Find Music Tab
6. Select any song
7. Create Lomotif
8. Click on Home Button
9. Tap on Save to save lomotif

Expected result: Lomotif should be saved
Actual result: App crach

**Comment by xiuie** [comment]
Can't replicate this either although it seems valid.

**Comment by benchang** [comment]
can't replicate
