### ISSUE TITLE
[1.9.37] iPhone 6 / 10.0.2 - Assets get increase in Instagram and Facebook - Click on Facebook and Instagram folder multiple times

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#860]
Frequency: Every time

Pre-requisite: Log in to Facebook and Instagram account in Linked Account section

Action:
1. Launch the app
2. Tap on "START"
3. Tap on Facebook folder, it will expand Facebook folder-> Observe and count available assets
4. Tap again to shrink Facebook folder
5. Again tap on Facebook folder and check available assets (Whether count of available assets are same increasaed (double)) 
6. Perform Step 3 to 5 for Instagram account, and check whether assets in Instagram are increasing everytime or not

Expected result: When user tap multiple times on Instagram or Facebook folder then available resource / assets should remain same

Actual result: When user tap multiple times of Instagram and Facebook folder then each time available assets get increased

**Comment by testershub** [comment]
@xiuie Similar to #726
