### ISSUE TITLE
[1.9.38] iPad Mini 3 / 9.3.4 - Search result for typo "Nickki Minij" is not displayed.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#868]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START".
3: Select any assets and proceed to "Find Music" screen.
4: Search for music "Nickki Minij".
5: Check if search result is displayed for "Nicki Minaj".

Expected result: Search result of "Nicki Minaj" should be displayed when user search with typo "Nickki Minij".

Actual result: Search result for typo "Nickki Minij" is not displayed.

Refer following screenshot for more details.

**Comment by testershub** [comment]
![nicki_music](https://cloud.githubusercontent.com/assets/18608449/19963962/f7ba9440-a1e4-11e6-8b87-681e770083c8.jpg)

**Comment by testershub** [comment]
@xiuie Please see, similar issue is observed for "Japanese - あなたへ贈る歌".

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce reproduce this issue for build [1.9.38] on iPhone 6 / iOS 10.0.2

**Comment by xiuie** [comment]
I will update the regression. Current search term does not return results for Nickki Minij
