### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- Audio insertion Bug - When create Lomotif from vines (animals) and Find Music

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#87]
Frequency- Everytime

Action
1. Start App
2. Click on Motif tab
3. Click on vines (animals)
4. Select any video
5. Tap on Find Music
6. Click on 30 seconds preview

Expected result: Audio should be downloaded and inserted in lomotif
Actual result: Audio download Error, Lomotif created without Audio

![img_0557](https://cloud.githubusercontent.com/assets/9691390/12907116/90a29e88-cf0d-11e5-9ea4-f23d25b23da2.PNG)

![img_0558](https://cloud.githubusercontent.com/assets/9691390/12907117/90a8cbd2-cf0d-11e5-8617-dbd13b7129d7.PNG)

**Comment by xiuie** [comment]
Can't replicate

**Comment by arif24888** [comment]
I can replicate this @hiteshbheda 

![img_4514](https://cloud.githubusercontent.com/assets/17019569/12940741/6ff67b48-cff6-11e5-92db-c5c5673a3fb6.PNG)

**Comment by benchang** [comment]
@ruiwen looks like soundcloud song: "Showtek & Justin prime - Canno ..." is missing it's files on the dev build
