### ISSUE TITLE
[1.9.38] iPhone 6 Plus / 10.0.2 and iPad mini 3 / 9.3.4- Entered text is not getting cleared from the text field when the user closes the search query.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#870]
Frequency: Every time.

Action:
1: Launch the app.
2: Tap on "START" button.
3: Tap on "Motif" tab and search with "Testershub" as a search parameter.
4: Tap on Close option of the search parameter.
5: Check if entered text in the search field is  getting cleared.

Expected result: Entered text in the search field should get cleared when user closes the search parameter.

Actual result: Entered text in the search bar is not getting cleared when user closes the entered search parameter.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.38] on iPhone 6 / iOS 10.0.2

But I think it's not a bug.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.38] on iPhone 6 / iOS 10.0.2

But I think it's not a bug.

**Comment by xiuie** [comment]
Hi I checked with the designer. It's expected behavior for now.
