### ISSUE TITLE
[1.9.38] iPad mini 3 / 9.3.4- Irrelevant sharing option "Instagram" is displayed on "Share" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#872]
Frequency: Every time.

Action:
1: Launch the app.
2: Tap on "START" button.
3: Navigate to "Share" screen with or without adding music.
4: Check if irrelevant  "Instagram" option is displayed on "Share" screen.

Expected result: As Instagram is not a supporting app for iPad mini 3, option should not be displayed on the create screen as well. 

Actual result: Irrelevant "Instagram" option is displayed on the share screen.

Note:
Similar issue is observed for "WhatsApp" app.

**Comment by testershub** [comment]
Please refer attached screenshot for more details.
![insta](https://cloud.githubusercontent.com/assets/18608449/19966517/19720b6a-a1f2-11e6-8a2c-8c8da1c978ff.jpg)

**Comment by xiuie** [comment]
@testershub Instagram should be available to download on your iPad mini. On the App Store search screen on your iPad mini there should be tabs at the top of the screen labeled "iPad Apps" and "iPhone Apps". If you choose "iPhone Apps" you should be able to download the Instagram iPhone app to your mini.
