### ISSUE TITLE
[1.9.38] iPhone 6 / 10.1.1 - Sign out without Facebook and Twitter account - Turn off internet and sign out from Facebook and Twitter account

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#873]
Frequency: Every time

Pre-requisite: User should be logged in with Facebook, Twitter and Instagram account in Linked account section

Action:
1. Turn OFF Internet
2. Launch the app
3. Tap on Hamburger icon
4. Click on Linked account section
5. Tap on Facebook and Twitter to sign out from them
6. Check whether user is able to sign out from linked Facebook and Twitter account without internet

Expected result: User should not able to log out from linked Facebook and Twitter account without Internet

Actual result: User can sign out from Facebook and Twitter account without internet

**IMPORTANT NOTE: Application works perfectly for Instagram. When user try to log out from Instgram without internet, it gives Error Message as expected.**

**Comment by hiteshbheda** [comment]
@xiuie  I can reproduce this issue for build [1.9.39] on iPhone 6 / iOS 10.1.1

**Comment by xiuie** [comment]
@hiteshbheda Try it all the way to the share screen, and try to share through Twitter. You'll realize that the accounts are indeed unlinked.
