### ISSUE TITLE
[1.9.39] iPhone 6 Plus / 10.1.1, iPhone 6 S / 10.0.1 - Only one motif is displayed for "badgalriri" category.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#875]
Frequency: Every time

Action:
1: Launch the app.
2: Tap on "START" >> Motif tab.
3: Scroll down and check if only one motif is displayed for "badgalriri" category.

Expected result: Three motifs should be displayed in "badgalriri" category.

Actual result: Only one motif is displayed for "badgalriri" category.

Note:
- P.S., for "twerking" category only two motifs are displayed. User can access rest of the motifs after tapping on the category name.
- Please refer screenshot for more details.

**Comment by testershub** [comment]
![badgal](https://cloud.githubusercontent.com/assets/18608449/20028726/8a127aee-a35f-11e6-860b-63ccbaebfc99.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.39] on iPhone 6 / iOS 10.1.1

**But I think it's not a bug.**
