### ISSUE TITLE
[1.7.0] iPhone 4s/ 9.2.1- Lomotif crash - Lomotif app crashes when moving the music waveform at Create Lomotif

### ISSUE THREAD

**Issue by arif24888** [Lomotif/lomotif-ios-issues#88]
Frequency-Every time

Action
1. Open Lomotif and tap Start
2. Select videos
3. Add music
4. At Create function, move the music waveform (left of right)
5. Lomotif crashes

Expected result: Adding music to Lomotif
Actual result: Lomotif crashes

![lomotif](https://cloud.githubusercontent.com/assets/17019569/12911169/9b8f97ba-cf3a-11e5-830a-d35ad8c8cd59.png)

![crash](https://cloud.githubusercontent.com/assets/17019569/12911219/02384426-cf3b-11e5-9a0a-4523c3f8788a.png)

**Comment by xiuie** [comment]
I can replicate this @tsukisa

**Comment by hiteshbheda** [comment]
I can replicate this @arif24888

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@75d23eb7dfde460d7b288b752ba104883f5bbd94
