### ISSUE TITLE
[1.9.39] iPhone 6 / 10.1.1 - Thumbnail mismatch - Create lomotif with motifs and export it

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#888]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "START"
3. Go to Motif tab
4. Expand any motif category (for example "Smoke")
5. Select few motifs from selected motif category and create lomotif without adding song
6. Export lomotif
7. Check on Application home screen and Photos app screeen whether lomotif thumbnails are same or not

Expected result: Exported lomotif's thumbnail / album art should be same at Lomotif home screen and Photos / camera roll folder

Actual result: Exported lomotif's thumbnails are different in Camera roll / photos folder and on App home screen

**Comment by testershub** [comment]
@xiuie Thumbnail is not displayed (White square box displayed) at home screen but at "Photos" thumbnail is displayed.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
