### ISSUE TITLE
[1.9.39] iPhone 6 S / 10.0.1 - Preview of the recently created project is not displayed on "Create" screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#889]
Frequency: Every time

Precondition:
- There should exist more than 7 created projects on the home screen.

Action:
1: Launch the app.
2: Tap on "START" and select three motifs from "Smoke" category.
3: Navigate to "Create" screen without adding any music.
4: Preview will be played, tap on "Export" option.
5: Tap on "No thanks, I'll share later" option.
6: From the  projects being displayed on "Home" screen, tap on recently created project.
7: Check if the preview is displayed on the "Create" screen.

Expected result: Preview should be displayed on the "Create" screen of the recently created project.

Actual result: Preview of the created project is not displayed on the "Create" screen.

Note:
- Issue is observed for the first time only when user navigated to the create screen from the home screen, for rest of the times it is working as expected.
- For the same assets it is working fine when the existing project count is less than 7 projects on the home screen.
- Please refer the following video link for more details:
https://drive.google.com/file/d/0B3w27aq2H9_UWno2bW15cmNXMTQ/view?usp=sharing

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.39] on iPhone 6 / iOS 10.1.1

@testershub This occurs if your Internet connection not working properly and motifs not load completely. Also if you will clear cache and then try, it won't replicate.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6S / 10.0.2 and iPhone 6 Plus / 10.1.1.
