### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- App Crash - When Click on Close (X) buttn or on "No Thanks, I'll share later" button on media sharing page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#89]
Frequency- Every time

Action
1. Start 
2. Select video from camera roll
3. Select any song from Find Music
4. Create Lomotif
5. Tap on Export button and click on Yes
6. Click on Close (X) buttn or on "No Thanks, I'll share later"
7. Click on "Yes" on Cancel sharing window

Expected result: App should not be crash and should reach to Home screen
Actual result: App crach

![img_0570](https://cloud.githubusercontent.com/assets/9691390/12917587/38917130-cf60-11e5-8aac-b018443f7bdb.PNG)

![img_0571](https://cloud.githubusercontent.com/assets/9691390/12917589/38ff5c22-cf60-11e5-863b-fa1ecc88778f.PNG)

![img_0573](https://cloud.githubusercontent.com/assets/9691390/12917590/38ff9f98-cf60-11e5-96ee-019d1e6a9bb4.PNG)

![img_0574](https://cloud.githubusercontent.com/assets/9691390/12917585/388d24c2-cf60-11e5-8470-1a670f6d46c0.PNG)

![img_0575](https://cloud.githubusercontent.com/assets/9691390/12917586/38900be2-cf60-11e5-89a8-e50e5760e449.PNG)

**Comment by arif24888** [comment]
I can replicate this

**Comment by tsukisa** [comment]
Fixed with commit Lomotif/lomotif-ios@707cf6a2a9fc495178388c4948992b054407302e
