### ISSUE TITLE
[1.9.39] iPhone 6 / 10.1.1 - Application Crash - Create lomotif with slo-mo

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#892]
Frequency: Every time

Action:
1. Launch the app
2. Tap on "START"
3. Select one slo-mo video
4. Skip song and create lomotif
5. Enable sticker tab but don't apply any sticker
6. Apply filter and change to different filter
7. Add any "Enter title" 
8. Export lomotif
9. Check whether app crashes or not

Expected result: Lomotif should be exported successfully

Actual result: Application crash

**Comment by testershub** [comment]
@xiuie I can not reproduce this issue for build [1.9.39] on iPhone 6S / iOS 10.0.1. It is working as expected.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
