### ISSUE TITLE
[1.7.0] iPhone 4s/ 9.2.1- Lomotif crash - Lomotif app crashes when exporting video after applying filter

### ISSUE THREAD

**Issue by arif24888** [Lomotif/lomotif-ios-issues#90]
Frequency: Every time
Action
1. Open Lomotif and tap start
2. Select Camera roll videos(2-3 videos)
3. Select music
4. Apply filter(VIDEO FRAMES DROP IN PREVIEW LOMOTIF)
5. Tap export video
6. Shows "Saving Lomotif to Camera Roll"
7. Lomotif Crashes

Expected result: Creating Lomotif Video by adding filter
Actual result: Lomotif crashes

![file_000](https://cloud.githubusercontent.com/assets/17019569/12923673/ca32f9a4-cf80-11e5-8545-ff94d9f5b897.jpeg)

![file_001](https://cloud.githubusercontent.com/assets/17019569/12923693/d90a56de-cf80-11e5-9be3-f99739f6ea79.jpeg)

**Comment by benchang** [comment]
this may be a iPhone 4S issue, @xiuie you are in charge of getting us a 4S

**Comment by xiuie** [comment]
For the upcoming cycle we have an iPhone 4S. Can't replicate on my device.
