### ISSUE TITLE
[1.9.42] iPad Mini 3 / 9.3.4, iPhone 5S / 9.3.5 - Entered information while "Sign Up" is not displayed in user's profile.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#905]
Frequency: Every time

Action:
1: Launch the app.
2: Swipe up to reveal profile view.
3: Complete the "Sign up" process with valid credentials.
4: Tap on "Settings" option.
5: Check if entered information is displayed (Email , Username and password)

Expected result: Entered information while "Sign Up" should be displayed in user's profile.

Actual result: Entered information while "Sign Up" is not displayed in user's profile.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.42] on iPhone 6 / iOS 10.1.1

All information are blank.

**Comment by Dipamit** [comment]
@xiuie : Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.42

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
