### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - "Forgot Password?" not working - User doesn't get Reset link on Email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#915]
Frequency: Every time

Actions:
1. Launch the app.
2. Tap on "Sign In" option.
3. Tap on "Forgot Password?" option.
4. Enter valid email address and tap on "Recover" button.
5. User will get message "We've sent an email at ......." message
6. Check the Inbox of the Email for which you have requested to reset password, whether user get any reset password link or not

Expected result: User should receive Email with reseat password link

Actual result: User does not receive any mail to reset password

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1 build 1.9.42

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.42] on iPhone 6 Plus / 10.1.1.
User gets "Reset password" link on registered email address.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
