### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - Improper flow - Click on "Skip for Now" button on login page and check the navigation flow

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#917]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. Click on "Skip for now" button at bottom of the screen
4. Check whether user is navigated on Create lomotif / motif selection page or not

Expected result: User should be navigated to Select motifs / image page

Actual result: When user clicks on "Skip for now" button, he/she will navigate to Login page again instead of Motifs / image selection page

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.42

**Comment by xiuie** [comment]
Clicking "Skip for Now" should lead you to home and "Start button".

**Comment by xiuie** [comment]
supposedly fixed
