### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - Irrelevant message - Sign up without Email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#918]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. On Sign Up page, enter any email and password and click on Sign Up button
4. On Next screen, Enter username and remove / Erase Email address and click on Let's Go button
5. Check whether user get any alert / warning / error message like "Enter Email address" or anything else...

Expected result: When user erase Email and click on Let's Go button, then he / she should get some alert / warning / error message like "Enter Email address" or any other message...

Actual result: Even though user has erased Email then also he/she gets message "We've sent you a verification email. If you haven't forgotten your password or username, you can retrieve these information via email"

![img_1750](https://cloud.githubusercontent.com/assets/9691390/20400844/60bd9dd8-ad1c-11e6-8fab-198bbc4df7e6.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.42] on iPhone 6 Plus / 10.1.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
