### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - "Server is busy" error - Sign up with already existed Email and new username

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#919]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. On Sign Up page, enter already registered Email and correct password
4. Click on Sign Up button
5. On Next screen, enter new (unused) username
6. Click on Let's Go! button
7. Check whether can sign up or get any error on the screen

Expected result: User should sign up with different (unused) username OR user should get Warning / Error message like "Entered Email address has already been used earlier" or "Email already registered", etc...

Actual result: User gets Error message "Server is little busy at the moment, please try again later"

![img_1746](https://cloud.githubusercontent.com/assets/9691390/20401180/c40877e0-ad1d-11e6-933d-1f7d256fb28b.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.42] on iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 and iPhone 5S / 9.3.5.
@hiteshbheda There might be network issue due to which above message "Server is little busy..." is displayed.

Refer screenshot for more details:
![error](https://cloud.githubusercontent.com/assets/18608449/20419557/59162986-ad7d-11e6-9782-d3377dc45d3c.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can still reproduce this issue specifically for this email. 

@testershub There is no internet connectivity issue currently and works properly for other functionalities of app.

**Comment by testershub** [comment]
@hiteshbheda I am not able to reproduce the issues with the above mentioned steps. Could you please provide a video link, I'll try reproducing it again.

**Comment by hiteshbheda** [comment]
@testershub Sure, I'll record the screen and send you the video link. Thank you!

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

**Error Message "A user is already registered with this email address" display. Works perfectly now.**

You can close this issue for build [2.1.0]
