### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - "Connect with Facebook" button problem - Click on "Connect with Facebook" button on Sign up / Sign in page

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#920]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. On Sign Up page, click on "Connect with Facebook" button
4. Logging in process will start
5. Check whether user can logged in with "Connect with Facebook" option and move to profile or START Home page

Expected result: 
1. When user click on "Connect with Facebook" button, he/she should be loged in through Facebook account
2. Once user logged in then he/she should be navigated to user profile or START Home page

Actual result: 
1. Once user click on "Connect with Facebook" button, logging in process starts and finish
2. User is not navigated to Home Page or Profile page
3. User can be logged in but nothing happens on the screen except logging process bar

![1](https://cloud.githubusercontent.com/assets/9691390/20419495/e4e08aca-ad7c-11e6-8240-bf69b3648051.PNG)

![2](https://cloud.githubusercontent.com/assets/9691390/20419497/e50b4882-ad7c-11e6-8ac4-d23acc0800ad.PNG)

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.42] on iPhone 6 Plus / 10.1.1.

**Comment by Dipamit** [comment]
@xiuie: User is navigating to "Choose Username" Screen on tapping "Connect with Facebook"


![img_5103 1](https://cloud.githubusercontent.com/assets/17335200/20513716/cf09d718-b0ad-11e6-956d-bfb1129e2742.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
