### ISSUE TITLE
[1.9.42] iPhone 6 / 10.1.1 - User can log in over Facebook login option - Login with "Connect with Facebook" option and after that login with Email and password

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#922]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. On Sign Up page, click on "Connect with Facebook" button
4. Logging in process will start and stop / finish but still user will be available at same screen
5. Click on "Sign in" option
6. On login screen, enter valid (already registered) username and password
7. Check on Available screen, whether user is logged in with Facebook credentials or with lastly used username and password

Expected result: Once user click on "Connect with Facebook" option then user should log in with facebook credentials and should not allow to login with other option

Actual result: Even though user has been logged in with "Connect with Facebook" option, then also he/she will be allowed to log in with username / password

**Comment by Dipamit** [comment]
@xiuie: When I tap on "Connect with Facebook" page navigate to sign up screen for entering username, email and password.

![img_5056 1](https://cloud.githubusercontent.com/assets/17335200/20421676/8717d6a0-ad8b-11e6-8149-f859e164bcdf.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
