### ISSUE TITLE
[1.9.42] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is freezing on create screen.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#925]
Frequency: Every time. 

Precondition:
- User should be logged in to the application.

Action:
1: Launch the application.
2: Navigate to create screen by selecting three motifs. 
3: Tap on "Post" option, "Do you want to.." pop up message will be displayed. 
4: Tap on "YES" option.
5: Close the "Post on Lomotif" pop up window.
6: Repeat step 3-4 and tap on "Done" option of "Post on Lomotif" pop up window.
7: Check if the application is freezing. 

Expected result: Application should not freeze, user should be able to export the created Lomotif. 

Actual result: Application is freezing after tapping on "Ok" option of the "The operation could not be completed" error message.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

Step 3 onwards all steps are not possible to perform on build [1.9.43]

**Comment by Dipamit** [comment]
@xiuie : I am able to create and export Lomotif.
             Some time Getting error " The operation couldn't be completed. (Cocoa error-1)" on tapping Back button from "Saving your Lomotif.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
