### ISSUE TITLE
[1.9.42] iPhone 6 Plus / 10.1.1, iPhone 6S / 10.0.2 - Application is crashing when user try to create lomotif .

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#929]
Frequency: Every time

Action:
Precondition: User should be logged in.
1: Launch the app.
2: Login with valid credentials.
3: Tap on "Settings >> Terms of user & Privacy Policy".
4: Tap on "X" option to close the "Terms of user & Privacy Policy" screen.
5: Swipe up and tap on "START".
6: Select any assets and proceed to "Find Music" screen.
7: Tap on tick (at right top corner) to proceed to "Create" screen.
8: Check if application is crashing.

Expected result: Application should not crash.

Actual result: Application is crashing when user try to create lomotif.

Refer following video for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iZFRVeHlVUG1KaFU

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.43] on iPhone 6 Plus / 10.1.1 and iPad Mini 3 / 9.3.4.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue now for build  [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by Dipamit** [comment]
@xiuie:Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.43

**Comment by testershub** [comment]
@xiuie I can still reproduce this issue for build [1.9.45] on iPhone 6 Plus / 10.1.1.

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2.
