### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- Image / Video deletion Bug - When Click on Remove/Delete button to delete selected image from created Lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#93]
Frequency- Every time

Action
1. Start
2. Select few images from camera roll
3. Select any song from My Music
4. Create Lomotif
5. Now, click on specific image at created Lomotif
6. It will open new small windows by displaying Add (+) and Remove (-) symbols
7. Click on Remove (-) symbol

Expected result: Selected Image should be removed from created Lomotif
Actual result: No effect applies on screen, No change, No response

![img_0588](https://cloud.githubusercontent.com/assets/9691390/12954286/e15b4744-d043-11e5-9c2e-10cfdaf4c9d3.PNG)

**Comment by arif24888** [comment]
I can replicate this @hiteshbheda
