### ISSUE TITLE
[1.9.42] iPhone 6 Plus / 10.1.1 - Application is crashing when user keep the device ideal while "Sign Up" process.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#930]
Frequency: Every time

Action:
1: Launch the app.
2: Swipe up to reveal profile view.
3: Tap on "Login" button.
4: Enter valid email and password.
5: Tap on "Sign Up" button (User will be navigated to "Choose username" screen)
6: Minimize the app.
7: Keep the device ideal for more than 6 mins.
8: Unlock the device and relaunch the app.
9: Check if application is crashing.

Expected result: Application should not crash when user keep the device ideal while "Sign Up" process.

Actual result: Application is crashing when user keep the device ideal (more than 6 mins) while "Sign Up" process.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
