### ISSUE TITLE
[1.9.42] iPhone 6S / 10.0.2 - Application is crashing while posting the lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#933]
Frequency: Every time

Action:
1: Launch the app.
2: Login with valid credentials.
3: Tap on "START" and select few videos / motifs.
4: Add music and proceed to "Create" screen.
5: Enable "Filter" toggle button and tap on "Post" option.
6: Tap on "Done" button on "Post on Lomotif" pop up.
7: "Baking in video effect" progress starts and stuck.
8: Check if application is crashing.

Expected result: Application should not crash while posting the lomotif.

Actual result: 
1: "Baking in video effect" progress starts and stuck.
2: Application is crashing after"Baking in video effect" progress stuck.

Refer following video for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iYkI2dTlqbDlvbzA

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.43

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
