### ISSUE TITLE
[1.9.43] iPhone 6 / 10.1.1 - "Keep Private" and "Save to Camera Roll" button not working - On "Saving your lomotif" page click on "Keep Private" and "Save to Camera Roll" button

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#937]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. Login with valid credentials.
4. Open any existing lomotif
5. Change opened lomotif by applying any effect / sticker etc.
6. Click on Ok and then Export from Top right corner on the screen
7. On "Saving your Lomotif" page, Click on "Keep Private" and "Save to Camera Roll" button
8. Check whether "Keep Private" and "Save to Camera Roll" buttons working or not

Expected result: "Keep Private" and "Save to Camera Roll" buttons should work

Actual result: "Keep Private" and "Save to Camera Roll" buttons do not work

![1](https://cloud.githubusercontent.com/assets/9691390/20439385/3c7e023a-ade1-11e6-9949-58230aa26059.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 Plus /10.1.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
