### ISSUE TITLE
[1.9.43] iPhone 6 / 10.1.1 - Exporting process not ending - Open an existing lomotif, change it and Export

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#938]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. Login with valid credentials.
4. Open any existing lomotif
5. Click on + sign and add one more asset
6. Click on Ok and then Export from Top right corner on the screen
7. On "Saving your Lomotif" page, Click on "Make Lomotif" button
8. Exporting process starts
9. Immediately click on "<" button before Exporting reach at 100 %
10. Check whether user gets continuous Exporting process on the screen or not

Expected result: Exporting process should be completed or cancelled

Actual result: Exporting process starts and when user click on Back button before Exporting process reach at 100% then on screen, Exporting continuously display

![2](https://cloud.githubusercontent.com/assets/9691390/20439474/9d1463d2-ade1-11e6-9dd4-21fccad6d463.PNG)

![4](https://cloud.githubusercontent.com/assets/9691390/20439475/9d1aa210-ade1-11e6-8d25-8ef89d9b4e9c.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 Plus / 10.1.1.
Continuous exporting is displayed even when user navigates back to "Create" screen from "Share" screen after exporting the lomotif.
Issue is happening for all lomotifs not for only existing lomotifs.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
