### ISSUE TITLE
[1.9.43] iPhone 6 / 10.1.1 - "No thanks, I'll share later" and "X" buttons not working - On Export screen click on "No thanks, I'll share later" and "X" buttons

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#939]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up to reveal profile view.
3. Login with valid credentials.
4. Open any existing lomotif
5. Click on + sign and add one more asset
6. Click on Ok and then Export from Top right corner on the screen
7. On "Saving your Lomotif" page, Click on "Make Lomotif" button
8. Let exporting process 100% complete
9. Once Exporting process completes, Uploading process will start
10. Let Uploading process 100% complete
11. Once Uploading process completes, user will be navigated to Export media screen
12. Click on "No thanks, I'll share later" at bottom of the screen OR "X" button at Top right corner of the screen
13. Check whether "No thanks, I'll share later" and "X" buttons are working or not

Expected result: "No thanks, I'll share later" and "X" buttons should work and user should be navigated to Home screen

Actual result: "No thanks, I'll share later" and "X" buttons don't work, Nothing happens and user available at the same screen

![3](https://cloud.githubusercontent.com/assets/9691390/20439667/ab03eba6-ade2-11e6-8b5a-d5b5a64c17c6.PNG)

**Comment by testershub** [comment]
@xiuie I am able to reproduce this issue for build [1.9.43] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
