### ISSUE TITLE
[1.9.43] iPhone 6 / 10.1.1 - Application Crash - Login with Facebook option and create and Export lomotif

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#942]
Frequency: Every time

Action:
1. Launch the app.
2. Swipe up for login
3. Click on "Connect with Facebook" option
4. Tap on START
5. Create lomotif with any camera roll image or motif, skip music
6. Click on Export button
7. Click on "Make Lomotif" button on "Saving your Lomotif" page
8. Exporting process starts and completes 100%
9. After Exporting process, Uploading process starts and completes 100 %
10. Check whether application crash or not

Expected result: After uploadig process, user should be navigated to Export / media sharing page

Actual result: Application crash

**IMPORTANT NOTE: This crashing is only occurs with FACEBOOK LOGINS, For username password or Email logins this issue is not reproducible.**

**Comment by xiuie** [comment]
Reproducible on iPhone 6s / 10.1.1 for build 1.9.43

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6 / iOS 10.1.1

You can close this issue for build 1.9.52
