### ISSUE TITLE
[1.7.0] iPhone 6 / 9.2.1- App crash - When trying to save created Lomotif on Home screen

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#95]
Frequency- Once / Twice

Action
1.  Start
2.  Click on vines (dance) from Motif tab
3.  Select any two 2 motifs
4.  Select any song from My Music
5.  Create Lomotif
6.  Click on Home Button
7.  Click on “Yes” at “Would you like to save your changes?” screen

Expected result: Lomotif should be saved
Actual result: Application crashes

**Comment by benchang** [comment]
can't replicate, closing.
