### ISSUE TITLE
[1.9.43] iPhone 6 Plus / 10.1.1 - Error "Error - Unknown" is displayed while uploading the lomotif. 

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#950]
Frequency: 6/10

Action:
1: Launch the app.
2: Login with valid credentials.
3: Tap on "START" and select 2 assets (1 video and 1 image) from "Snapchat" folder.
4: Add / skip the music and proceed to "Create" screen.
5: Tap on "Export" option.
6: Tap on "Make Lomotif" button.
7: Exporting progress will be displayed.
8: Check if error "Error-Unkown" id displayed while uploading the lomotif.

Expected result: User should be navigated to "Share" screen after completing uploading the lomotif.

Actual result: Error "Error - Unknown" is displayed while uploading the lomotif. 

Refer screenshot for more details:

**Comment by testershub** [comment]
![error-unknown](https://cloud.githubusercontent.com/assets/18608449/20472446/e0b1398a-afdf-11e6-838e-83f19676c96d.jpg)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by Dipamit** [comment]
@xiu: Not able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.43

**Comment by hiteshbheda** [comment]
@xiuie I still can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [2.1.1] on iPhone 6 Plus / 10.1.1
