### ISSUE TITLE
[1.9.43] iPhone 5/10.1.1 Error displayed for No internet connection even 3G connection is ON.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#953]
Frequency: Always

Pre-Condition: Turn Off WiFi connection and set 3G connection.
1. Open Application and tap on Start.
2. Select any image or video and tap on Next.
3. Skip Music and tap on Next.
4. On preview screen tap on Export.
5. Tap on "Make Lomotif" and Verify displayed page.

Expected result: User should able to make Lomotif with 3G connection.

Actual result: Network error generated for 3G connection while tapping on "Make Lomotif".

Note: After tapping "OK" From error popup, Endless loading for export while tapping on Back.

![img_5085 1](https://cloud.githubusercontent.com/assets/17335200/20478547/93b479f0-b000-11e6-98e5-62a9f041ac5a.PNG)

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1
