### ISSUE TITLE
[1.9.43] iPhone 5/10.1.1 Content is not proper for "Saving your Lomotif" page.

### ISSUE THREAD

**Issue by Dipamit** [Lomotif/lomotif-ios-issues#954]
Frequency:  Always

1. open application and tap on start.
2. Select Image or video and tap on Next.
3. Skip Music and tap on Next.
4. On preview page tap on Export.
5. Verify displayed page.

Expected result: Content should proper.

Actual result: Displayed content is not proper.

![img_5088 1](https://cloud.githubusercontent.com/assets/17335200/20478735/5d7f567e-b001-11e6-9d3d-39da3d792b9c.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 5S / 9.3.5.

**Comment by xiuie** [comment]
Please check that this is fixed in the next build. Let me know if otherwise.
