### ISSUE TITLE
[1.9.43] iPhone 6S / 10.0.2, iPhone 6 Plus / 10.1.1 - Application is crashing after uploading a lomotif completes.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#957]
Frequency: Every time

Action:
1: Launch the app.
2: Login with valid credentials( Login with account which is created on "Android" device).
3: Tap on "START" and select few assets.
4: Skip the music and proceed to "Create" screen.
5: Apply any filter and tap on "Export" option.
6: Tap on "Make Lomotif" button.
7: Check if application is crashing after uploading progress completes.

Expected result: Application should not crash; user should be navigated to "Share" screen.

Actual result: Application is crashing after uploading a lomotif progress completes (100%).

Refer following video for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwZkRRcFY4NlIzeWs

Note: It is working as expected when user login with account which is created on iOS devices.

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

Uploading process complete 100% and then application crashes

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.52] on iPhone 6S / 10.0.2.
