### ISSUE TITLE
[1.9.43] iPhone 6 / 10.1.1 - Update Profile picture not working - Click on Profile picture to change user profile picture

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#958]
Frequency: Every time

Action:
1.Launch the app.
2. Login with valid credential
3. Go to User Profile page
4. Click on User profile picture to change it
5. Check whether user is able to change profile picture or not

Expected result: By clicking on Profile picture, user should be able to change profile picture

Actual result: User is not able to change profile picture

![img_1833](https://cloud.githubusercontent.com/assets/9691390/20486771/0f0f0c0c-b027-11e6-8268-ce270f5475b5.PNG)

**Comment by xiuie** [comment]
Please check that this is available for the next build.

**Comment by hiteshbheda** [comment]
@xiuie Ok. Thanks for update.

**Comment by xiuie** [comment]
Correction: Profile picture sync should be working already

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.
Profile picture section is not tappable on iOS devices.

Please see, Profile picture is not synced to iOS device when user change the profile picture form Android device.

**Comment by Dipamit** [comment]
@xiuie: Agree with @testershub 's Comment, Profile picture can not change on IOS device. 

Profile picture is not synced to IOS device when user change the profile picture from Android device.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
