### ISSUE TITLE
[1.9.43] iPhone 5S / 9.3.5 - User is not able to "Make Lomotif".

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#959]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create a lomotif.
3: Tap on "Export" option (User will be navigated to "Saving your Lomotif" screen)
4: Tap on text field to enter some text (Keypad will appears)
5: Check if user is able to make lomotif.

Expected result: 
1: Keypad should get disappear when user taps anywhere on the screen.
2: Keypad should not overlap on "Make Lomotif" button.

 Actual result: 
1: Keypad is overlapping on "Make Lomotif" button.
2: User is not able to "Make Lomotif".
3: Keypad is not disappearing after tapping anywhere on the screen.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iXzJoMUQ1SW1qbkE

Note: Issue is specifically observed on iPhone 5S / 9.3.5. 
For all devices, keypad is not disappeared after tapping anywhere on the screen.

**Comment by Dipamit** [comment]
@xiuie: Able to reproduce this issue on iPhone 5/10.1.1 for build 1.9.43

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 5S / 9.3.5
