### ISSUE TITLE
[1.7.0] iPhone 4s / 9.2.1- Vines bug - Animal vines seen in Dance vines

### ISSUE THREAD

**Issue by arif24888** [Lomotif/lomotif-ios-issues#96]
Frequency: Every time

Action
1. Open Lomotif and Tap start
2. Tap on Motif and select a vine from animals
3. Tap on drop down of Comedy vines(don't select)
4.. Finally, tap on drop down of Dance vines
5. The Animal vines are seen in Dance vines

Expected result: To select animal and dance vines
Actual result: The animal vines appears again in dance vines.

![img_4520](https://cloud.githubusercontent.com/assets/17019569/12969791/d89890fa-d0af-11e5-934d-d2d4f8333f47.PNG)
![img_4521](https://cloud.githubusercontent.com/assets/17019569/12969792/d8996822-d0af-11e5-906d-a13d3a3218a4.PNG)

**Comment by benchang** [comment]
@xiuie wants to replicate it, so I'll let her close this

**Comment by tsukisa** [comment]
@xiuie fixed with commit Lomotif/lomotif-ios@fa38209
