### ISSUE TITLE
[1.9.43] iPhone 5S / 9.3.5, iPad Mini 3 / 9.3.4 - Application is crashing when user export the lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#962]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START" and create lomotif with few motifs.
3: Tap on "Export" option.
4: Tap on "Make Lomotif" button.
5: Tap on back option "<" before exporting progress completes.
6: Error message "The operation couldn't be completed.." is displayed.
7: Tap on "OK" option on error message.
8: Observe black frame is displayed.
9: Tap on "Export" option. (Observe black frame is displayed.)
10: Tap back option "<".
11: Tap on "Export" option again.
12: Check if application is crashing.

Expected result: 
1: Error message "The operation couldn't be completed.." should not be displayed when user navigate back to "Create" screen form "Saving your Lomotif' screen.
2: Black frame should not be displayed when user close the error message.
3:  Application should not crash when user export the lomotif.

Actual result: 
1: Error message "The operation couldn't be completed.." is displayed when user navigate back to "Create" screen form "Saving your Lomotif' screen.
2: Black frame is displayed when user close the error message.
3:  Application is crashing when user export the lomotif.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iQk9PLUZNUzJxTFk

Note: Application is not crashing on iPhone 6 Plus / 10.1.1 and iPhone 6S / 10.0.2.

**Comment by Dipamit** [comment]
@xiuie: I am getting endless loading for exporting when i tap on back from "Save your Lomotif" or from "Make Lomotif".

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**But, by performing mentioned steps first time, application is not crashing but after performing the same process 3-4 times then application crash after getting error "The operation couldn't be completed.." "Cocoa -1"**

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 5S / 9.3.5 and iPad Mini / 9.3.4
