### ISSUE TITLE
[1.9.43] iPhone 6 Plus / 10.1.1 - Application is crashing when "Baking in Video" is in progress.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#963]
Frequency: Every time

Action:
1: Launch the app and login with valid credentials.
2: Tap on "START and select 1 video.
3: Tap on any music under "Find Music" tab (Loading process will be displayed)
4: Tap on tick while loading process is displayed.
5: Warning pop up "Do you want to proceed without music?" will be displayed.
6: Wait till loading process completes and user is navigated to "Create" screen once loading completes.
7: Observe "Do you want to proceed without music?" pop up is not disappeared.
8: Tap on "OK" option on pop up (Observe duplicate asset is getting created / displayed)
9: Enable filter toggle button and tap on "Export" option.
10: Tap on "Make Lomotif" button.
11: Check if application is crashing when "Baking in video" is in progress.

Expected result: 
1:  "Do you want to proceed without music?" pop up should get disappeared when user navigates to "Create' screen from "Find Music" screen.
2: Application should not crash while "Baking in Video" is in progress.

Actual result: 
1:  "Do you want to proceed without music?" pop up is not disappeared when user navigates to "Create' screen from "Find Music" screen.
2: Application is crashing while "Baking in Video" is in progress.

Refer following video link for more details:
https://drive.google.com/open?id=0ByjueaPWc0dwUXJfWmJqWElaOVE

Note: On iPhone 6S / 10.0.2 - Error "Error-unknown" is displayed while "Baking in video" is in progress.

**Comment by Dipamit** [comment]
@xiuie: Not able to reproduce this issue on iPhone 5/10.1.1. for build 1.9.43

**Comment by hiteshbheda** [comment]
@xiuie I can reproduce this issue for build [1.9.43] on iPhone 6 / iOS 10.1.1

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6 Plus / 10.1.1
