### ISSUE TITLE
[1.9.43] iPhone 6S / 10.0.2, iPhone 5S / 9.3.5 - Continuous loading is displayed when user load recently created lomotif.

### ISSUE THREAD

**Issue by testershub** [Lomotif/lomotif-ios-issues#967]
Frequency:Every time

Action:
1: Launch the app.
2: Login with valid credentials.
3: Tap on "START" and create lomotif with few motifs and with/without music.
4: Tap on "Home" option.(User will be navigated to "Home" screen)
5: Swipe up to "Profile" view and load the recently created lomotif.
6: Tap on "Export" option and export the lomotif.
7: Navigate back to "User profile" screen.
8: Tap on recently created lomotif.
9: Check if the continuous loading is displayed.

Expected result: Continuous loading should not be display and user should be navigated to "Create" screen.

Actual result: 
1: Continuous loading is displayed when user load recently created lomotif.
2: All other functionalities are functional(Like: User is able to tap on "Setting" option and swipe down to reveal "Home" screen) while continuous loading is displayed.

Refer following video link for more details:
https://drive.google.com/open?id=0B0-oVt0Gfy3iMnlPb1FBRnJGczg

**Comment by Dipamit** [comment]
@Xiuie: Not able to reproduce this issue on iPhone 5/10.1.1 for build 10.1.1

**Comment by hiteshbheda** [comment]
@xiuie I found 2 different observation here for this issue:

1. When I perform mentioned steps, then at step no. 6 After Exporting process uploading process starts and when Uploading process reach at 100% then application crash. (iOS issue #957)

2. And during step 6 execution of exporting process, if I click on Back (<) button then Exporting process continuously loading on the screen. (iOS issue #938 )

**Comment by testershub** [comment]
@xiuie I can't reproduce this issue for build [1.9.51] on iPhone 6S / 10.0.2
