### ISSUE TITLE
[1.9.44] iPhone 6 / 10.1.1 - Profile picture does not fetch from Facebook accouunt - Login with "Connect with Facebook" option and check User profile picture

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#969]
Frequency: Every time

Action:
1. Launch the app.
2. On login page, click on "Connect with Facebook" option
3. User will be logged in 
4. Go to User Profile page
5. Check whether user profile picture is available or not

Expected result: When user login with "Connect with Facebook" option then profile picture should also be fetched from facebook account

Actual result: Profile picture does not fetch from facebook account

![1](https://cloud.githubusercontent.com/assets/9691390/20550866/34492e5a-b160-11e6-966c-824b94c463c8.PNG)

![2](https://cloud.githubusercontent.com/assets/9691390/20550867/34deb9de-b160-11e6-8262-4b7efc92d270.PNG)

**Comment by Dipamit** [comment]
@xiuie : Unable to Login with Facebook. I am getting different behavior on tapping "Connect with Facebook" Device: iPhone 5/10.1.1 

1. While tapping on "Connect with Facebook" page navigate to Signup screen. (Screenshot 1)
2. On filling required data and tap on "Lets Go", "Server Busy... " error displayed. (Screenshot 2)

![img_5103 1](https://cloud.githubusercontent.com/assets/17335200/20560286/8ca0d6e6-b19e-11e6-82d0-02cc54b1534b.PNG)
![img_5129 1](https://cloud.githubusercontent.com/assets/17335200/20560308/a636313c-b19e-11e6-9313-b94601b62d89.PNG)

**Comment by xiuie** [comment]
@hiteshbheda This feature is not available for now.
