### ISSUE TITLE
[1.9.44] iPhone 6 / 10.1.1 - Irrevelant message display for Email change - Login with valid credential and change Email

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#971]
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential
3. Go to User Information page
4. Tap on Email field to change Email
5. Enter valid Email address
6. Check whether Email changed or not

Expected result: Email should be changed when user change and enter valid Email address

Actual result: Irrelevant / wrong error message display

![1](https://cloud.githubusercontent.com/assets/9691390/20551124/8b1f820e-b162-11e6-81cb-08413c911c13.PNG)

![2](https://cloud.githubusercontent.com/assets/9691390/20551125/8b55b87e-b162-11e6-915b-e4a154138d4c.PNG)

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.44] on iPhone 6 Plus / 10.1.1.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
