### ISSUE TITLE
[1.7.2] iPhone 6 / 9.2.1- Toggle Instagram vs Lomotif format  - App Crashing

### ISSUE THREAD

**Issue by xiuie** [Lomotif/lomotif-ios-issues#98]
Frequency: Every time

Action: 
1. Launch Lomotif 
2. Tap on Create lomotif
3. Select video files
5. Select any song 
6. Add sticker
7. Toggle between lomotif and instagram formats x ~10
9. App crash

Expected Result: Video toggled

Actual Result: Lomotif app crashes

Note: Select purple-haired sticker

Best to tap when the preview indicates that the video is still loading.

**Comment by tsukisa** [comment]
@xiuie unable to reproduce
