### ISSUE TITLE
[1.9.45] iPhone 6 / 10.1.1 - Same lomotifs in all users' account - Login with 2-3 different accounts and check LOMOTIFS tab

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#997]
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential
3. Tap on LOMOTIF tab on User profile page
4. Check and observe available lomotifs on user account
5. Log out / sign out from user's account
6. Login with other username and password
7. Go to LOMOTIFS tab and again observe available lomotifs in this user's account
8. Now, compare whether both (2 different) users have the same lomotifs or not in LOMOTIFS tab

Expected result: Available lomotifs in LOMOTIFS tab should be different and account specific

Actual result: In all users accounts, there are same lomotifs available in LOMOTIFS tab

![img_1891](https://cloud.githubusercontent.com/assets/9691390/20587165/f70d8c80-b230-11e6-8e23-5de17517f973.PNG)

![img_1895](https://cloud.githubusercontent.com/assets/9691390/20587166/f718e4d6-b230-11e6-83fc-d8382817fd0f.PNG)

**Comment by xiuie** [comment]
I can reproduce this on iPhone 6S/10.1.1 for build 1.9.45
Lomotifs aren't hidden on Logged out state.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
