### ISSUE TITLE
[1.9.45] iPhone 6 / 10.1.1 - Username and Password do not update on existing lomotifs - Change username and password for user account and play existing lomotifs

### ISSUE THREAD

**Issue by hiteshbheda** [Lomotif/lomotif-ios-issues#998]
Frequency: Every time

Action:
1. Launch the app.
2. Login with valid credential
3. Update username and password
4. Now, Tap on LOMOTIF tab on User profile page
5. From LOMOTIFS tab, play any existing lomotif
6. Observe username and profile picture on playing lomotif
7. Check whether username and profile picture is updated or not on playing screen

Expected result: On lomotif playing screen, username and password should update as they are already updated on user profile

Actual result: On lomotif playing screen, username and profile picture are not updated.

![img_1889](https://cloud.githubusercontent.com/assets/9691390/20587255/fcf6946a-b231-11e6-9cfa-8c40f1503bcb.PNG)

![img_1890](https://cloud.githubusercontent.com/assets/9691390/20587256/fd278174-b231-11e6-9a87-88ce60472d6e.PNG)

**Comment by xiuie** [comment]
I can't reproduce this for build 1.9.45 on iPhone 6S/10.1.1

**Comment by testershub** [comment]
@xiuie I can reproduce this issue for build [1.9.45] on iPhone 6 Plus / 10.1.1 and iPhone 5S / 9.3.5.

**Comment by hiteshbheda** [comment]
@xiuie I can't reproduce this issue for build [2.1.0] on iPhone 6 / iOS 10.1.1

You can close this issue for build [2.1.0]
